stages:
   - build

build_angular:
  stage: build
  tags:
  - dev
  script:
      - cd frontend
      - npm install -q
      - ng build --prod 
  only:
  - NewUpdate
  artifacts:
    paths:
      - frontend/node_modules/
    expire_in: 1 week
