stages:
   - install_dependencies
   - build
   - test
   - deployangular
install_dependencies:
  stage: install_dependencies
  tags:
  - dev-server
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - frontend/node_modules/
  script:
    - cd frontend
    - npm ci
  only:
    changes:
      - frontend/package-lock.json

build_angular:
  stage: build
  tags:
  - dev-server
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - frontend/node_modules/
    policy: pull

  script:
      - cd frontend
      - ng build --configuration=dev --aot
  only:
  - dev
  artifacts:
    name: ${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}
    paths:
      - frontend/dist
    expire_in: 1 hour


 
sonar-angular:
  stage: test
  image: trion/ng-cli:latest
  script:
    - cd frontend
    - npm install -g sonarqube-scanner
    # - >
    #   sonar-scanner
    #   -Dsonar.projectKey=elitech-ecole_ems2_AXuPM7gG38mGkzIHXcIr
    #   -Dsonar.host.url=http://51.68.215.184:9000
    #   -Dsonar.login=fc8633efd4b1d7da6613efb22ab4226c1d8d7e29
    #   -Dsonar.typescript.lcov.reportPaths=coverage/lcov/lcov.info
    #   -Dsonar.sourceEncoding=UTF-8
    #   -Dsonar.sources=src/app
    #   -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts
    #   -Dsonar.tests=src/app
    #   -Dsonar.test.inclusions=**/*.spec.ts
  allow_failure: true
  only:
    - dev
  tags:
    - dev-docker

deployangular_todev:
  stage: deployangular
  tags:
    - dev-server
  script:
    - sudo mv frontend/dist /var/www/html/ems
  only:
  - dev
