stages:
   - install_dependencies
   - build
install_dependencies:
  stage: install_dependencies
  tags:
  - dev
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - frontend/node_modules/
  script:
    - cd frontend
    - npm ci
  only:
    - NewUpdate
    # changes:
    #   - frontend/package-lock.json


build_angular:
  stage: build
  tags:
  - dev
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - frontend/node_modules/
    policy: pull

  script:
      - cd frontend
      - ng build --prod 
  only:
  - NewUpdate
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 week




