stages:
   - install_dependencies
   - build
   - deployangular
install_dependencies:
  stage: install_dependencies
  tags:
  - dev
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - frontend/node_modules/
  script:
    - cd frontend
    - npm ci
  only:
    changes:
      - frontend/package-lock.json

build_angular:
  stage: build
  tags:
  - dev
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - frontend/node_modules/
    policy: pull

  script:
      - cd frontend
      - ng build --prod 
  only:
  - NewUpdate
  artifacts:
    name: ${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}
    paths:
      - frontend/dist
    expire_in: 1 hour


deployangular_todev:
  stage: deployangular
  tags:
    - dev
  script:
    - ls frontend 
  only:
  - NewUpdate
