stages:
   - install_dependencies
   - build
   - test
   - deployangular
install_dependencies:
  stage: install_dependencies
  tags:
  - dev-server
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - frontend/node_modules/
  script:
    - cd frontend
    - npm ci
  only:
    changes:
      - frontend/package-lock.json

build_angular:
  stage: build
  tags:
  - dev-server
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - frontend/node_modules/
    policy: pull

  script:
      - cd frontend
      - ng build --configuration=dev --aot
  only:
  - dev
  artifacts:
    name: ${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}
    paths:
      - frontend/dist
    expire_in: 1 hour
  when: manual
 
# sonar-angular:
#   stage: test
#   image: trion/ng-cli:latest
#   script:
#     - cd frontend
#     - npm install -g sonarqube-scanner
#     - >
#       sonar-scanner
#       -Dsonar.projectKey=Typlosion14_estya-ticketing_AXzlBhDN1eE81W_XHtj1
#       -Dsonar.host.url="$SONAR_HOST_URL"
#       -Dsonar.login=c544ce01591fdf08382e33570de9cdbc4b16aea3
#       -Dsonar.typescript.lcov.reportPaths=coverage/lcov/lcov.info
#       -Dsonar.sourceEncoding=UTF-8
#       -Dsonar.sources=src/app
#       -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts
#       -Dsonar.tests=src/app
#       -Dsonar.test.inclusions=**/*.spec.ts

#   allow_failure: true
#   only:
#     - dev
#   tags:
#     - dev-docker
#   when: manual
# deployangular_todev:
#   stage: deployangular
#   tags:
#     - dev-server
#   script:
#     - sudo mv frontend/dist /var/www/html/ems
#   only:
#   - dev
#   when: manual

# sonar-node:
#   stage: test
#   image: sonarsource/sonar-scanner-cli
#   needs: []
#   dependencies: []
#   script:
    # - cd backend
    # - >
    #   sonar-scanner 
    #   -Dsonar.projectKey=Typlosion14_estya-ticketing_AXzf-Al-1eE81W_XHtjA
    #   -Dsonar.host.url="$SONAR_HOST_URL"
    #   -Dsonar.login="$SONAR_TOKEN"
    #   -Dsonar.sources=frontend/src/app
    #   -Dsonar.sources=backend/

#   allow_failure: true
#   variables:
#     SONAR_PROJECT_BASE_DIR: "${CI_PROJECT_DIR}"
#     GIT_DEPTH: 0
#   cache:
#     key: "sonar-${CI_PROJECT_ID}"
#     paths:
#       - ".scannerwork"
#       - ".sonar"
#   tags:
#     - dev-docker
#   when: manual 
sonarqube-check:
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - >
      sonar-scanner 
      -Dsonar.projectKey=Typlosion14_estya-ticketing_AXzlBhDN1eE81W_XHtj1
      -Dsonar.qualitygate.wait=true
      -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts, 
      -Dsonar.test.inclusions=**/*.spec.ts
      -Dsonar.sources=frontend/src/app,backend/controllers,backend/models,backend/middleware


  allow_failure: true
  only:
    - dev # or the name of your main branch
