version: "3.9"
services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      DB_USER: root
      DB_PASSWORD: 
      DB_HOST: localhost
      DB_PORT: 27017
      DB_NAME: # FIXME sample-db
    ports: 
      - '27017-27019:27017-27019'
    volumes:
      - mongo_data:/data/db
      # Add the db-init.js file to the Mongo DB container
      # - ./db-init.js:/docker-entrypoint-initdb.d/init.js:ro

  back:
    build: back
    restart: always
    environment:
      MONGODB_URI: mongodb://127.0.0.1:27017
    depends_on:
      - mongodb
    ports:
      # local->container
      - '3000:3000'

  front:
    build: front
    restart: always
    ports:
      # local->container
      - '4200:4200'

  forms-app:
    build: forms-app
    restart: always
    ports:
      # local->container
      - '4210:4210'

volumes:
  mongo_data: {}


# docker compose up # -d