import { User } from "./User";

export class Entreprise {

    constructor(
        public _id?: string,
        public r_sociale?: string,
        public fm_juridique?: string,
        public activite?: string,
        public type_ent?: string,
        public categorie?: string,
        public isInterne?: Boolean,
        public crc?: string,
        public nb_salarie?: Number,
        public convention?: string,
        public idcc?: string,
        public indicatif_ent?: Number,
        public phone_ent?: Number,
        public adresse_ent?: string,
        public code_postale_ent?: Number,
        public ville_ent?: string,
        public adresse_ec?: string,
        public postal_ec?: Number,
        public ville_ec?: string,
        public siret?: Number,
        public code_ape_naf?: string, 
        public num_tva?: string,
        public telecopie?: string,
        public OPCO?: string,
        public organisme_prevoyance?: string,
        public civilite_rep?: string,
        public nom_rep?: string,
        public prenom_rep?: string,
        public email_rep?: string,
        public indicatif_rep?: Number,
        public phone_rep?: Number,
        public indicatif_rep_wt?: Number,
        public phone_rep_wt?: Number,
        public isTuteur?: Boolean,
        public civilite_tuteur?: string,
        public nom_tuteur?: string,
        public prenom_tuteur?: string,
        public email_tuteur?: string,
        public indicatif_tuteur?: Number,
        public phone_tuteur?: Number,
        public indicatif_tuteur_wt?: Number,
        public phone_tuteur_wt?: Number,
        public date_naissance_tuteur?: Date,
        public fonction_tuteur?: string,
        public anciennete_tuteur?: Number,
        public niveau_etude_tuteur?: Number,
        public Directeur_id?: User,
    ) { }

}