import { User } from "./User";

export class Entreprise {

    constructor(
        public _id?: string,
        public r_sociale?: string,
        public fm_juridique?: string,
        public vip?: number,
        public type_ent?: string,
        public isInterne?: boolean,
        public siret?: string,
        public code_ape_naf?: string,
        public num_tva?: string,
        public nom_contact?: string,
        public prenom_contact?: string,
        public fc_contact?: string,
        public email_contact?: string,
        public phone_contact?: string,
        public nom_contact_2nd?: string,
        public prenom_contact_2nd?: string,
        public fc_contact_2nd?: string,
        public email_contact_2nd?: string,
        public phone_contact_2nd?: string,
        public pays_adresse?: string,
        public ville_adresse?: string,
        public rue_adresse?: string,
        public numero_adresse?: number,
        public postal_adresse?: string,
        public email?: string,
        public phone?: string,
        public website?: string,
        public financeur?: string,
        public nda?: string,
        public type_soc?: string,
        public categorie?: string[],
        public Directeur_id?: User,
        public activite?: string,
        public adresse_ec?: string,
        public postal_ec?: string,
        public ville_ec?: string,
        public crc?: string,
        public convention?: string,
        public telecopie?: string,
        public nb_salarie?: string,
        public idcc?: string,
        public indicatif?: string,
        public OPCO?: string,
        public organisme_prevoyance?: string,

    ) { }

}