export class LeadCRM {
    constructor(
        public source?: string,
        public operation?: string,
        public civilite?: string,
        public nom?: string,
        public prenom?: string,
        public pays_residence?: string,
        public email?: string,
        public indicatif_phone?: string,
        public numero_phone?: string,
        public date_naissance?: Date,
        public nationalite?: string,
        public indicatif_whatsapp?: string,
        public numero_whatsapp?: string,
        public indicatif_telegram?: string,
        public numero_telegram?: string,
        public dernier_niveau_academique?: string,
        public statut?: string,
        public niveau_fr?: string,
        public niveau_en?: string,
        public custom_id?: string,
        public date_contact?: Date,
        public contact_by?: string,
        public canal?: string,
        public suite_contact?: string,
        public note?: string,
        public produit?: string,
        public date_paiement?: Date,
        public montant_paye?: string,
        public modalite_paiement?: string,
        public date_envoie?: Date,
        public objet_mail?: string,
        public send_mail?: string,
        public decision_qualification?: string,
    ) { }

}