// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --configuration=prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  recaptchaKey: '6LeR3hgpAAAAAFs7Tyh3IIhpnyBpzs1AgAcOM6aU ',
  origin: "https://ims.intedgroup.com/soc/",
  key: "6abdfb04243e096a4a51b46c8f3d4b32",
  User: null,
  clientId: "c2fdb74f-1c56-4ebb-872b-0e0279e91612",
  filterFR: {
    "startsWith": "Commence par",
    "contains": "Contiens",
    "notContains": "Ne contiens pas",
    "endsWith": "Fini par",
    "equals": "Corresponds à",
    "notEquals": "Ne corresponds pas à",
    "noFilter": "Sans Filtre",
    "lt": "Plus petit que",
    "lte": "Plus petit ou égal à",
    "gt": "Plus grand que",
    "gte": "Plus grand ou égal à",
    "is": "est",
    "isNot": "n'est pas",
    "before": "Avant",
    "after": "Après",
    "dateIs": "Date est",
    "dateIsNot": "Date n'est pas",
    "dateBefore": "Date est avant",
    "dateAfter": "Date est après",
    "clear": "Vider",
    "apply": "Filtrer",
    "matchAll": "Correponds à tous",
    "matchAny": "Correponds à l'un d'eux",
    "addRule": "Ajouter un Filtre",
    "removeRule": "Supprimer le Filtre",
    "accept": "Oui",
    "reject": "Non",
    "choose": "Choisir",
    "upload": "Upload",
    "cancel": "Annuler",
    dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
    dayNamesShort: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
    monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
    monthNamesShort: ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Jun', 'Jul', 'Aoû', 'Sep', 'Oct', 'Nov', 'Déc'],
    dateFormat: 'dd-mm-yy',
    "firstDayOfWeek": 0,
    today: 'Aujourdhui',
    weekHeader: 'sem',
    "weak": 'Faible',
    "medium": 'Moyen',
    "strong": 'Fort',
    "passwordPrompt": 'Entrer un mot de passe',
    "emptyMessage": 'Aucun résultat',
    "emptyFilterMessage": 'Aucun résultat'
  },
  fr: {
    firstDayOfWeek: 0,
    dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
    dayNamesShort: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
    monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
    monthNamesShort: ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Jun', 'Jul', 'Aoû', 'Sep', 'Oct', 'Nov', 'Déc'],
    today: 'Aujourdhui',
    clear: 'Clear',
    dateFormat: 'dd-mm-yy',
    weekHeader: 'sem'
  },
  colorPaletteGreen: [
    "#b7de6a",
    "#486b03",
    "#79a324",
    "#cafa6b",
    "#c1db8c",
    "#6e9422",
    "#abb39b",
    "#b6e657",
    "#B2C787",
    "#8c9678",
  ],
  role: [
    { value: 'Agent' },
    { value: 'Responsable' }
  ],

  typeUser: [
    { value: "Initial" },
    { value: "Salarié" },
    { value: "Alternant/Stagiaire" },
  ],

  campus: [
    { value: "Paris" },
    { value: "Montpellier" },
    { value: "Dubai" },
    { value: "Montréal" },
    { value: "Londres" },
    { value: "Tunis" },
    { value: "En Ligne(365)" }
  ],

  isoCodes: [
    { value: "AD", label: "Andorre", prep: "en" },
    { value: "AE", label: "Émirats Arabes Unis", prep: "aux" },
    { value: "AF", label: "Afghanistan", prep: "en" },
    { value: "AG", label: "Antigua-Et-Barbuda", prep: "à" },
    { value: "AI", label: "Anguilla", prep: "à" },
    { value: "AL", label: "Albanie", prep: "en" },
    { value: "AM", label: "Arménie", prep: "en" },
    { value: "AO", label: "Angola", prep: "en" },
    { value: "AP", label: "Région Asie/Pacifique", prep: "dans la" },
    { value: "AQ", label: "Antarctique", prep: "en" },
    { value: "AR", label: "Argentine", prep: "en" },
    { value: "AS", label: "Samoa Américaines", prep: "aux" },
    { value: "AT", label: "Autriche", prep: "en" },
    { value: "AU", label: "Australie", prep: "en" },
    { value: "AW", label: "Aruba", prep: "à" },
    { value: "AX", label: "Îles Åland", prep: "aux" },
    { value: "AZ", label: "Azerbaïdjan", prep: "en" },
    { value: "BA", label: "Bosnie-Herzégovine", prep: "en" },
    { value: "BB", label: "Barbade", prep: "à" },
    { value: "BD", label: "Bangladesh", prep: "au" },
    { value: "BE", label: "Belgique", prep: "en" },
    { value: "BF", label: "Burkina Faso", prep: "au" },
    { value: "BG", label: "Bulgarie", prep: "en" },
    { value: "BH", label: "Bahreïn", prep: "à" },
    { value: "BI", label: "Burundi", prep: "au" },
    { value: "BJ", label: "Bénin", prep: "au" },
    { value: "BL", label: "Saint-Barthélemy", prep: "à" },
    { value: "BM", label: "Bermudes", prep: "aux" },
    { value: "BN", label: "Brunei Darussalam", prep: "au" },
    { value: "BO", label: "État Plurinational De Bolivie", prep: "en" },
    { value: "BQ", label: "Bonaire, Saint-Eustache Et Saba", prep: "à" },
    { value: "BR", label: "Brésil", prep: "au" },
    { value: "BS", label: "Bahamas", prep: "aux" },
    { value: "BT", label: "Bhoutan", prep: "au" },
    { value: "BV", label: "Île Bouvet", prep: "sur" },
    { value: "BW", label: "Botswana", prep: "au" },
    { value: "BY", label: "Biélorussie", prep: "en" },
    { value: "BZ", label: "Belize", prep: "au" },
    { value: "CA", label: "Canada", prep: "au" },
    { value: "CC", label: "Îles Cocos", prep: "aux" },
    { value: "CD", label: "République Démocratique Du Congo", prep: "en" },
    { value: "CF", label: "République Centrafricaine", prep: "en" },
    { value: "CG", label: "Congo", prep: "au" },
    { value: "CH", label: "Suisse", prep: "en" },
    { value: "CI", label: "Côte D'Ivoire", prep: "en" },
    { value: "CK", label: "Îles Cook", prep: "aux" },
    { value: "CL", label: "Chili", prep: "au" },
    { value: "CM", label: "Cameroun", prep: "au" },
    { value: "CN", label: "Chine", prep: "en" },
    { value: "CO", label: "Colombie", prep: "en" },
    { value: "CR", label: "Costa Rica", prep: "au" },
    { value: "CU", label: "Cuba", prep: "à" },
    { value: "CV", label: "Cap-Vert", prep: "au" },
    { value: "CW", label: "Curaçao", prep: "à" },
    { value: "CX", label: "Île Christmas", prep: "à" },
    { value: "CY", label: "Chypre", prep: "à" },
    { value: "CZ", label: "République Tchèque", prep: "en" },
    { value: "DE", label: "Allemagne", prep: "en" },
    { value: "DJ", label: "Djibouti", prep: "à" },
    { value: "DK", label: "Danemark", prep: "au" },
    { value: "DM", label: "Dominique", prep: "à" },
    { value: "DO", label: "République Dominicaine", prep: "en" },
    { value: "DZ", label: "Algérie", prep: "en" },
    { value: "EC", label: "Équateur", prep: "en" },
    { value: "EE", label: "Estonie", prep: "en" },
    { value: "EG", label: "Égypte", prep: "en" },
    { value: "EH", label: "Sahara Occidental", prep: "au" },
    { value: "ER", label: "Érythrée", prep: "en" },
    { value: "ES", label: "Espagne", prep: "en" },
    { value: "ET", label: "Éthiopie", prep: "en" },
    { value: "EU", label: "Europe", prep: "en" },
    { value: "FI", label: "Finlande", prep: "en" },
    { value: "FJ", label: "Fidji", prep: "aux" },
    { value: "FK", label: "Îles Falkland", prep: "aux" },
    { value: "FM", label: "Micronésie, États Fédérés De", prep: "aux" },
    { value: "FO", label: "Îles Féroé", prep: "aux" },
    { value: "FR", label: "France", prep: "en" },
    { value: "GA", label: "Gabon", prep: "au" },
    { value: "GB", label: "Royaume-Uni", prep: "au" },
    { value: "GD", label: "Grenade", prep: "à" },
    { value: "GE", label: "Géorgie", prep: "en" },
    { value: "GF", label: "Guyane Française", prep: "en" },
    { value: "GG", label: "Guernesey", prep: "à" },
    { value: "GH", label: "Ghana", prep: "au" },
    { value: "GI", label: "Gibraltar", prep: "à" },
    { value: "GL", label: "Groenland", prep: "au" },
    { value: "GM", label: "Gambie", prep: "en" },
    { value: "GN", label: "Guinée", prep: "en" },
    { value: "GP", label: "Guadeloupe", prep: "en" },
    { value: "GQ", label: "Guinée Équatoriale", prep: "en" },
    { value: "GR", label: "Grèce", prep: "en" },
    { value: "GS", label: "Géorgie Du Sud Et Les Îles Sandwich Du Sud", prep: "en" },
    { value: "GT", label: "Guatemala", prep: "au" },
    { value: "GU", label: "Guam", prep: "à" },
    { value: "GW", label: "Guinée-Bissau", prep: "en" },
    { value: "GY", label: "Guyana", prep: "en" },
    { value: "HK", label: "Région Administrative Spéciale De Hong Kong", prep: "à" },
    { value: "HM", label: "Îles Heard Et McDonald", prep: "aux" },
    { value: "HN", label: "Honduras", prep: "au" },
    { value: "HR", label: "Croatie", prep: "en" },
    { value: "HT", label: "Haïti", prep: "en" },
    { value: "HU", label: "Hongrie", prep: "en" },
    { value: "ID", label: "Indonésie", prep: "en" },
    { value: "IE", label: "Irlande", prep: "en" },
    { value: "IL", label: "Israël", prep: "en" },
    { value: "IM", label: "Île De Man", prep: "à" },
    { value: "IN", label: "Inde", prep: "en" },
    { value: "IO", label: "Territoire Britannique De L'Océan Indien", prep: "au" },
    { value: "IQ", label: "Irak", prep: "en" },
    { value: "IR", label: "Iran, République Islamique D'", prep: "en" },
    { value: "IS", label: "Islande", prep: "en" },
    { value: "IT", label: "Italie", prep: "en" },
    { value: "JE", label: "Jersey", prep: "à" },
    { value: "JM", label: "Jamaïque", prep: "en" },
    { value: "JO", label: "Jordanie", prep: "en" },
    { value: "JP", label: "Japon", prep: "au" },
    { value: "KE", label: "Kenya", prep: "au" },
    { value: "KG", label: "Kirghizistan", prep: "au" },
    { value: "KH", label: "Cambodge", prep: "au" },
    { value: "KI", label: "Kiribati", prep: "aux" },
    { value: "KM", label: "Comores", prep: "aux" },
    { value: "KN", label: "Saint-Kitts-Et-Nevis", prep: "à" },
    { value: "KP", label: "Corée, République Populaire Démocratique De", prep: "en" },
    { value: "KR", label: "Corée, République De", prep: "en" },
    { value: "KW", label: "Koweït", prep: "au" },
    { value: "KY", label: "Îles Caïmans", prep: "aux" },
    { value: "KZ", label: "Kazakhstan", prep: "au" },
    { value: "LA", label: "République Démocratique Populaire Lao", prep: "en" },
    { value: "LB", label: "Liban", prep: "au" },
    { value: "LC", label: "Sainte-Lucie", prep: "à" },
    { value: "LI", label: "Liechtenstein", prep: "au" },
    { value: "LK", label: "Sri Lanka", prep: "au" },
    { value: "LR", label: "Libéria", prep: "au" },
    { value: "LS", label: "Lesotho", prep: "au" },
    { value: "LT", label: "Lituanie", prep: "en" },
    { value: "LU", label: "Luxembourg", prep: "au" },
    { value: "LV", label: "Lettonie", prep: "en" },
    { value: "LY", label: "Libye", prep: "en" },
    { value: "MA", label: "Maroc", prep: "au" },
    { value: "MC", label: "Monaco", prep: "à" },
    { value: "MD", label: "Moldavie, République De", prep: "en" },
    { value: "ME", label: "Monténégro", prep: "au" },
    { value: "MC", label: "Monaco", prep: "à" },
    { value: "MD", label: "Moldavie, République De", prep: "en" },
    { value: "ME", label: "Monténégro", prep: "au" },
    { value: "MF", label: "Saint-Martin (Partie Française)", prep: "à" },
    { value: "MG", label: "Madagascar", prep: "à" },
    { value: "MH", label: "Îles Marshall", prep: "aux" },
    { value: "MK", label: "Macédoine, L'Ex-République Yougoslave De", prep: "en" },
    { value: "ML", label: "Mali", prep: "au" },
    { value: "MM", label: "Myanmar", prep: "au" },
    { value: "MN", label: "Mongolie", prep: "en" },
    { value: "MO", label: "Région Administrative Spéciale De Macao", prep: "à" },
    { value: "MP", label: "Îles Mariannes Du Nord", prep: "aux" },
    { value: "MQ", label: "Martinique", prep: "en" },
    { value: "MR", label: "Mauritanie", prep: "en" },
    { value: "MS", label: "Montserrat", prep: "à" },
    { value: "MT", label: "Malte", prep: "à" },
    { value: "MU", label: "Maurice", prep: "à" },
    { value: "MV", label: "Maldives", prep: "aux" },
    { value: "MW", label: "Malawi", prep: "au" },
    { value: "MX", label: "Mexique", prep: "au" },
    { value: "MY", label: "Malaisie", prep: "en" },
    { value: "MZ", label: "Mozambique", prep: "au" },
    { value: "NA", label: "Namibie", prep: "en" },
    { value: "NC", label: "Nouvelle-Calédonie", prep: "en" },
    { value: "NE", label: "Niger", prep: "au" },
    { value: "NF", label: "Île Norfolk", prep: "à" },
    { value: "NG", label: "Nigéria", prep: "au" },
    { value: "NI", label: "Nicaragua", prep: "au" },
    { value: "NL", label: "Pays-Bas", prep: "aux" },
    { value: "NO", label: "Norvège", prep: "en" },
    { value: "NP", label: "Népal", prep: "au" },
    { value: "NR", label: "Nauru", prep: "à" },
    { value: "NU", label: "Nioué", prep: "à" },
    { value: "NZ", label: "Nouvelle-Zélande", prep: "en" },
    { value: "OM", label: "Oman", prep: "en" },
    { value: "PA", label: "Panama", prep: "au" },
    { value: "PE", label: "Pérou", prep: "au" },
    { value: "PF", label: "Polynésie Française", prep: "en" },
    { value: "PG", label: "Papouasie-Nouvelle-Guinée", prep: "en" },
    { value: "PH", label: "Philippines", prep: "aux" },
    { value: "PK", label: "Pakistan", prep: "au" },
    { value: "PL", label: "Pologne", prep: "en" },
    { value: "PM", label: "Saint-Pierre-Et-Miquelon", prep: "à" },
    { value: "PN", label: "Îles Pitcairn", prep: "aux" },
    { value: "PR", label: "Porto Rico", prep: "à" },
    { value: "PS", label: "Territoire Palestinien Occupé", prep: "en" },
    { value: "PT", label: "Portugal", prep: "au" },
    { value: "PW", label: "Palaos", prep: "aux" },
    { value: "PY", label: "Paraguay", prep: "au" },
    { value: "QA", label: "Qatar", prep: "au" },
    { value: "RE", label: "Réunion", prep: "à" },
    { value: "RO", label: "Roumanie", prep: "en" },
    { value: "RS", label: "Serbie", prep: "en" },
    { value: "RU", label: "Fédération De Russie", prep: "en" },
    { value: "RW", label: "Rwanda", prep: "au" },
    { value: "SA", label: "Arabie Saoudite", prep: "en" },
    { value: "SB", label: "Îles Salomon", prep: "aux" },
    { value: "SC", label: "Seychelles", prep: "aux" },
    { value: "SD", label: "Soudan", prep: "au" },
    { value: "SE", label: "Suède", prep: "en" },
    { value: "SG", label: "Singapour", prep: "à" },
    { value: "SH", label: "Sainte-Hélène, Ascension Et Tristan Da Cunha", prep: "à" },
    { value: "SI", label: "Slovénie", prep: "en" },
    { value: "SJ", label: "Svalbard Et Jan Mayen", prep: "à" },
    { value: "SK", label: "Slovaquie", prep: "en" },
    { value: "SL", label: "Sierra Leone", prep: "en" },
    { value: "SM", label: "Saint-Marin", prep: "à" },
    { value: "SN", label: "Sénégal", prep: "au" },
    { value: "SO", label: "Somalie", prep: "en" },
    { value: "SR", label: "Surinam", prep: "au" },
    { value: "SS", label: "Soudan Du Sud", prep: "au" },
    { value: "SM", label: "Saint-Marin", prep: "à" },
    { value: "SN", label: "Sénégal", prep: "au" },
    { value: "SO", label: "Somalie", prep: "en" },
    { value: "SR", label: "Surinam", prep: "au" },
    { value: "SS", label: "Soudan Du Sud", prep: "au" },
    { value: "ST", label: "Sao Tomé-Et-Principe", prep: "à" },
    { value: "SV", label: "El Salvador", prep: "au" },
    { value: "SX", label: "Saint-Martin (Partie Néerlandaise)", prep: "à" },
    { value: "SY", label: "République Arabe Syrienne", prep: "en" },
    { value: "SZ", label: "Eswatini", prep: "en" },
    { value: "TC", label: "Îles Turks Et Caïques", prep: "aux" },
    { value: "TD", label: "Tchad", prep: "au" },
    { value: "TF", label: "Terres Australes Françaises", prep: "aux" },
    { value: "TG", label: "Togo", prep: "au" },
    { value: "TH", label: "Thaïlande", prep: "en" },
    { value: "TJ", label: "Tadjikistan", prep: "au" },
    { value: "TK", label: "Tokelau", prep: "à" },
    { value: "TL", label: "Timor-Leste", prep: "au" },
    { value: "TM", label: "Turkménistan", prep: "au" },
    { value: "TN", label: "Tunisie", prep: "en" },
    { value: "TO", label: "Tonga", prep: "aux" },
    { value: "TR", label: "Turquie", prep: "en" },
    { value: "TT", label: "Trinité-Et-Tobago", prep: "à" },
    { value: "TV", label: "Tuvalu", prep: "à" },
    { value: "TW", label: "Taïwan, Province De Chine", prep: "à" },
    { value: "TZ", label: "Tanzanie, République-Unie De", prep: "en" },
    { value: "UA", label: "Ukraine", prep: "en" },
    { value: "UG", label: "Ouganda", prep: "en" },
    { value: "UM", label: "Îles Mineures Éloignées Des États-Unis", prep: "aux" },
    { value: "US", label: "États-Unis", prep: "aux" },
    { value: "UY", label: "Uruguay", prep: "en" },
    { value: "UZ", label: "Ouzbékistan", prep: "en" },
    { value: "VA", label: "État De La Cité Du Vatican", prep: "à" },
    { value: "VC", label: "Saint-Vincent-Et-Les Grenadines", prep: "à" },
    { value: "VE", label: "Venezuela, République Bolivarienne Du", prep: "en" },
    { value: "VG", label: "Îles Vierges Britanniques", prep: "aux" },
    { value: "VI", label: "Îles Vierges Des États-Unis", prep: "aux" },
    { value: "VN", label: "Viet Nam", prep: "au" },
    { value: "VU", label: "Vanuatu", prep: "au" },
    { value: "WF", label: "Wallis Et Futuna", prep: "à" },
    { value: "WS", label: "Samoa", prep: "aux" },
    { value: "YE", label: "Yémen", prep: "au" },
    { value: "YT", label: "Mayotte", prep: "à" },
    { value: "ZA", label: "Afrique Du Sud", prep: "en" },
    { value: "ZM", label: "Zambie", prep: "en" },
    { value: "ZW", label: "Zimbabwe", prep: "au" }
  ],

  pays: [ //default [76]
    { value: 'Aruba', label: 'Aruba' },
    { value: 'Afghanistan', label: 'Afghanistan' },
    { value: 'Angola', label: 'Angola' },
    { value: 'Anguilla', label: 'Anguilla' },
    { value: 'Ahvenanmaa', label: 'Ahvenanmaa' },
    { value: 'Albanie', label: 'Albanie' },
    { value: 'Andorre', label: 'Andorre' },
    { value: 'Émirats arabes unis', label: 'Émirats arabes unis' },
    { value: 'Argentine', label: 'Argentine' },
    { value: 'Arménie', label: 'Arménie' },
    { value: 'Samoa américaines', label: 'Samoa américaines' },
    { value: 'Antarctique', label: 'Antarctique' },
    { value: 'Terres australes et antarctiques françaises', label: 'Terres australes et antarctiques françaises' },
    { value: 'Antigua-et-Barbuda', label: 'Antigua-et-Barbuda' },
    { value: 'Australie', label: 'Australie' },
    { value: 'Autriche', label: 'Autriche' },
    { value: 'Azerbaïdjan', label: 'Azerbaïdjan' },
    { value: 'Burundi', label: 'Burundi' },
    { value: 'Belgique', label: 'Belgique' },
    { value: 'Bénin', label: 'Bénin' },
    { value: 'Burkina Faso', label: 'Burkina Faso' },
    { value: 'Bangladesh', label: 'Bangladesh' },
    { value: 'Bulgarie', label: 'Bulgarie' },
    { value: 'Bahreïn', label: 'Bahreïn' },
    { value: 'Bahamas', label: 'Bahamas' },
    { value: 'Bosnie-Herzégovine', label: 'Bosnie-Herzégovine' },
    { value: 'Saint-Barthélemy', label: 'Saint-Barthélemy' },
    { value: 'Sainte-Hélène, Ascension et Tristan da Cunha', label: 'Sainte-Hélène, Ascension et Tristan da Cunha' },
    { value: 'Biélorussie', label: 'Biélorussie' },
    { value: 'Belize', label: 'Belize' },
    { value: 'Bermudes', label: 'Bermudes' },
    { value: 'Bolivie', label: 'Bolivie' },
    { value: 'Pays-Bas caribéens', label: 'Pays-Bas caribéens' },
    { value: 'Brésil', label: 'Brésil' },
    { value: 'Barbade', label: 'Barbade' },
    { value: 'Brunei', label: 'Brunei' },
    { value: 'Bhoutan', label: 'Bhoutan' },
    { value: 'Île Bouvet', label: 'Île Bouvet' },
    { value: 'Botswana', label: 'Botswana' },
    { value: 'République centrafricaine', label: 'République centrafricaine' },
    { value: 'Canada', label: 'Canada' },
    { value: 'Îles Cocos', label: 'Îles Cocos' },
    { value: 'Suisse', label: 'Suisse' },
    { value: 'Chili', label: 'Chili' },
    { value: 'Chine', label: 'Chine' },
    { value: 'Côte d\'Ivoire', label: 'Côte d\'Ivoire' },
    { value: 'Cameroun', label: 'Cameroun' },
    { value: 'Congo (Rép. dém.)', label: 'Congo (Rép. dém.)' },
    { value: 'Congo', label: 'Congo' },
    { value: 'Îles Cook', label: 'Îles Cook' },
    { value: 'Colombie', label: 'Colombie' },
    { value: 'Comores', label: 'Comores' },
    { value: 'Îles du Cap-Vert', label: 'Îles du Cap-Vert' },
    { value: 'Costa Rica', label: 'Costa Rica' },
    { value: 'Cuba', label: 'Cuba' },
    { value: 'Curaçao', label: 'Curaçao' },
    { value: 'Île Christmas', label: 'Île Christmas' },
    { value: 'Îles Caïmans', label: 'Îles Caïmans' },
    { value: 'Chypre', label: 'Chypre' },
    { value: 'Tchéquie', label: 'Tchéquie' },
    { value: 'Allemagne', label: 'Allemagne' },
    { value: 'Djibouti', label: 'Djibouti' },
    { value: 'Dominique', label: 'Dominique' },
    { value: 'Danemark', label: 'Danemark' },
    { value: 'République dominicaine', label: 'République dominicaine' },
    { value: 'Algérie', label: 'Algérie' },
    { value: 'Équateur', label: 'Équateur' },
    { value: 'Égypte', label: 'Égypte' },
    { value: 'Érythrée', label: 'Érythrée' },
    { value: 'Sahara Occidental', label: 'Sahara Occidental' },
    { value: 'Espagne', label: 'Espagne' },
    { value: 'Estonie', label: 'Estonie' },
    { value: 'Éthiopie', label: 'Éthiopie' },
    { value: 'Finlande', label: 'Finlande' },
    { value: 'Fidji', label: 'Fidji' },
    { value: 'Îles Malouines', label: 'Îles Malouines' },
    { value: 'France', label: 'France' },
    { value: 'Îles Féroé', label: 'Îles Féroé' },
    { value: 'Micronésie', label: 'Micronésie' },
    { value: 'Gabon', label: 'Gabon' },
    { value: 'Royaume-Uni', label: 'Royaume-Uni' },
    { value: 'Géorgie', label: 'Géorgie' },
    { value: 'Guernesey', label: 'Guernesey' },
    { value: 'Ghana', label: 'Ghana' },
    { value: 'Gibraltar', label: 'Gibraltar' },
    { value: 'Guinée', label: 'Guinée' },
    { value: 'Guadeloupe', label: 'Guadeloupe' },
    { value: 'Gambie', label: 'Gambie' },
    { value: 'Guinée-Bissau', label: 'Guinée-Bissau' },
    { value: 'Guinée équatoriale', label: 'Guinée équatoriale' },
    { value: 'Grèce', label: 'Grèce' },
    { value: 'Grenade', label: 'Grenade' },
    { value: 'Groenland', label: 'Groenland' },
    { value: 'Guatemala', label: 'Guatemala' },
    { value: 'Guyane', label: 'Guyane' },
    { value: 'Guam', label: 'Guam' },
    { value: 'Guyana', label: 'Guyana' },
    { value: 'Hong Kong', label: 'Hong Kong' },
    { value: 'Îles Heard-et-MacDonald', label: 'Îles Heard-et-MacDonald' },
    { value: 'Honduras', label: 'Honduras' },
    { value: 'Croatie', label: 'Croatie' },
    { value: 'Haïti', label: 'Haïti' },
    { value: 'Hongrie', label: 'Hongrie' },
    { value: 'Indonésie', label: 'Indonésie' },
    { value: 'Île de Man', label: 'Île de Man' },
    { value: 'Inde', label: 'Inde' },
    { value: 'Territoire britannique de l\'océan Indien', label: 'Territoire britannique de l\'océan Indien' },
    { value: 'Irlande', label: 'Irlande' },
    { value: 'Iran', label: 'Iran' },
    { value: 'Irak', label: 'Irak' },
    { value: 'Islande', label: 'Islande' },
    { value: 'Israël', label: 'Israël' },
    { value: 'Italie', label: 'Italie' },
    { value: 'Jamaïque', label: 'Jamaïque' },
    { value: 'Jersey', label: 'Jersey' },
    { value: 'Jordanie', label: 'Jordanie' },
    { value: 'Japon', label: 'Japon' },
    { value: 'Kazakhstan', label: 'Kazakhstan' },
    { value: 'Kenya', label: 'Kenya' },
    { value: 'Kirghizistan', label: 'Kirghizistan' },
    { value: 'Cambodge', label: 'Cambodge' },
    { value: 'Kiribati', label: 'Kiribati' },
    { value: 'Saint-Christophe-et-Niévès', label: 'Saint-Christophe-et-Niévès' },
    { value: 'Corée du Sud', label: 'Corée du Sud' },
    { value: 'Kosovo', label: 'Kosovo' },
    { value: 'Koweït', label: 'Koweït' },
    { value: 'Laos', label: 'Laos' },
    { value: 'Liban', label: 'Liban' },
    { value: 'Liberia', label: 'Liberia' },
    { value: 'Libye', label: 'Libye' },
    { value: 'Sainte-Lucie', label: 'Sainte-Lucie' },
    { value: 'Liechtenstein', label: 'Liechtenstein' },
    { value: 'Sri Lanka', label: 'Sri Lanka' },
    { value: 'Lesotho', label: 'Lesotho' },
    { value: 'Lituanie', label: 'Lituanie' },
    { value: 'Luxembourg', label: 'Luxembourg' },
    { value: 'Lettonie', label: 'Lettonie' },
    { value: 'Macao', label: 'Macao' },
    { value: 'Saint-Martin', label: 'Saint-Martin' },
    { value: 'Maroc', label: 'Maroc' },
    { value: 'Monaco', label: 'Monaco' },
    { value: 'Moldavie', label: 'Moldavie' },
    { value: 'Madagascar', label: 'Madagascar' },
    { value: 'Maldives', label: 'Maldives' },
    { value: 'Mexique', label: 'Mexique' },
    { value: 'Îles Marshall', label: 'Îles Marshall' },
    { value: 'Macédoine', label: 'Macédoine' },
    { value: 'Mali', label: 'Mali' },
    { value: 'Malte', label: 'Malte' },
    { value: 'Birmanie', label: 'Birmanie' },
    { value: 'Monténégro', label: 'Monténégro' },
    { value: 'Mongolie', label: 'Mongolie' },
    { value: 'Îles Mariannes du Nord', label: 'Îles Mariannes du Nord' },
    { value: 'Mozambique', label: 'Mozambique' },
    { value: 'Mauritanie', label: 'Mauritanie' },
    { value: 'Montserrat', label: 'Montserrat' },
    { value: 'Martinique', label: 'Martinique' },
    { value: 'Île Maurice', label: 'Île Maurice' },
    { value: 'Malawi', label: 'Malawi' },
    { value: 'Malaisie', label: 'Malaisie' },
    { value: 'Mayotte', label: 'Mayotte' },
    { value: 'Namibie', label: 'Namibie' },
    { value: 'Nouvelle-Calédonie', label: 'Nouvelle-Calédonie' },
    { value: 'Niger', label: 'Niger' },
    { value: 'Île Norfolk', label: 'Île Norfolk' },
    { value: 'Nigéria', label: 'Nigéria' },
    { value: 'Nicaragua', label: 'Nicaragua' },
    { value: 'Niue', label: 'Niue' },
    { value: 'Pays-Bas', label: 'Pays-Bas' },
    { value: 'Norvège', label: 'Norvège' },
    { value: 'Népal', label: 'Népal' },
    { value: 'Nauru', label: 'Nauru' },
    { value: 'Nouvelle-Zélande', label: 'Nouvelle-Zélande' },
    { value: 'Oman', label: 'Oman' },
    { value: 'Pakistan', label: 'Pakistan' },
    { value: 'Panama', label: 'Panama' },
    { value: 'Îles Pitcairn', label: 'Îles Pitcairn' },
    { value: 'Pérou', label: 'Pérou' },
    { value: 'Philippines', label: 'Philippines' },
    { value: 'Palaos (Palau)', label: 'Palaos (Palau)' },
    { value: 'Papouasie-Nouvelle-Guinée', label: 'Papouasie-Nouvelle-Guinée' },
    { value: 'Pologne', label: 'Pologne' },
    { value: 'Porto Rico', label: 'Porto Rico' },
    { value: 'Corée du Nord', label: 'Corée du Nord' },
    { value: 'Portugal', label: 'Portugal' },
    { value: 'Paraguay', label: 'Paraguay' },
    { value: 'Palestine', label: 'Palestine' },
    { value: 'Polynésie française', label: 'Polynésie française' },
    { value: 'Qatar', label: 'Qatar' },
    { value: 'Réunion', label: 'Réunion' },
    { value: 'Roumanie', label: 'Roumanie' },
    { value: 'Russie', label: 'Russie' },
    { value: 'Rwanda', label: 'Rwanda' },
    { value: 'Arabie Saoudite', label: 'Arabie Saoudite' },
    { value: 'Soudan', label: 'Soudan' },
    { value: 'Sénégal', label: 'Sénégal' },
    { value: 'Singapour', label: 'Singapour' },
    { value: 'Géorgie du Sud-et-les Îles Sandwich du Sud', label: 'Géorgie du Sud-et-les Îles Sandwich du Sud' },
    { value: 'Svalbard et Jan Mayen', label: 'Svalbard et Jan Mayen' },
    { value: 'Îles Salomon', label: 'Îles Salomon' },
    { value: 'Sierra Leone', label: 'Sierra Leone' },
    { value: 'Salvador', label: 'Salvador' },
    { value: 'Saint-Marin', label: 'Saint-Marin' },
    { value: 'Somalie', label: 'Somalie' },
    { value: 'Saint-Pierre-et-Miquelon', label: 'Saint-Pierre-et-Miquelon' },
    { value: 'Serbie', label: 'Serbie' },
    { value: 'Soudan du Sud', label: 'Soudan du Sud' },
    { value: 'São Tomé et Príncipe', label: 'São Tomé et Príncipe' },
    { value: 'Surinam', label: 'Surinam' },
    { value: 'Slovaquie', label: 'Slovaquie' },
    { value: 'Slovénie', label: 'Slovénie' },
    { value: 'Suède', label: 'Suède' },
    { value: 'Swaziland', label: 'Swaziland' },
    { value: 'Saint-Martin', label: 'Saint-Martin' },
    { value: 'Seychelles', label: 'Seychelles' },
    { value: 'Syrie', label: 'Syrie' },
    { value: 'Îles Turques-et-Caïques', label: 'Îles Turques-et-Caïques' },
    { value: 'Tchad', label: 'Tchad' },
    { value: 'Togo', label: 'Togo' },
    { value: 'Thaïlande', label: 'Thaïlande' },
    { value: 'Tadjikistan', label: 'Tadjikistan' },
    { value: 'Tokelau', label: 'Tokelau' },
    { value: 'Turkménistan', label: 'Turkménistan' },
    { value: 'Timor oriental', label: 'Timor oriental' },
    { value: 'Tonga', label: 'Tonga' },
    { value: 'Trinité-et-Tobago', label: 'Trinité-et-Tobago' },
    { value: 'Tunisie', label: 'Tunisie' },
    { value: 'Turquie', label: 'Turquie' },
    { value: 'Tuvalu', label: 'Tuvalu' },
    { value: 'Taïwan', label: 'Taïwan' },
    { value: 'Tanzanie', label: 'Tanzanie' },
    { value: 'Ouganda', label: 'Ouganda' },
    { value: 'Ukraine', label: 'Ukraine' },
    { value: 'Îles mineures éloignées des États-Unis', label: 'Îles mineures éloignées des États-Unis' },
    { value: 'Uruguay', label: 'Uruguay' },
    { value: 'États-Unis', label: 'États-Unis' },
    { value: 'Ouzbékistan', label: 'Ouzbékistan' },
    { value: 'Cité du Vatican', label: 'Cité du Vatican' },
    { value: 'Saint-Vincent-et-les-Grenadines', label: 'Saint-Vincent-et-les-Grenadines' },
    { value: 'Venezuela', label: 'Venezuela' },
    { value: 'Îles Vierges britanniques', label: 'Îles Vierges britanniques' },
    { value: 'Îles Vierges des États-Unis', label: 'Îles Vierges des États-Unis' },
    { value: 'Viêt Nam', label: 'Viêt Nam' },
    { value: 'Vanuatu', label: 'Vanuatu' },
    { value: 'Wallis-et-Futuna', label: 'Wallis-et-Futuna' },
    { value: 'Samoa', label: 'Samoa' },
    { value: 'Yémen', label: 'Yémen' },
    { value: 'Afrique du Sud', label: 'Afrique du Sud' },
    { value: 'Zambie', label: 'Zambie' },
    { value: 'Zimbabwe', label: 'Zimbabwe' }
  ],

  paysEnglish: [
    { label: "Afghanistan" , value: "Afghanistan" },
    { label: "Albania" , value: "Albania" },
    { label: "Algeria" , value: "Algeria" },
    { label: "American Samoa" , value: "American Samoa" },
    { label: "Andorra" , value: "Andorra" },
    { label: "Angola" , value: "Angola" },
    { label: "Anguilla" , value: "Anguilla" },
    { label: "Antarctica" , value: "Antarctica" },
    { label: "Antigua and Barbuda" , value: "Antigua and Barbuda" },
    { label: "Argentina" , value: "Argentina" },
    { label: "Armenia" , value: "Armenia" },
    { label: "Aruba" , value: "Aruba" },
    { label: "Australia" , value: "Australia" },
    { label: "Austria" , value: "Austria" },
    { label: "Azerbaijan" , value: "Azerbaijan" },
    { label: "Bahamas" , value: "Bahamas" },
    { label: "Bahrain" , value: "Bahrain" },
    { label: "Bangladesh" , value: "Bangladesh" },
    { label: "Barbados" , value: "Barbados" },
    { label: "Belarus" , value: "Belarus" },
    { label: "Belgium" , value: "Belgium" },
    { label: "Belize" , value: "Belize" },
    { label: "Benin" , value: "Benin" },
    { label: "Bermuda" , value: "Bermuda" },
    { label: "Bhutan" , value: "Bhutan" },
    { label: "Bolivia" , value: "Bolivia" },
    { label: "Bosnia and Herzegovina" , value: "Bosnia and Herzegovina" },
    { label: "Botswana" , value: "Botswana" },
    { label: "Bouvet Island" , value: "Bouvet Island" },
    { label: "Brazil" , value: "Brazil" },
    { label: "British Indian Ocean Territory" , value: "British Indian Ocean Territory" },
    { label: "Brunei" , value: "Brunei" },
    { label: "Bulgaria" , value: "Bulgaria" },
    { label: "Burkina Faso" , value: "Burkina Faso" },
    { label: "Burundi" , value: "Burundi" },
    { label: "Cambodia" , value: "Cambodia" },
    { label: "Cameroon" , value: "Cameroon" },
    { label: "Canada" , value: "Canada" },
    { label: "Cape Verde" , value: "Cape Verde" },
    { label: "Cayman Islands" , value: "Cayman Islands" },
    { label: "Central African Republic" , value: "Central African Republic" },
    { label: "Chad" , value: "Chad" },
    { label: "Chile" , value: "Chile" },
    { label: "China" , value: "China" },
    { label: "Christmas Island" , value: "Christmas Island" },
    { label: "Cocos (Keeling) Islands" , value: "Cocos (Keeling) Islands" },
    { label: "Colombia" , value: "Colombia" },
    { label: "Comoros" , value: "Comoros" },
    { label: "Congo" , value: "Congo" },
    { label: "Cook Islands" , value: "Cook Islands" },
    { label: "Costa Rica" , value: "Costa Rica" },
    { label: "Côte d'Ivoire" , value: "Côte d'Ivoire" },
    { label: "Croatia (Hrvatska)" , value: "Croatia (Hrvatska)" },
    { label: "Cuba" , value: "Cuba" },
    { label: "Cyprus" , value: "Cyprus" },
    { label: "Czech Republic" , value: "Czech Republic" },
    { label: "Congo (DRC)" , value: "Congo (DRC)" },
    { label: "Denmark" , value: "Denmark" },
    { label: "Djibouti" , value: "Djibouti" },
    { label: "Dominica" , value: "Dominica" },
    { label: "Dominican Republic" , value: "Dominican Republic" },
    { label: "East Timor" , value: "East Timor" },
    { label: "Ecuador" , value: "Ecuador" },
    { label: "Egypt" , value: "Egypt" },
    { label: "El Salvador" , value: "El Salvador" },
    { label: "Equatorial Guinea" , value: "Equatorial Guinea" },
    { label: "Eritrea" , value: "Eritrea" },
    { label: "Estonia" , value: "Estonia" },
    { label: "Ethiopia" , value: "Ethiopia" },
    { label: "Falkland Islands (Islas Malvinas)" , value: "Falkland Islands (Islas Malvinas)" },
    { label: "Faroe Islands" , value: "Faroe Islands" },
    { label: "Fiji Islands" , value: "Fiji Islands" },
    { label: "Finland" , value: "Finland" },
    { label: "France" , value: "France" },
    { label: "French Guiana" , value: "French Guiana" },
    { label: "French Polynesia" , value: "French Polynesia" },
    { label: "French Southern and Antarctic Lands" , value: "French Southern and Antarctic Lands" },
    { label: "Gabon" , value: "Gabon" },
    { label: "Gambia" , value: "Gambia" },
    { label: "Georgia" , value: "Georgia" },
    { label: "Germany" , value: "Germany" },
    { label: "Ghana" , value: "Ghana" },
    { label: "Gibraltar" , value: "Gibraltar" },
    { label: "Greece" , value: "Greece" },
    { label: "Greenland" , value: "Greenland" },
    { label: "Grenada" , value: "Grenada" },
    { label: "Guadeloupe" , value: "Guadeloupe" },
    { label: "Guam" , value: "Guam" },
    { label: "Guatemala" , value: "Guatemala" },
    { label: "Guinea" , value: "Guinea" },
    { label: "Guinea-Bissau" , value: "Guinea-Bissau" },
    { label: "Guyana" , value: "Guyana" },
    { label: "Haiti" , value: "Haiti" },
    { label: "Heard Island and McDonald Islands", value: "Heard Island and McDonald Islands" },
    { label: "Honduras", value: "Honduras" },
    { label: "Hong Kong SAR", value: "Hong Kong SAR" },
    { label: "Hungary", value: "Hungary" },
    { label: "Iceland", value: "Iceland" },
    { label: "India", value: "India" },
    { label: "Indonesia", value: "Indonesia" },
    { label: "Iran", value: "Iran" },
    { label: "Iraq", value: "Iraq" },
    { label: "Ireland", value: "Ireland" },
    { label: "Israel", value: "Israel" },
    { label: "Italy", value: "Italy" },
    { label: "Jamaica", value: "Jamaica" },
    { label: "Japan", value: "Japan" },
    { label: "Jordan", value: "Jordan" },
    { label: "Kazakhstan", value: "Kazakhstan" },
    { label: "Kenya", value: "Kenya" },
    { label: "Kiribati", value: "Kiribati" },
    { label: "Korea", value: "Korea" },
    { label: "Kuwait", value: "Kuwait" },
    { label: "Kyrgyzstan", value: "Kyrgyzstan" },
    { label: "Laos", value: "Laos" },
    { label: "Latvia", value: "Latvia" },
    { label: "Lebanon", value: "Lebanon" },
    { label: "Lesotho", value: "Lesotho" },
    { label: "Liberia", value: "Liberia" },
    { label: "Libya", value: "Libya" },
    { label: "Liechtenstein", value: "Liechtenstein" },
    { label: "Lithuania", value: "Lithuania" },
    { label: "Luxembourg", value: "Luxembourg" },
    { label: "Macao SAR", value: "Macao SAR" },
    { label: "Macedonia, Former Yugoslav Republic of", value: "Macedonia, Former Yugoslav Republic of" },
    { label: "Madagascar", value: "Madagascar" },
    { label: "Malawi", value: "Malawi" },
    { label: "Malaysia", value: "Malaysia" },
    { label: "Maldives", value: "Maldives" },
    { label: "Mali", value: "Mali" },
    { label: "Malta", value: "Malta" },
    { label: "Marshall Islands", value: "Marshall Islands" },
    { label: "Martinique", value: "Martinique" },
    { label: "Mauritania", value: "Mauritania" },
    { label: "Mauritius", value: "Mauritius" },
    { label: "Mayotte", value: "Mayotte" },
    { label: "Mexico", value: "Mexico" },
    { label: "Micronesia", value: "Micronesia" },
    { label: "Moldova", value: "Moldova" },
    { label: "Monaco", value: "Monaco" },
    { label: "Mongolia", value: "Mongolia" },
    { label: "Montserrat", value: "Montserrat" },
    { label: "Morocco", value: "Morocco" },
    { label: "Mozambique", value: "Mozambique" },
    { label: "Myanmar", value: "Myanmar" },
    { label: "Namibia", value: "Namibia" },
    { label: "Nauru", value: "Nauru" },
    { label: "Nepal", value: "Nepal" },
    { label: "Netherlands", value: "Netherlands" },
    { label: "Netherlands Antilles", value: "Netherlands Antilles" },
    { label: "New Caledonia", value: "New Caledonia" },
    { label: "New Zealand", value: "New Zealand" },
    { label: "Nicaragua", value: "Nicaragua" },
    { label: "Niger", value: "Niger" },
    { label: "Nigeria", value: "Nigeria" },
    { label: "Niue", value: "Niue" },
    { label: "Norfolk Island", value: "Norfolk Island" },
    { label: "North Korea", value: "North Korea" },
    { label: "Northern Mariana Islands", value: "Northern Mariana Islands" },
    { label: "Norway", value: "Norway" },
    { label: "Oman", value: "Oman" },
    { label: "Pakistan", value: "Pakistan" },
    { label: "Palau", value: "Palau" },
    { label: "Panama", value: "Panama" },
    { label: "Papua New Guinea", value: "Papua New Guinea" },
    { label: "Paraguay", value: "Paraguay" },
    { label: "Peru", value: "Peru" },
    { label: "Philippines", value: "Philippines" },
    { label: "Pitcairn Islands", value: "Pitcairn Islands" },
    { label: "Poland", value: "Poland" },
    { label: "Portugal", value: "Portugal" },
    { label: "Puerto Rico", value: "Puerto Rico" },
    { label: "Qatar", value: "Qatar" },
    { label: "Reunion", value: "Reunion" },
    { label: "Romania", value: "Romania" },
    { label: "Russia", value: "Russia" },
    { label: "Rwanda", value: "Rwanda" },
    { label: "Samoa", value: "Samoa" },
    { label: "San Marino", value: "San Marino" },
    { label: "São Tomé and Príncipe", value: "São Tomé and Príncipe" },
    { label: "Saudi Arabia", value: "Saudi Arabia" },
    { label: "Senegal", value: "Senegal" },
    { label: "Serbia and Montenegro", value: "Serbia and Montenegro" },
    { label: "Seychelles", value: "Seychelles" },
    { label: "Sierra Leone", value: "Sierra Leone" },
    { label: "Singapore", value: "Singapore" },
    { label: "Slovakia", value: "Slovakia" },
    { label: "Slovenia", value: "Slovenia" },
    { label: "Solomon Islands", value: "Solomon Islands" },
    { label: "Somalia", value: "Somalia" },
    { label: "South Africa", value: "South Africa" },
    { label: "South Georgia and the South Sandwich Islands", value: "South Georgia and the South Sandwich Islands" },
    { label: "Spain", value: "Spain" },
    { label: "Sri Lanka", value: "Sri Lanka" },
    { label: "St. Helena", value: "St. Helena" },
    { label: "St. Kitts and Nevis", value: "St. Kitts and Nevis" },
    { label: "St. Lucia", value: "St. Lucia" },
    { label: "St. Pierre and Miquelon", value: "St. Pierre and Miquelon" },
    { label: "St. Vincent and the Grenadines", value: "St. Vincent and the Grenadines" },
    { label: "Sudan", value: "Sudan" },
    { label: "Suriname", value: "Suriname" },
    { label: "Svalbard and Jan Mayen", value: "Svalbard and Jan Mayen" },
    { label: "Swaziland", value: "Swaziland" },
    { label: "Sweden", value: "Sweden" },
    { label: "Switzerland", value: "Switzerland" },
    { label: "Syria", value: "Syria" },
    { label: "Taiwan", value: "Taiwan" },
    { label: "Tajikistan", value: "Tajikistan" },
    { label: "Tanzania", value: "Tanzania" },
    { label: "Thailand", value: "Thailand" },
    { label: "Togo", value: "Togo" },
    { label: "Tokelau", value: "Tokelau" },
    { label: "Tonga", value: "Tonga" },
    { label: "Trinidad and Tobago", value: "Trinidad and Tobago" },
    { label: "Tunisia", value: "Tunisia" },
    { label: "Turkey", value: "Turkey" },
    { label: "Turkmenistan", value: "Turkmenistan" },
    { label: "Turks and Caicos Islands", value: "Turks and Caicos Islands" },
    { label: "Tuvalu", value: "Tuvalu" },
    { label: "Uganda", value: "Uganda" },
    { label: "Ukraine", value: "Ukraine" },
    { label: "United Arab Emirates", value: "United Arab Emirates" },
    { label: "United Kingdom", value: "United Kingdom" },
    { label: "United States", value: "United States" },
    { label: "Uruguay", value: "Uruguay" },
    { label: "Uzbekistan", value: "Uzbekistan" },
    { label: "Vanuatu", value: "Vanuatu" },
    { label: "Vatican City", value: "Vatican City" },
    { label: "Venezuela", value: "Venezuela" },
    { label: "Viet Nam", value: "Viet Nam" },
    { label: "Virgin Islands (British)", value: "Virgin Islands (British)" },
    { label: "Virgin Islands", value: "Virgin Islands" },
    { label: "Wallis and Futuna", value: "Wallis and Futuna" },
    { label: "Yemen", value: "Yemen" },
    { label: "Zambia", value: "Zambia" },
    { label: "Zimbabwe", value: "Zimbabwe" },
  ],

  formations: [
    { value: "BTS MCO" },
    { value: "BTS NDR" },
    { value: "RNCP MUM" },
    { value: "RNCP NTC" },
    { value: "RNCP MERCD" },
    { value: "RNCP CMD" },
    { value: "RNCP MCI" },
    { value: "RNCP MCI CI" },
    { value: "RNCP MCI IA" },
    { value: "BTS SIO" },
    { value: "BTS WEB" },
    { value: "RNCP Réseaux" },
    { value: "RNCP Développeur" },
    { value: "RNCP AIS" },
    { value: "MPI Big Data" },
    { value: "MPI CyberSecurité" },
    { value: "RNCP ARH" },
    { value: "BTS Assurance" },
    { value: "BTS Banque" },
    { value: "BTS CG" },
    { value: "RNCP GCF" },
    { value: "BTS PME" },
    { value: "BTS Notariat" },
    { value: "DCG" },
    { value: "DCGS" },
    { value: "RNCP MRH" },
    { value: "RNCP BIM" },
    { value: "BTS MEC" },
    { value: "Bachelor BIM" },
    { value: "BTS Hôtellerie-Restauration" },
    { value: "BTS SPSSS" },
    { value: "RNCP RET" },
  ],

  entreprisesList: [
    { value: "Elitelabs" },
    { value: "ESTYA" },
    { value: "ADG" },
    { value: "Autre" }
  ],

  programme: [
    { value: "Programme Français" },
    { value: "Programme Anglais" },
  ],

  niveau_academic: [
    { id: 1, value: 'Pré-bac', label: 'Pré-bac' },
    { id: 2, value: 'Bac+2', label: 'Bac+2' },
    { id: 3, value: 'Bac+3', label: 'Bac+3' },
    { id: 4, value: 'Bac+4', label: 'Bac+4' },
    { id: 5, value: 'Bac+5', label: 'Bac+5' },
  ],

  statut_actuel: [
    { id: 1, value: 'Etudiant', label: 'Etudiant' },
    { id: 2, value: 'Salarié', label: 'Salarié' },
    { id: 3, value: 'Au chômage', label: 'Au chômage' },
    { id: 4, value: 'Autre', label: 'Autre' },
  ],

  civilite: [
    { id: 1, value: 'Monsieur', label: 'Mr' },
    { id: 2, value: 'Madame', label: 'Mme' },
    { id: 3, value: 'Autre', label: 'Autre' },
  ],
  civiliteEN: [
    { id: 1, value: 'Mr', label: 'Mr' },
    { id: 2, value: 'Ms', label: 'Ms' },
    { id: 3, value: 'Other', label: 'Other' },
  ],

  profil: [
    { value: 'Salarié', label: 'Salarié' },
    { value: 'Apprenti', label: 'Apprenti' },
    { value: 'Demandeur d\'emploi', label: 'Demandeur d\'emploi'},
    { value: 'Particulier', label: 'Particulier'},
    { value: 'Contrat de professionnalisation', label: 'Contrat de professionnalisation' },
    { value: 'Autre', label: 'Autre' },
  ],

  statut: [
    { value: 'En cours de traitement', label: 'En cours de traitement' },
    { value: 'En attente d\'une réponse', label: 'En attente d\'une réponse' },
    { value: 'Traité', label: 'Traité' },
  ],

  sujetTicketing: [
    { value: "Attestation d'emploi et Certificat de travail", label: "Attestation d'emploi et Certificat de travail" },
    { value: "Déclarer un arrêt de travail", label: 'Déclarer un arrêt de travail' },
    { value: "Renouvellement de contrat", label: "Renouvellement de contrat" },
    { value: "Demander ses BDS", label: "Demander ses BDS" },
    { value: "Démission", label: "Démission" },
    { value: "Domiciliation de salaire", label: "Domiciliation de salaire" },
    { value: "Attestation de salaire", label: "Attestation de salaire" },
    { value: "Avenant de contrat", label: "Avenant de contrat" },
    { value: "Ticket resto", label: "Ticket resto" },
    { value: "Avenant de contrat", label: "Avenant de contrat" },
    { value: "Prévoyance et mutuelle", label: "Prévoyance et mutuelle" },

  ],

  dicNationaliteCode: [
    { 'Aruba': 'ABW' }, // TODO
    { 'Afghane': 'AFG' },
    { 'Angolaise': 'AGO' },
    { 'Anguilla': 'AIA' }, // TODO
    { 'Åland Islands': 'ALA' }, // TODO
    { 'Albanaise': 'ALB' },
    { 'Andorra': 'AND' }, // TODO
    { 'United Arab Emirates': 'ARE' }, // TODO
    { 'Argentine': 'ARG' },
    { 'Armenia': 'ARM' }, // TODO
    { 'American Samoa': 'ASM' }, // TODO
    { 'Antarctica': 'ATA' }, // TODO
    { 'French Southern Territories': 'ATF' }, // TODO
    { 'Antiguaise et barbudienne': 'ATG' },
    { 'Australienne': 'AUS' },
    { 'Autrichienne': 'AUT' },
    { 'Azerbaïdjanaise': 'AZE' },
    { 'Burundaise': 'BDI' },
    { 'Belge': 'BEL' },
    { 'Beninoise': 'BEN' },
    { 'Bonaire, Sint Eustatius and Saba': 'BES' }, //TODO
    { 'Burkinabe': 'BFA' },
    { 'Bangladaise': 'BGD' },
    { 'Bulgare': 'BGR' },
    { 'Bahreinienne': 'BHR' },
    { 'Bahamienne': 'BHS' },
    { 'Bosnienne': 'BIH' },
    { 'Saint BarthÃ©lemy': 'BLM' }, //TODO
    { 'Bielorusse': 'BLR' },
    { 'Belizienne': 'BLZ' },
    { 'Bermuda': 'BMU' },//TODO
    { 'Bolivienne': 'BOL' },
    { 'Brazil': 'BRA' },//TODO
    { 'Barbadienne': 'BRB' },
    { 'Brunei Darussalam': 'BRN' },//TODO
    { 'Bhoutanaise': 'BTN' },
    { 'Bouvet Island': 'BVT' },//TODO
    { 'Botswanaise': 'BWA' },
    { 'Centrafricaine': 'CAF' },
    { 'Canadienne': 'CAN' },
    { 'Cocos (Keeling) Islands': 'CCK' },//TODO
    { 'Suisse': 'CHE' },
    { 'Chilienne': 'CHL' },
    { 'Chinoise': 'CHN' },
    { "Ivoirienne": 'CIV' },
    { 'Camerounaise': 'CMR' },
    { 'Congolaise': 'COD' },
    { 'Congolais': 'COG' },
    { 'Cook Islands': 'COK' },//TODO
    { 'Colombienne': 'COL' },
    { 'Comorienne': 'COM' },
    { 'Cap-verdienn': 'CPV' },
    { 'Costaricaine': 'CRI' },
    { 'Cubaine': 'CUB' },
    { 'Curaçao': 'CUW' },//TODO
    { 'Christmas Island': 'CXR' },//TODO
    { 'Cayman Islands': 'CYM' },//TODO
    { 'Cyprus': 'CYP' },//TODO Chypriote
    { 'Czech Republic': 'CZE' }, //TODO Croate
    { 'Allemande': 'DEU' },
    { 'Djiboutienne': 'DJI' },
    { 'Dominiquaise': 'DMA' },
    { 'Danoise': 'DNK' }, { 'Dominicaine': 'DOM' }, { 'Algerienne': 'DZA' },
    { 'Equatorienne': 'ECU' }, { 'Egyptienne': 'EGY' }, { 'Erythreenne': 'ERI' },
    { 'Western Sahara': 'ESH' },//TODO 
    { 'Espagnole': 'ESP' },
    { 'Estonienne': 'EST' }, { 'Ethiopienne': 'ETH' }, { 'Finlandaise': 'FIN' },
    { 'Fidjienne': 'FJI' },
    { 'Falkland Islands (Malvinas)': 'FLK' },//TODO
    { 'Française': 'FRA' },
    { 'Faroe Islands': 'FRO' }, //TODO
    { 'Micronesia, Federated States of': 'FSM' },//TODO
    { 'Gambienne': 'GAB' },
    { 'Britannique': 'GBR' },
    { 'Georgienne': 'GEO' },
    { 'Guernsey': 'GGY' }, //TODO
    { 'Ghaneenne': 'GHA' },
    { 'Gibraltar': 'GIB' },//TODO
    { 'Guineenne': 'GIN' },
    { 'Guadeloupe': 'GLP' },//TODO
    { 'Gambia': 'GMB' },//TODO
    { 'Guinea-Bissau': 'GNB' },//TODO
    { 'Equatorial Guinea': 'GNQ' },//TODO
    { 'Grecque': 'GRC' }, { 'Grenadienne': 'GRD' },
    { 'Greenland': 'GRL' },//TODO
    { 'Guatemalteque': 'GTM' },
    { 'French Guiana': 'GUF' },//TODO
    { 'Guam': 'GUM' },//TODO
    { 'Guyanienne': 'GUY' },
    { 'Hong Kong': 'HKG' },//TODO
    { 'Heard Island and McDonald Islands': 'HMD' },//TODO
    { 'Hondurienne': 'HND' },
    { 'Croate': 'HRV' },
    { 'Haïtienne': 'HTI' },
    { 'Hongroise': 'HUN' },
    { 'Indonesienne': 'IDN' },
    { 'Isle of Man': 'IMN' },//TODO
    { 'Indienne': 'IND' },
    { 'British Indian Ocean Territory': 'IOT' },//TODO
    { 'Irlandaise': 'IRL' },//TODO
    { 'Iran, Islamic Republic of': 'IRN' }, //TODO
    { 'Irakienne': 'IRQ' },
    { 'Islandaise': 'ISL' },
    { 'Israel': 'ISR' },
    { 'Italienne': 'ITA' },
    { 'Jamaïcaine': 'JAM' },
    { 'Jersey': 'JEY' },//TODO
    { 'Jordanienne': 'JOR' }, { 'Japonaise': 'JPN' },
    { 'Kazakhstanaise': 'KAZ' }, { 'Kenyane': 'KEN' }, { 'Kirghize': 'KGZ' },
    { 'Cambodgienne': 'KHM' },
    { 'Kiribatienne': 'KIR' }, { 'Kittitienne-et-nevicienne': 'KNA' },
    { 'Korea, Republic of': 'KOR' }, //TODO
    { 'Kuwait': 'KWT' },//TODO Koweitienne
    { "Lao People's Democratic Republic": 'LAO' }, //TODO Laotienne
    { 'Libanaise': 'LBN' },
    { 'Liberienne': 'LBR' },
    { 'Libyenne': 'LBY' },
    { 'Saint Lucia': 'LCA' }, //TODO
    { 'Liechtensteinoise': 'LIE' },
    { 'Sri Lanka': 'LKA' },//TODO
    { 'Lesothane': 'LSO' },
    { 'Lituanienne': 'LTU' }, { 'Luxembourgeoise': 'LUX' },
    { 'Latvia': 'LVA' },  //TODO
    { 'Macao': 'MAC' }, //TODO
    { 'Saint-Martinois': 'MAF' },
    { 'Morocco': 'MAR' }, //TODO
    { 'Monaco': 'MCO' }, //TODO
    { 'Moldave': 'MDA' },
    { 'Madagascar': 'MDG' },//TODO
    { 'Maldivienne': 'MDV' },
    { 'Mexicaine': 'MEX' },
    { 'Marshall Islands': 'MHL' },//TODO
    { 'Macedonia, the former Yugoslav Republic of': 'MKD' },//TODO
    { 'Malienne': 'MLI' },
    { 'Maltaise': 'MLT' },
    { 'Myanmar': 'MMR' },//TODO
    { 'Montenegrine': 'MNE' },
    { 'Mongole': 'MNG' },
    { 'Northern Mariana Islands': 'MNP' },//TODO
    { 'Mozambicaine': 'MOZ' }, { 'Mauritanienne': 'MRT' },
    { 'Montserrat': 'MSR' },//TODO
    { 'Martinique': 'MTQ' },//TODO
    { 'Mauritius': 'MUS' },//TODO
    { 'Malawienne': 'MWI' },//TODO
    { 'Malaisienne': 'MYS' },
    { 'Mayotte': 'MYT' },//TODO
    { 'Namibienne': 'NAM' },
    { 'New Caledonia': 'NCL' },//TODO
    { 'Nigerienne': 'NER' },
    { 'Norfolk Island': 'NFK' },//TODO
    { 'Nigeriane': 'NGA' },
    { 'Nicaraguayenne': 'NIC' },
    { 'Niue': 'NIU' },//TODO Niuéenne
    { 'Néerlandaise': 'NLD' },
    { 'Norvegienne': 'NOR' }, { 'Nepalaise': 'NPL' },
    { 'Nauruane': 'NRU' }, { 'Neo-zelandaise': 'NZL' },
    { 'Omanaise': 'OMN' }, { 'Pakistanaise': 'PAK' }, { 'Panameenne': 'PAN' },
    { 'Pitcairn': 'PCN' },//TODO Pitcairnaise
    { 'Peruvienne': 'PER' }, { 'Philippine': 'PHL' },
    { 'Palau': 'PLW' },
    { 'Papouane-neoguineenne': 'PNG' },
    { 'Polonaise': 'POL' }, { 'Portoricaine': 'PRI' },
    { "Korea, Democratic People's Republic of": 'PRK' },
    { 'Portugaise': 'PRT' }, { 'Paraguayenne': 'PRY' }, { 'Palestinienne': 'PSE' },
    { 'French Polynesia': 'PYF' },//TODO Polynésiens
    { 'Qatarienne': 'QAT' },
    { 'Réunion': 'REU' },//TODO Réunionnais
    { 'Roumaine': 'ROU' },
    { 'Russe': 'RUS' }, { 'Rwandaise': 'RWA' },
    { 'Saoudienne': 'SAU' },
    { 'Soudanaise': 'SDN' }, { 'Senegalaise': 'SEN' },
    { 'Singapourienne': 'SGP' },
    { 'South Georgia and the South Sandwich Islands': 'SGS' },//TODO
    { 'Hellenique': 'SHN' },
    { 'Svalbard and Jan Mayen': 'SJM' },//TODO
    { 'Salomonaise': 'SLB' },
    { 'Sierra-leonaise': 'SLE' },
    { 'El Salvador': 'SLV' },
    { 'San Marino': 'SMR' },
    { 'Somalienne': 'SOM' },
    { 'Miquelonais': 'SPM' },
    { 'Serbe': 'SRB' },
    { 'Saoudienne': 'SSD' },
    { 'Santomeenne': 'STP' },
    { 'Surinamaise': 'SUR' },
    { 'Slovaque': 'SVK' }, { 'Slovene': 'SVN' }, { 'Suedoise': 'SWE' },
    { 'Swazie': 'SWZ' },
    { 'Sint Maarten (Dutch part)': 'SXM' },//TODO
    { 'Seychelloise': 'SYC' },
    { 'Syrienne': 'SYR' },
    { 'Turks and Caicos Islands': 'TCA' }, //TODO
    { 'Tchadienne': 'TCD' },
    { 'Togolaise': 'TGO' },
    { 'Thaïlandaise': 'THA' },
    { 'Tadjike': 'TJK' },
    { 'Tokelau': 'TKL' },
    { 'Turkmene': 'TKM' },
    { 'Est-timoraise': 'TLS' },
    { 'Tonguienne': 'TON' }, { 'Trinidadienne': 'TTO' }, { 'Tunisienne': 'TUN' },
    { 'Turque': 'TUR' }, { 'Tuvaluane': 'TUV' }, { 'Taiwanaise': 'TWN' },
    { 'Tanzanienne': 'TZA' },
    { 'Ougandaise': 'UGA' },
    { 'Ukrainienne': 'UKR' },
    { 'United States Minor Outlying Islands': 'UMI' }, //TODO
    { 'Uruguayenne': 'URY' },
    { 'Americaine': 'USA' },
    { 'Ouzbeke': 'UZB' },
    { 'Holy See (Vatican City State)': 'VAT' },//TODO
    { 'Saint-vincentaise-et-grenadine': 'VCT' },
    { 'Venezuelienne': 'VEN' },
    { 'Virgin Islands, British': 'VGB' },//TODO
    { 'Virgin Islands, U.S.': 'VIR' }, //TODO
    { 'Vietnamienne': 'VNM' },
    { 'Vanuatu': 'VUT' },
    { 'Wallis and Futuna': 'WLF' },
    { 'Samoane': 'WSM' },
    { 'Yemenite': 'YEM' },
    { 'Sud-africaine': 'ZAF' },
    { 'Zambienne': 'ZMB' }, { 'Zimbabweenne': 'ZWE' }
  ],


  nationalites: [
    //{ value: "", label: "Choisissez une nationalité" },
    { value: "Afghane", label: 'Afghane' },
    { value: "Albanaise", label: 'Albanaise' },
    { value: "Algerienne", label: 'Algerienne' },
    { value: "Allemande", label: 'Allemande' },
    { value: "Americaine", label: 'Americaine' },
    { value: "Andorrane", label: 'Andorrane' },
    { value: "Angolaise", label: 'Angolaise' },
    { value: "Antiguaise et barbudienne", label: 'Antiguaise et barbudienne' },
    { value: "Argentine", label: 'Argentine' },
    { value: "Australienne", label: 'Australienne' },
    { value: "Autrichienne", label: 'Autrichienne' },
    { value: "Azerbaïdjanaise", label: 'Azerbaïdjanaise' },
    { value: "Bahamienne", label: 'Bahamienne' },
    { value: "Bahreinienne", label: 'Bahreinienne' },
    { value: "Bangladaise", label: 'Bangladaise' },
    { value: "Barbadienne", label: 'Barbadienne' },
    { value: "Belge", label: 'Belge' },
    { value: "Belizienne", label: 'Belizienne' },
    { value: "Beninoise", label: 'Beninoise' },
    { value: "Bhoutanaise", label: 'Bhoutanaise' },
    { value: "Bielorusse", label: 'Bielorusse' },
    { value: "Birmane", label: 'Birmane' },
    { value: "Bissau-Guinéenne", label: 'Bissau-Guinéenne' },
    { value: "Bolivienne", label: 'Bolivienne' },
    { value: "Bosnienne", label: 'Bosnienne' },
    { value: "Botswanaise", label: 'Botswanaise' },
    { value: "Britannique", label: 'Britannique' },
    { value: "Bruneienne", label: 'Bruneienne' },
    { value: "Bulgare", label: 'Bulgare' },
    { value: "Burkinabe", label: 'Burkinabe' },
    { value: "Burundaise", label: 'Burundaise' },
    { value: "Cambodgienne", label: 'Cambodgienne' },
    { value: "Camerounaise", label: 'Camerounaise' },
    { value: "Canadienne", label: 'Canadienne' },
    { value: "Cap-verdienne", label: 'Cap-verdienne' },
    { value: "Centrafricaine", label: 'Centrafricaine' },
    { value: "Chilienne", label: 'Chilienne' },
    { value: "Chinoise", label: 'Chinoise' },
    { value: "Chypriote", label: 'Chypriote' },
    { value: "Colombienne", label: 'Colombienne' },
    { value: "Comorienne", label: 'Comorienne' },
    { value: "Congolaise", label: 'Congolaise' },
    { value: "Costaricaine", label: 'Costaricaine' },
    { value: "Croate", label: 'Croate' },
    { value: "Cubaine", label: 'Cubaine' },
    { value: "Danoise", label: 'Danoise' },
    { value: "Djiboutienne", label: 'Djiboutienne' },
    { value: "Dominicaine", label: 'Dominicaine' },
    { value: "Dominiquaise", label: 'Dominiquaise' },
    { value: "Egyptienne", label: 'Egyptienne' },
    { value: "Emirienne", label: 'Emirienne' },
    { value: "Equato-guineenne", label: 'Equato-guineenne' },
    { value: "Equatorienne", label: 'Equatorienne' },
    { value: "Erythreenne", label: 'Erythreenne' },
    { value: "Espagnole", label: 'Espagnole' },
    { value: "Est-timoraise", label: 'Est-timoraise' },
    { value: "Estonienne", label: 'Estonienne' },
    { value: "Ethiopienne", label: 'Ethiopienne' },
    { value: "Fidjienne", label: 'Fidjienne' },
    { value: "Finlandaise", label: 'Finlandaise' },
    { value: "Française", label: 'Française' },
    { value: "Gabonaise", label: 'Gabonaise' },
    { value: "Gambienne", label: 'Gambienne' },
    { value: "Georgienne", label: 'Georgienne' },
    { value: "Ghaneenne", label: 'Ghaneenne' },
    { value: "Grèce", label: 'Grèce' },
    { value: "Grenadienne", label: 'Grenadienne' },
    { value: "Guatemalteque", label: 'Guatemalteque' },
    { value: "Guineenne", label: 'Guineenne' },
    { value: "Guyanienne", label: 'Guyanienne' },
    { value: "Grecque", label: 'Grecque' },
    { value: "Haïtienne", label: 'Haïtienne' },
    { value: "Hellenique", label: 'Hellenique' },
    { value: "Hondurienne", label: 'Hondurienne' },
    { value: "Hongroise", label: 'Hongroise' },
    { value: "Hongrie", label: 'Hongrie' },
    { value: "Indienne", label: 'Indienne' },
    { value: "Indonesienne", label: 'Indonesienne' },
    { value: "Irakienne", label: 'Irakienne' },
    { value: "Irlandaise", label: 'Irlandaise' },
    { value: "Islandaise", label: 'Islandaise' },
    { value: "Italienne", label: 'Italienne' },
    { value: "Ivoirienne", label: 'Ivoirienne' },
    { value: "Jamaïcaine", label: 'Jamaïcaine' },
    { value: "Japonaise", label: 'Japonaise' },
    { value: "Jordanienne", label: 'Jordanienne' },
    { value: "Kazakhstanaise", label: 'Kazakhstanaise' },
    { value: "Kenyane", label: 'Kenyane' },
    { value: "Kirghize", label: 'Kirghize' },
    { value: "Kiribatienne", label: 'Kiribatienne' },
    { value: "Kittitienne-et-nevicienne", label: 'Kittitienne-et-nevicienne' },
    { value: "Kossovienne", label: 'Kossovienne' },
    { value: "Koweitienne", label: 'Koweitienne' },
    { value: "Laotienne", label: 'Laotienne' },
    { value: "Lesothane", label: 'Lesothane' },
    { value: "Lettone", label: 'Lettone' },
    { value: "Libanaise", label: 'Libanaise' },
    { value: "Liberienne", label: 'Liberienne' },
    { value: "Libyenne", label: 'Libyenne' },
    { value: "Liechtensteinoise", label: 'Liechtensteinoise' },
    { value: "Lituanienne", label: 'Lituanienne' },
    { value: "Luxembourgeoise", label: 'Luxembourgeoise' },
    { value: "Macedonienne", label: 'Macedonienne' },
    { value: "Malaisienne", label: 'Malaisienne' },
    { value: "Malawienne", label: 'Malawienne' },
    { value: "Maldivienne", label: 'Maldivienne' },
    { value: "Malgache", label: 'Malgache' },
    { value: "Malienne", label: 'Malienne' },
    { value: "Maltaise", label: 'Maltaise' },
    { value: "Marocaine", label: 'Marocaine' },
    { value: "Marshallaise", label: 'Marshallaise' },
    { value: "Mauricienne", label: 'Mauricienne' },
    { value: "Mauritanienne", label: 'Mauritanienne' },
    { value: "Mexicaine", label: 'Mexicaine' },
    { value: "Micronesienne", label: 'Micronesienne' },
    { value: "Moldave", label: 'Moldave' },
    { value: "Monegasque", label: 'Monegasque' },
    { value: "Mongole", label: 'Mongole' },
    { value: "Montenegrine", label: 'Montenegrine' },
    { value: "Mozambicaine", label: 'Mozambicaine' },
    { value: "Namibienne", label: 'Namibienne' },
    { value: "Nauruane", label: 'Nauruane' },
    { value: "Néerlandaise", label: 'Neerlandaise' },
    { value: "Neo-zelandaise", label: 'Neo-zelandaise' },
    { value: "Nepalaise", label: 'Nepalaise' },
    { value: "Nicaraguayenne", label: 'Nicaraguayenne' },
    { value: "Nigeriane", label: 'Nigeriane' },
    { value: "Nigerienne", label: 'Nigerienne' },
    { value: "Nord-coréenne", label: 'Nord-coréenne' },
    { value: "Norvegienne", label: 'Norvegienne' },
    { value: "Omanaise", label: 'Omanaise' },
    { value: "Ougandaise", label: 'Ougandaise' },
    { value: "Ouzbeke", label: 'Ouzbeke' },
    { value: "Pakistanaise", label: 'Pakistanaise' },
    { value: "Palau", label: 'Palau' },
    { value: "Palestinienne", label: 'Palestinienne' },
    { value: "Panameenne", label: 'Panameenne' },
    { value: "Papouane-neoguineenne", label: 'Papouane-neoguineenne' },
    { value: "Paraguayenne", label: 'Paraguayenne' },
    { value: "Peruvienne", label: 'Peruvienne' },
    { value: "Philippine", label: 'Philippine' },
    { value: "Polonaise", label: 'Polonaise' },
    { value: "Portoricaine", label: 'Portoricaine' },
    { value: "Portugaise", label: 'Portugaise' },
    { value: "Qatarienne", label: 'Qatarienne' },
    { value: "Roumaine", label: 'Roumaine' },
    { value: "Russe", label: 'Russe' },
    { value: "Rwandaise", label: 'Rwandaise' },
    { value: "Saint-lucienne", label: 'Saint-lucienne' },
    { value: "Saint-marinaise", label: 'Saint-marinaise' },
    { value: "Saint-vincentaise-et-grenadine", label: 'Saint-vincentaise-et-grenadine' },
    { value: "Salomonaise", label: 'Salomonaise' },
    { value: "Salvadorienne", label: 'Salvadorienne' },
    { value: "Samoane", label: 'Samoane' },
    { value: "Santomeenne", label: 'Santomeenne' },
    { value: "Saoudienne", label: 'Saoudienne' },
    { value: "Senegalaise", label: 'Senegalaise' },
    { value: "Serbe", label: 'Serbe' },
    { value: "Seychelloise", label: 'Seychelloise' },
    { value: "Sierra-leonaise", label: 'Sierra-leonaise' },
    { value: "Singapourienne", label: 'Singapourienne' },
    { value: "Slovaque", label: 'Slovaque' },
    { value: "Slovene", label: 'Slovene' },
    { value: "Somalienne", label: 'Somalienne' },
    { value: "Soudanaise", label: 'Soudanaise' },
    { value: "Sri-lankaise", label: 'Sri-lankaise' },
    { value: "Sud-africaine", label: 'Sud-africaine' },
    { value: "Sud-coréenne", label: 'Sud-coréenne' },
    { value: "Suedoise", label: 'Suedoise' },
    { value: "Suisse", label: 'Suisse' },
    { value: "Surinamaise", label: 'Surinamaise' },
    { value: "Swazie", label: 'Swazie' },
    { value: "Syrienne", label: 'Syrienne' },
    { value: "Tadjike", label: 'Tadjike' },
    { value: "Taiwanaise", label: 'Taiwanaise' },
    { value: "Tanzanienne", label: 'Tanzanienne' },
    { value: "Tchadienne", label: 'Tchadienne' },
    { value: "Tcheque", label: 'Tcheque' },
    { value: "Thaïlandaise", label: 'Thaïlandaise' },
    { value: "Togolaise", label: 'Togolaise' },
    { value: "Tonguienne", label: 'Tonguienne' },
    { value: "Trinidadienne", label: 'Trinidadienne' },
    { value: "Tunisienne", label: 'Tunisienne' },
    { value: "Turkmene", label: 'Turkmene' },
    { value: "Turque", label: 'Turque' },
    { value: "Tuvaluane", label: 'Tuvaluane' },
    { value: "Ukrainienne", label: 'Ukrainienne' },
    { value: "Uruguayenne", label: 'Uruguayenne' },
    { value: "Vanuatuane", label: 'Vanuatuane' },
    { value: "Venezuelienne", label: 'Venezuelienne' },
    { value: "Vietnamienne", label: 'Vietnamienne' },
    { value: "Yemenite", label: 'Yemenite' },
    { value: "Zambienne", label: 'Zambienne' },
    { value: "Zimbabweenne", label: 'Zimbabweenne' },

  ],
  nationalities: [
    { value: "Afghan", label: 'Afghan' },
    { value: "Albanian", label: 'Albanian' },
    { value: "Algerian", label: 'Algerian' },
    { value: "German", label: 'German' },
    { value: "American", label: 'American' },
    { value: "Andorran", label: 'Andorran' },
    { value: "Angolan", label: 'Angolan' },
    { value: "Antiguan and Barbudan", label: 'Antiguan and Barbudan' },
    { value: "Argentinian", label: 'Argentinian' },
    { value: "Australian", label: 'Australian' },
    { value: "Austrian", label: 'Austrian' },
    { value: "Azerbaijani", label: 'Azerbaijani' },
    { value: "Bahamian", label: 'Bahamian' },
    { value: "Bahraini", label: 'Bahraini' },
    { value: "Bangladeshi", label: 'Bangladeshi' },
    { value: "Barbadian", label: 'Barbadian' },
    { value: "Belgian", label: 'Belgian' },
    { value: "Belizean", label: 'Belizean' },
    { value: "Beninese", label: 'Beninese' },
    { value: "Bhutanese", label: 'Bhutanese' },
    { value: "Belarusian", label: 'Belarusian' },
    { value: "Burmese", label: 'Burmese' },
    { value: "Bissau-Guinean", label: 'Bissau-Guinean' },
    { value: "Bolivian", label: 'Bolivian' },
    { value: "Bosnian", label: 'Bosnian' },
    { value: "Botswanan", label: 'Botswanan' },
    { value: "British", label: 'British' },
    { value: "Bruneian", label: 'Bruneian' },
    { value: "Bulgarian", label: 'Bulgarian' },
    { value: "Burkinabe", label: 'Burkinabe' },
    { value: "Burundian", label: 'Burundian' },
    { value: "Cambodian", label: 'Cambodian' },
    { value: "Cameroonian", label: 'Cameroonian' },
    { value: "Canadian", label: 'Canadian' },
    { value: "Cape Verdean", label: 'Cape Verdean' },
    { value: "Central African", label: 'Central African' },
    { value: "Chilean", label: 'Chilean' },
    { value: "Chinese", label: 'Chinese' },
    { value: "Cypriot", label: 'Cypriot' },
    { value: "Colombian", label: 'Colombian' },
    { value: "Comorian", label: 'Comorian' },
    { value: "Congolese", label: 'Congolese' },
    { value: "Costa Rican", label: 'Costa Rican' },
    { value: "Croatian", label: 'Croatian' },
    { value: "Cuban", label: 'Cuban' },
    { value: "Danish", label: 'Danish' },
    { value: "Djiboutian", label: 'Djiboutian' },
    { value: "Dominican", label: 'Dominican' },
    { value: "Dominican", label: 'Dominican' },
    { value: "Egyptian", label: 'Egyptian' },
    { value: "Emirati", label: 'Emirati' },
    { value: "Equatorial Guinean", label: 'Equatorial Guinean' },
    { value: "Ecuadorian", label: 'Ecuadorian' },
    { value: "Eritrean", label: 'Eritrean' },
    { value: "Spanish", label: 'Spanish' },
    { value: "East Timorese", label: 'East Timorese' },
    { value: "Estonian", label: 'Estonian' },
    { value: "Ethiopian", label: 'Ethiopian' },
    { value: "Fijian", label: 'Fijian' },
    { value: "Finnish", label: 'Finnish' },
    { value: "French", label: 'French' },
    { value: "Gabonese", label: 'Gabonese' },
    { value: "Gambian", label: 'Gambian' },
    { value: "Georgian", label: 'Georgian' },
    { value: "Ghanaian", label: 'Ghanaian' },
    { value: "Grenadian", label: 'Grenadian' },
    { value: "Guatemalan", label: 'Guatemalan' },
    { value: "Guinean", label: 'Guinean' },
    { value: "Guyanese", label: 'Guyanese' },
    { value: "Greek", label: 'Greek' },
    { value: "Haitian", label: 'Haitian' },
    { value: "Honduran", label: 'Honduran' },
    { value: "Hungarian", label: 'Hungarian' },
    { value: "Indian", label: 'Indian' },
    { value: "Indonesian", label: 'Indonesian' },
    { value: "Iraqi", label: 'Iraqi' },
    { value: "Irish", label: 'Irish' },
    { value: "Icelandic", label: 'Icelandic' },
    { value: "Italian", label: 'Italian' },
    { value: "Ivorian", label: 'Ivorian' },
    { value: "Jamaican", label: 'Jamaican' },
    { value: "Japanese", label: 'Japanese' },
    { value: "Jordanian", label: 'Jordanian' },
    { value: "Kazakhstani", label: 'Kazakhstani' },
    { value: "Kenyan", label: 'Kenyan' },
    { value: "Kyrgyz", label: 'Kyrgyz' },
    { value: "Kiribati", label: 'Kiribati' },
    { value: "Kittitian and Nevisian", label: 'Kittitian and Nevisian' },
    { value: "Kosovar", label: 'Kosovar' },
    { value: "Kuwaiti", label: 'Kuwaiti' },
    { value: "Laotian", label: 'Laotian' },
    { value: "Basotho", label: 'Basotho' },
    { value: "Latvian", label: 'Latvian' },
    { value: "Lebanese", label: 'Lebanese' },
    { value: "Liberian", label: 'Liberian' },
    { value: "Libyan", label: 'Libyan' },
    { value: "Liechtensteiner", label: 'Liechtensteiner' },
    { value: "Lithuanian", label: 'Lithuanian' },
    { value: "Luxembourgish", label: 'Luxembourgish' },
    { value: "Macedonian", label: 'Macedonian' },
    { value: "Malaysian", label: 'Malaysian' },
    { value: "Malawian", label: 'Malawian' },
    { value: "Maldivian", label: 'Maldivian' },
    { value: "Malagasy", label: 'Malagasy' },
    { value: "Malian", label: 'Malian' },
    { value: "Maltese", label: 'Maltese' },
    { value: "Moroccan", label: 'Moroccan' },
    { value: "Marshallese", label: 'Marshallese' },
    { value: "Mauritian", label: 'Mauritian' },
    { value: "Mauritanian", label: 'Mauritanian' },
    { value: "Mexican", label: 'Mexican' },
    { value: "Micronesian", label: 'Micronesian' },
    { value: "Moldovan", label: 'Moldovan' },
    { value: "Monégasque", label: 'Monégasque' },
    { value: "Mongolian", label: 'Mongolian' },
    { value: "Montenegrin", label: 'Montenegrin' },
    { value: "Mozambican", label: 'Mozambican' },
    { value: "Namibian", label: 'Namibian' },
    { value: "Nauruan", label: 'Nauruan' },
    { value: "Dutch", label: 'Dutch' },
    { value: "New Zealander", label: 'New Zealander' },
    { value: "Nepalese", label: 'Nepalese' },
    { value: "Nicaraguan", label: 'Nicaraguan' },
    { value: "Nigerian", label: 'Nigerian' },
    { value: "North Korean", label: 'North Korean' },
    { value: "Norwegian", label: 'Norwegian' },
    { value: "Omani", label: 'Omani' },
    { value: "Ugandan", label: 'Ugandan' },
    { value: "Uzbek", label: 'Uzbek' },
    { value: "Pakistani", label: 'Pakistani' },
    { value: "Palauan", label: 'Palauan' },
    { value: "Palestinian", label: 'Palestinian' },
    { value: "Panamanian", label: 'Panamanian' },
    { value: "Papua New Guinean", label: 'Papua New Guinean' },
    { value: "Paraguayan", label: 'Paraguayan' },
    { value: "Peruvian", label: 'Peruvian' },
    { value: "Filipino", label: 'Filipino' },
    { value: "Polish", label: 'Polish' },
    { value: "Puerto Rican", label: 'Puerto Rican' },
    { value: "Portuguese", label: 'Portuguese' },
    { value: "Qatari", label: 'Qatari' },
    { value: "Romanian", label: 'Romanian' },
    { value: "Russian", label: 'Russian' },
    { value: "Rwandan", label: 'Rwandan' },
    { value: "Saint Lucian", label: 'Saint Lucian' },
    { value: "Saint Marinese", label: 'Saint Marinese' },
    { value: "Saint Vincentian and Grenadian", label: 'Saint Vincentian and Grenadian' },
    { value: "Solomon Islander", label: 'Solomon Islander' },
    { value: "Salvadoran", label: 'Salvadoran' },
    { value: "Samoan", label: 'Samoan' },
    { value: "São Toméan", label: 'São Toméan' },
    { value: "Saudi", label: 'Saudi' },
    { value: "Senegalese", label: 'Senegalese' },
    { value: "Serbian", label: 'Serbian' },
    { value: "Seychellois", label: 'Seychellois' },
    { value: "Sierra Leonean", label: 'Sierra Leonean' },
    { value: "Singaporean", label: 'Singaporean' },
    { value: "Slovak", label: 'Slovak' },
    { value: "Slovenian", label: 'Slovenian' },
    { value: "Somali", label: 'Somali' },
    { value: "Sudanese", label: 'Sudanese' },
    { value: "Sri Lankan", label: 'Sri Lankan' },
    { value: "South African", label: 'South African' },
    { value: "South Korean", label: 'South Korean' },
    { value: "Swedish", label: 'Swedish' },
    { value: "Swiss", label: 'Swiss' },
    { value: "Surinamese", label: 'Surinamese' },
    { value: "Swazi", label: 'Swazi' },
    { value: "Syrian", label: 'Syrian' },
    { value: "Tajik", label: 'Tajik' },
    { value: "Taiwanese", label: 'Taiwanese' },
    { value: "Tanzanian", label: 'Tanzanian' },
    { value: "Chadian", label: 'Chadian' },
    { value: "Czech", label: 'Czech' },
    { value: "Thai", label: 'Thai' },
    { value: "Togolese", label: 'Togolese' },
    { value: "Tongan", label: 'Tongan' },
    { value: "Trinidadian", label: 'Trinidadian' },
    { value: "Tunisian", label: 'Tunisian' },
    { value: "Turkmen", label: 'Turkmen' },
    { value: "Turkish", label: 'Turkish' },
    { value: "Tuvaluan", label: 'Tuvaluan' },
    { value: "Ukrainian", label: 'Ukrainian' },
    { value: "Uruguayan", label: 'Uruguayan' },
    { value: "Vanuatuan", label: 'Vanuatuan' },
    { value: "Venezuelan", label: 'Venezuelan' },
    { value: "Vietnamese", label: 'Vietnamese' },
    { value: "Yemeni", label: 'Yemeni' },
    { value: "Zambian", label: 'Zambian' },
    { value: "Zimbabwean", label: 'Zimbabwean' }
  ],
  nationalites_UE: [
    { value: "Allemande", label: 'Allemande' },
    { value: "Autrichienne", label: 'Autrichienne' },
    { value: "Belge", label: 'Belge' },
    { value: "Danoise", label: 'Danoise' },
    { value: "Espagnole", label: 'Espagnole' },
    { value: "Estonienne", label: 'Estonienne' },
    { value: "Finlandaise", label: 'Finlandaise' },
    { value: "Française", label: 'Française' },
    { value: "Grèce", label: 'Grèce' },
    { value: "Hongrie", label: 'Hongrie' },
    { value: "Islandaise", label: 'Islandaise' },
    { value: "Italienne", label: 'Italienne' },
    { value: "Liechtensteinoise", label: 'Liechtensteinoise' },
    { value: "Lituanienne", label: 'Lituanienne' },
    { value: "Lettone", label: 'Lettone' },
    { value: "Luxembourgeoise", label: 'Luxembourgeoise' },
    { value: "Maltaise", label: 'Maltaise' },
    { value: "Norvegienne", label: 'Norvegienne' },
    { value: "Néerlandaise", label: 'Néerlandaise' },
    { value: "Polonaise", label: 'Polonaise' },
    { value: "Portugaise", label: 'Portugaise' },
    { value: "Slovaque", label: 'Slovaque' },
    { value: "Slovene", label: 'Slovene' },
    { value: "Suedoise", label: 'Suedoise' },
    { value: "Suisse", label: 'Suisse' },
    { value: "Tcheque", label: 'Tcheque' },
  ],

  nationalitesEDU: [
    { value: "Afghane", label: 'Afghane' },
    { value: "Albanaise", label: 'Albanaise' },
    { value: "Algerienne", label: 'Algerienne' },
    { value: "Americaine", label: 'Americaine' },
    { value: "Andorrane", label: 'Andorrane' },
    { value: "Angolaise", label: 'Angolaise' },
    { value: "Antiguaise et barbudienne", label: 'Antiguaise et barbudienne' },
    { value: "Argentine", label: 'Argentine' },
    { value: "Australienne", label: 'Australienne' },
    { value: "Azerbaïdjanaise", label: 'Azerbaïdjanaise' },
    { value: "Bahamienne", label: 'Bahamienne' },
    { value: "Bahreinienne", label: 'Bahreinienne' },
    { value: "Bangladaise", label: 'Bangladaise' },
    { value: "Barbadienne", label: 'Barbadienne' },
    { value: "Belizienne", label: 'Belizienne' },
    { value: "Beninoise", label: 'Beninoise' },
    { value: "Bhoutanaise", label: 'Bhoutanaise' },
    { value: "Bielorusse", label: 'Bielorusse' },
    { value: "Birmane", label: 'Birmane' },
    { value: "Bissau-Guinéenne", label: 'Bissau-Guinéenne' },
    { value: "Bolivienne", label: 'Bolivienne' },
    { value: "Bosnienne", label: 'Bosnienne' },
    { value: "Botswanaise", label: 'Botswanaise' },
    { value: "Britannique", label: 'Britannique' },
    { value: "Bruneienne", label: 'Bruneienne' },
    { value: "Bulgare", label: 'Bulgare' },
    { value: "Burkinabe", label: 'Burkinabe' },
    { value: "Burundaise", label: 'Burundaise' },
    { value: "Cambodgienne", label: 'Cambodgienne' },
    { value: "Camerounaise", label: 'Camerounaise' },
    { value: "Canadienne", label: 'Canadienne' },
    { value: "Cap-verdienne", label: 'Cap-verdienne' },
    { value: "Centrafricaine", label: 'Centrafricaine' },
    { value: "Chilienne", label: 'Chilienne' },
    { value: "Chinoise", label: 'Chinoise' },
    { value: "Chypriote", label: 'Chypriote' },
    { value: "Colombienne", label: 'Colombienne' },
    { value: "Comorienne", label: 'Comorienne' },
    { value: "Congolaise", label: 'Congolaise' },
    { value: "Costaricaine", label: 'Costaricaine' },
    { value: "Croate", label: 'Croate' },
    { value: "Cubaine", label: 'Cubaine' },
    { value: "Djiboutienne", label: 'Djiboutienne' },
    { value: "Dominicaine", label: 'Dominicaine' },
    { value: "Dominiquaise", label: 'Dominiquaise' },
    { value: "Egyptienne", label: 'Egyptienne' },
    { value: "Emirienne", label: 'Emirienne' },
    { value: "Equato-guineenne", label: 'Equato-guineenne' },
    { value: "Equatorienne", label: 'Equatorienne' },
    { value: "Erythreenne", label: 'Erythreenne' },
    { value: "Est-timoraise", label: 'Est-timoraise' },
    { value: "Ethiopienne", label: 'Ethiopienne' },
    { value: "Fidjienne", label: 'Fidjienne' },
    { value: "Gabonaise", label: 'Gabonaise' },
    { value: "Gambienne", label: 'Gambienne' },
    { value: "Georgienne", label: 'Georgienne' },
    { value: "Ghaneenne", label: 'Ghaneenne' },
    { value: "Grenadienne", label: 'Grenadienne' },
    { value: "Guatemalteque", label: 'Guatemalteque' },
    { value: "Guineenne", label: 'Guineenne' },
    { value: "Guyanienne", label: 'Guyanienne' },
    { value: "Grecque", label: 'Grecque' },
    { value: "Haïtienne", label: 'Haïtienne' },
    { value: "Hellenique", label: 'Hellenique' },
    { value: "Hondurienne", label: 'Hondurienne' },
    { value: "Hongroise", label: 'Hongroise' },
    { value: "Indienne", label: 'Indienne' },
    { value: "Indonesienne", label: 'Indonesienne' },
    { value: "Irakienne", label: 'Irakienne' },
    { value: "Irlandaise", label: 'Irlandaise' },
    { value: "Ivoirienne", label: 'Ivoirienne' },
    { value: "Jamaïcaine", label: 'Jamaïcaine' },
    { value: "Japonaise", label: 'Japonaise' },
    { value: "Jordanienne", label: 'Jordanienne' },
    { value: "Kazakhstanaise", label: 'Kazakhstanaise' },
    { value: "Kenyane", label: 'Kenyane' },
    { value: "Kirghize", label: 'Kirghize' },
    { value: "Kiribatienne", label: 'Kiribatienne' },
    { value: "Kittitienne-et-nevicienne", label: 'Kittitienne-et-nevicienne' },
    { value: "Kossovienne", label: 'Kossovienne' },
    { value: "Koweitienne", label: 'Koweitienne' },
    { value: "Laotienne", label: 'Laotienne' },
    { value: "Lesothane", label: 'Lesothane' },
    { value: "Libanaise", label: 'Libanaise' },
    { value: "Liberienne", label: 'Liberienne' },
    { value: "Libyenne", label: 'Libyenne' },
    { value: "Macedonienne", label: 'Macedonienne' },
    { value: "Malaisienne", label: 'Malaisienne' },
    { value: "Malawienne", label: 'Malawienne' },
    { value: "Maldivienne", label: 'Maldivienne' },
    { value: "Malgache", label: 'Malgache' },
    { value: "Malienne", label: 'Malienne' },
    { value: "Marocaine", label: 'Marocaine' },
    { value: "Marshallaise", label: 'Marshallaise' },
    { value: "Mauricienne", label: 'Mauricienne' },
    { value: "Mauritanienne", label: 'Mauritanienne' },
    { value: "Mexicaine", label: 'Mexicaine' },
    { value: "Micronesienne", label: 'Micronesienne' },
    { value: "Moldave", label: 'Moldave' },
    { value: "Monegasque", label: 'Monegasque' },
    { value: "Mongole", label: 'Mongole' },
    { value: "Montenegrine", label: 'Montenegrine' },
    { value: "Mozambicaine", label: 'Mozambicaine' },
    { value: "Namibienne", label: 'Namibienne' },
    { value: "Nauruane", label: 'Nauruane' },
    { value: "Neo-zelandaise", label: 'Neo-zelandaise' },
    { value: "Nepalaise", label: 'Nepalaise' },
    { value: "Nicaraguayenne", label: 'Nicaraguayenne' },
    { value: "Nigeriane", label: 'Nigeriane' },
    { value: "Nigerienne", label: 'Nigerienne' },
    { value: "Nord-coréenne", label: 'Nord-coréenne' },
    { value: "Omanaise", label: 'Omanaise' },
    { value: "Ougandaise", label: 'Ougandaise' },
    { value: "Ouzbeke", label: 'Ouzbeke' },
    { value: "Pakistanaise", label: 'Pakistanaise' },
    { value: "Palau", label: 'Palau' },
    { value: "Palestinienne", label: 'Palestinienne' },
    { value: "Panameenne", label: 'Panameenne' },
    { value: "Papouane-neoguineenne", label: 'Papouane-neoguineenne' },
    { value: "Paraguayenne", label: 'Paraguayenne' },
    { value: "Peruvienne", label: 'Peruvienne' },
    { value: "Philippine", label: 'Philippine' },
    { value: "Portoricaine", label: 'Portoricaine' },
    { value: "Qatarienne", label: 'Qatarienne' },
    { value: "Roumaine", label: 'Roumaine' },
    { value: "Russe", label: 'Russe' },
    { value: "Rwandaise", label: 'Rwandaise' },
    { value: "Saint-lucienne", label: 'Saint-lucienne' },
    { value: "Saint-marinaise", label: 'Saint-marinaise' },
    { value: "Saint-vincentaise-et-grenadine", label: 'Saint-vincentaise-et-grenadine' },
    { value: "Salomonaise", label: 'Salomonaise' },
    { value: "Salvadorienne", label: 'Salvadorienne' },
    { value: "Samoane", label: 'Samoane' },
    { value: "Santomeenne", label: 'Santomeenne' },
    { value: "Saoudienne", label: 'Saoudienne' },
    { value: "Senegalaise", label: 'Senegalaise' },
    { value: "Serbe", label: 'Serbe' },
    { value: "Seychelloise", label: 'Seychelloise' },
    { value: "Sierra-leonaise", label: 'Sierra-leonaise' },
    { value: "Singapourienne", label: 'Singapourienne' },
    { value: "Somalienne", label: 'Somalienne' },
    { value: "Soudanaise", label: 'Soudanaise' },
    { value: "Sri-lankaise", label: 'Sri-lankaise' },
    { value: "Sud-africaine", label: 'Sud-africaine' },
    { value: "Sud-coréenne", label: 'Sud-coréenne' },
    { value: "Surinamaise", label: 'Surinamaise' },
    { value: "Swazie", label: 'Swazie' },
    { value: "Syrienne", label: 'Syrienne' },
    { value: "Tadjike", label: 'Tadjike' },
    { value: "Taiwanaise", label: 'Taiwanaise' },
    { value: "Tanzanienne", label: 'Tanzanienne' },
    { value: "Tchadienne", label: 'Tchadienne' },
    { value: "Thaïlandaise", label: 'Thaïlandaise' },
    { value: "Togolaise", label: 'Togolaise' },
    { value: "Tonguienne", label: 'Tonguienne' },
    { value: "Trinidadienne", label: 'Trinidadienne' },
    { value: "Tunisienne", label: 'Tunisienne' },
    { value: "Turkmene", label: 'Turkmene' },
    { value: "Turque", label: 'Turque' },
    { value: "Tuvaluane", label: 'Tuvaluane' },
    { value: "Ukrainienne", label: 'Ukrainienne' },
    { value: "Uruguayenne", label: 'Uruguayenne' },
    { value: "Vanuatuane", label: 'Vanuatuane' },
    { value: "Venezuelienne", label: 'Venezuelienne' },
    { value: "Vietnamienne", label: 'Vietnamienne' },
    { value: "Yemenite", label: 'Yemenite' },
    { value: "Zambienne", label: 'Zambienne' },
    { value: "Zimbabweenne", label: 'Zimbabweenne' },

  ],
  entreprises: [
    { value: "ESTYA Education", label: 'ESTYA Education' },
    { value: "ESTYA Training", label: 'ESTYA Training' },
    { value: "Académie des gouvernantes", label: 'Académie des gouvernantes' },

  ],
  status: [
    { label: "À traiter", value: 'À traiter' },
    { label: "En cours de traitement", value: 'En cours de traitement' },
    { label: "En attente de retour", value: 'En attente de retour' },
    { label: "Clôturé", value: 'Clôturé' }
  ],

  etat_annee: [
    { label: "Nouvelle", value: 'Nouvelle' },
    { label: "Active", value: 'Active' },
    { label: "Archivée", value: 'Archivée' },
  ],

  programeFrDropdown:
    [
      { value: "BTS MCO - Management Commercial Opérationnel" },
      { value: "BTS NDRC - Négociation et Digitalisation de la Relation Client" },
      { value: "BTS CG - Comptabilité et Gestion" },
      { value: "RNCP CI - Commerce International" },
      { value: "RNCP NTC - Négociateur Technico-Commercial" },
      { value: "RNCP - Chargé de Développement Marketing et Commercial" },
      { value: "RNCP - IA - Ingénieur d'Affaires" },
      { value: "RNCP Management et Commerce International" },
      { value: "BTS Services Informatique aux Organisations - SISR" },
      { value: "BTS Services Informatique aux Organisations - SLAM" },
      { value: "RNCP TSSR - Technicien Supérieur Systèmes et Réseaux" },
      { value: "RNCP DWWM - Développeur Web & Web Mobile" },
      { value: "RNCP AIS - Administrateur d'Infrastructures Sécurisées" },
      { value: "RNCP CDA - Concepteur Développeur d'Applications" },
      { value: "RNCP MPI Big Data - Expert IT – Applications Intelligentes & Big Data" },
      { value: "RNCP MPI CyberSecurité - Expert IT – Cybersécurité et Haute Disponibilité" },
      { value: "BTS Collaborateur Juriste Notarial" },
      { value: "RNCP - Assistant Ressources Humaines" },
      { value: "RNCP- Management des Ressources Humaines" },
      { value: "BTS SPSSS - Services et Prestations des Secteurs Sanitaire et Social" },
      { value: "RNCP - BIM modeleur du Bâtiement" },
      { value: "RNCP - BIM modeleur du Coordinateur BIM du Bâtiment" },
    ],

  programEnDropdown:
    [
      { value: "Level 3 - Foundation Diploma for Higher Education Studies" },
      { value: "Level 4 - Business Management " },
      { value: "Level 4 - Information Technology " },
      { value: "Level 4 - Tourism and Hospitality Management" },
      { value: "Level 4 - Health and Social care Management" },
      { value: "Level 5 - Business Management" },
      { value: "Level 5 - Information Technology" },
      { value: "Level 7 - Project Management" },
      { value: "Level 7 - Tourism and Hospitality Management" },
      { value: "Level 7 - Health and Social care Management", }

    ],
  ADGprogrameFrDropdown:
    [
      { value: "GH - Gouvernant(e) en hôtellerie - Titre RNCP - Niveau 4" },
      { value: "CAP AEPE – CAP Accompagnant Educatif Petite Enfance" },
      { value: "GM - Gouvernant(e) de maison - Diplôme maison" },
      { value: "BTS MCO - Management Commercial Operationnel" },
      { value: "BTS NDRC - Négociation et Digitalisation de la Relation Client" },
      { value: "BTS GPME" },
      { value: "BTS CI - Commerce International" },
      { value: "NTC - Négociateur Technico-Commercial (Titre Professionnel)" },
      { value: "Chargé de gestion commerciale - Spécialité service commercial" },
      { value: "IA - Ingénieur d'Affaires" },
      { value: "Management et Stratégie d’Entreprise " },
      { value: "BTS SIO - Services Informatiques aux Organisations" },
      { value: "TSSR - Technicien Supérieur Systèmes et Réseaux (Titre professionnel)" },
      { value: "DWWM - Développeur Web et Web Mobile (Titre professionnel)" },
      { value: "AIS - Administrateur d’Infrastructures Sécurisées" },
      { value: "CDA - Concepteur Développeur d’Applications" },
      { value: "EXPERT IT - CYBERSÉCURITÉ ET HAUTE DISPONIBILITÉ " },
      { value: "EXPERT IT - APPLICATIONS INTELLIGENTES & BIG DATA " },
      { value: "BTS CJN  - Collaborateur Juriste Notarial" },
      { value: "BTS CG - Comptabilité et Gestion" },
      { value: "ARH : Assistant Ressources Humaines (Titre Professionnel)" },
      { value: "BIM Modeleur du Bâtiment (Titre Professionnel)" },
      { value: "Coordinateur BIM du Bâtiment" },
      { value: "BTS SPSSS - Services et Prestations dans les Secteurs Sanitaire et Social" },
      { value: "Formations continues IPERIA" }

    ],
  formationReinscrit:
    [
      { value: "BTS MCO 1ère année - Management Commercial Opérationnel" },
      { value: "BTS NDRC 1ère année - Négociation et Digitalisation de la Relation Client" },
      { value: "BTS CG 1ère année - Comptabilité et Gestion" },
      { value: "BTS MCO 2ème année - Management Commercial Opérationnel" },
      { value: "BTS NDRC 2ème année - Négociation et Digitalisation de la Relation Client" },
      { value: "BTS CG 2ème année	 - Comptabilité et Gestion" },
      { value: "BTS CI 1ère année - Commerce International" },
      { value: "BTS CI 2ème année - Commerce International" },
      { value: "RNCP NTC 1ère année - Négociateur Technico-Commercial" },
      { value: "RNCP NTC 2ème année - Négociateur Technico-Commercial" },
      { value: "RNCP CDMC - Chargé de Développement Marketing et Commercial" },
      { value: "RNCP - IA 1ère année - Ingénieur d'Affaires" },
      { value: "RNCP - IA 2ème année - Ingénieur d'Affaires" },
      { value: "RNCP MCI - Management et Commerce International" },
      { value: "RNCP MDO - Management Des Organisations" },
      { value: "RNCP MSE" },
      { value: "RNCP MSE - Rentrée décalée" },
      { value: "BTS Services Informatique aux Organisations 1ère année - SISR" },
      { value: "BTS Services Informatique aux Organisations 2ème année - SISR" },
      { value: "BTS Services Informatique aux Organisations 1ère année - SLAM" },
      { value: "BTS Services Informatique aux Organisations 2ème année - SLAM" },
      { value: "RNCP TSSR - Technicien Supérieur Systèmes et Réseaux" },
      { value: "RNCP DWWM - Développeur Web & Web Mobile" },
      { value: "RNCP AIS - Administrateur d'Infrastructures Sécurisées" },
      { value: "RNCP CDA - Concepteur Développeur d'Applications" },
      { value: "RNCP MPI Big Data 1ère année - Expert IT – Applications Intelligentes & Big Data" },
      { value: "RNCP MPI Big Data 2ème année - Expert IT – Applications Intelligentes & Big Data" },
      { value: "RNCP MPI CyberSecurité 1ère année - Expert IT – Cybersécurité et Haute Disponibilité" },
      { value: "RNCP MPI CyberSecurité 2ème année - Expert IT – Cybersécurité et Haute Disponibilité" },
      { value: "BTS Collaborateur Juriste Notarial" },
      { value: "RNCP - Assistant Ressources Humaines" },
      { value: "RNCP - Management des Ressources Humaines - 1ère année" },
      { value: "RNCP - Management des Ressources Humaines - 2ème année" },
      { value: "BTS SPSSS - Services et Prestations des Secteurs Sanitaire et Social" },
      { value: "RNCP - BIM modeleur du Bâtiement" },
      { value: "RNCP - BIM modeleur du Coordinateur BIM du Bâtiment" },

      { value: "Level 3 - Foundation Diploma for Higher Education Studies" },
      { value: "Level 4 - Business Management " },
      { value: "Level 4 - Information Technology " },
      { value: "Level 4 - Tourism and Hospitality Management" },
      { value: "Level 4 - Health and Social care Management" },
      { value: "Level 5 - Business Management" },
      { value: "Level 5 - Information Technology" },
      { value: "Level 7 - Project Management" },
      { value: "Level 7 - Tourism and Hospitality Management" },
      { value: "Level 7 - Health and Social care Management" },
    ],
  ADGReinscrit: [
    { value: "GH - Gouvernant(e) en hôtellerie - Titre RNCP - Niveau 4" },
    { value: "CAP AEPE – CAP Accompagnant Educatif Petite Enfance" },
    { value: "GM - Gouvernant(e) de maison - Diplôme maison" },
    { value: "BTS MCO 1ère année - Management Commercial Operationnel" },
    { value: "BTS MCO 2ème année - Management Commercial Operationnel" },
    { value: "BTS NDRC 1ère année - Négociation et Digitalisation de la Relation Client" },
    { value: "BTS NDRC 2ème année - Négociation et Digitalisation de la Relation Client" },
    { value: "BTS GPME" },
    { value: "BTS CI 1ère année - Commerce International" },
    { value: "BTS CI 2ème année - Commerce International" },
    { value: "BTS NTC 1ère année - Négociateur Technico-Commercial (Titre Professionnel)" },
    { value: "BTS NTC 2ème année - Négociateur Technico-Commercial (Titre Professionnel)" },
    { value: "Chargé de gestion commerciale - Spécialité service commercial" },
    { value: "RNCP IA 1ère année - Ingénieur d'Affaires" },
    { value: "RNCP IA 2ème année - Ingénieur d'Affaires" },
    { value: "Management et Stratégie d’Entreprise " },
    { value: "BTS Services Informatique aux Organisations 1ère année - SISR" },
    { value: "BTS Services Informatique aux Organisations 2ème année - SISR" },
    { value: "BTS Services Informatique aux Organisations 1ère année - SLAM" },
    { value: "BTS Services Informatique aux Organisations 2ème année - SLAM" },
    { value: "TSSR - Technicien Supérieur Systèmes et Réseaux (Titre professionnel)" },
    { value: "DWWM - Développeur Web et Web Mobile (Titre professionnel)" },
    { value: "AIS - Administrateur d’Infrastructures Sécurisées" },
    { value: "CDA - Concepteur Développeur d’Applications" },
    { value: "EXPERT IT - CYBERSÉCURITÉ ET HAUTE DISPONIBILITÉ " },
    { value: "EXPERT IT - APPLICATIONS INTELLIGENTES & BIG DATA " },
    { value: "BTS CJN  - Collaborateur Juriste Notarial" },
    { value: "BTS CG - Comptabilité et Gestion" },
    { value: "ARH : Assistant Ressources Humaines (Titre Professionnel)" },
    { value: "BIM Modeleur du Bâtiment (Titre Professionnel)" },
    { value: "Coordinateur BIM du Bâtiment" },
    { value: "BTS SPSSS - Services et Prestations dans les Secteurs Sanitaire et Social" },
    { value: "Formations continues IPERIA" }
  ],
  motif :[
    {label: 'Refus de visa', value: 'Refus de visa'},
    {label: 'Alternance',value: 'Alternance'},
    {label: 'Dossier rejeté par capmus France',value: 'Dossier rejeté par capmus France'},
    {label: 'Paiement en double',value: 'Paiement en double'},
    {label: 'Autre',value: 'Autre'},

  ],
  paymentType : [
    { label: 'Virement', value: 'Virement' },
    { label: 'Chèque', value: 'Chèque' },
    { label: 'Compensation', value: 'Compensation' },
    { label:'Autre', value: 'Autre'},

  ], 

  availableStatus : [
    {
      label: "Nouvelle",
      value: 'new'
    },
    {
      label: "En cours ",
      value: 'in-progress'
    },
    {
      label: "Refusée",
      value: 'declined'
    },
    {
      label: "Acceptée",
      value: 'accepted'
    },
    {
      label: "Orienté",
      value: 'oriented'
    },
    {
      label: "Remboursé",
      value: 'refunded'
    }
  
  ],
};
/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
