// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  origin: "https://141.94.71.25/soc/",
  key: "6abdfb04243e096a4a51b46c8f3d4b32",
  clientId: "24cf4a22-5a5f-4c56-bab4-29884bc6c06f",
  User: null,
  filterFR: {
    "startsWith": "Commence par",
    "contains": "Contiens",
    "notContains": "Ne contiens pas",
    "endsWith": "Fini par",
    "equals": "Corresponds à",
    "notEquals": "Ne corresponds pas à",
    "noFilter": "Sans Filtre",
    "lt": "Plus petit que",
    "lte": "Plus petit ou égal à",
    "gt": "Plus grand que",
    "gte": "Plus grand ou égal à",
    "is": "est",
    "isNot": "n'est pas",
    "before": "Avant",
    "after": "Après",
    "dateIs": "Date est",
    "dateIsNot": "Date n'est pas",
    "dateBefore": "Date est avant",
    "dateAfter": "Date est après",
    "clear": "Vider",
    "apply": "Filtrer",
    "matchAll": "Match All",
    "matchAny": "Match Any",
    "addRule": "Ajouter un Filtre",
    "removeRule": "Supprimer le Filtre",
    "accept": "Oui",
    "reject": "Non",
    "choose": "Choisir",
    "upload": "Upload",
    "cancel": "Annuler",
    dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
    dayNamesShort: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
    monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
    monthNamesShort: ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Jun', 'Jul', 'Aoû', 'Sep', 'Oct', 'Nov', 'Déc'],
    dateFormat: 'dd-mm-yy',
    "firstDayOfWeek": 0,
    today: 'Aujourdhui',
    weekHeader: 'sem',
    "weak": 'Faible',
    "medium": 'Moyen',
    "strong": 'Fort',
    "passwordPrompt": 'Entrer un mot de passe',
    "emptyMessage": 'Aucun résultat',
    "emptyFilterMessage": 'Aucun résultat'
  },
  fr: {
    firstDayOfWeek: 0,
    dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
    dayNamesShort: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
    monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
    monthNamesShort: ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Jun', 'Jul', 'Aoû', 'Sep', 'Oct', 'Nov', 'Déc'],
    today: 'Aujourdhui',
    clear: 'Clear',
    dateFormat: 'dd-mm-yy',
    weekHeader: 'sem'
  },
  colorPaletteGreen: [
    "#b7de6a",
    "#486b03",
    "#79a324",
    "#cafa6b",
    "#c1db8c",
    "#6e9422",
    "#abb39b",
    "#b6e657",
    "#B2C787",
    "#8c9678",
  ],
  role: [
    { value: 'Agent' },
    { value: 'Responsable' }
  ],

  typeUser: [
    { value: "Initial" },
    { value: "Salarié" },
    { value: "Alternant/Stagiaire" },
  ],

  campus: [
    { value: "Paris" },
    { value: "Montpellier" },
    { value: "Dubai" },
    { value: "Montréal" },
    { value: "Londres" },
    { value: "Tunis" },
    { value: "En Ligne(365)" }
  ],

  isoCodes: [
    { value: "AD", label: "Andorre"},
    { value: "AE", label: "Émirats Arabes Unis"},
    { value: "AF", label: "Afghanistan"},
    { value: "AG", label: "Antigua-Et-Barbuda"},
    { value: "AI", label: "Anguilla"},
    { value: "AL", label: "Albanie"},
    { value: "AM", label: "Arménie"},
    { value: "AO", label: "Angola"},
    { value: "AP", label: "Région Asie/Pacifique"},
    { value: "AQ", label: "Antarctique"},
    { value: "AR", label: "Argentine"},
    { value: "AS", label: "Samoa Américaines"},
    { value: "AT", label: "Autriche"},
    { value: "AU", label: "Australie"},
    { value: "AW", label: "Aruba"},
    { value: "AX", label: "Îles Åland"},
    { value: "AZ", label: "Azerbaïdjan"},
    { value: "BA", label: "Bosnie-Herzégovine"},
    { value: "BB", label: "Barbad"},
    { value: "BD", label: "Bangladesh"},
    { value: "BE", label: "Belgique"},
    { value: "BF", label: "Burkina Faso"},
    { value: "BG", label: "Bulgarie"},
    { value: "BH", label: "Bahreïn"},
    { value: "BI", label: "Burundi"},
    { value: "BJ", label: "Bénin"},
    { value: "BL", label: "Saint-Barthélemy"},
    { value: "BM", label: "Bermudes"},
    { value: "BN", label: "Brunei Darussalam"},
    { value: "BO", label: "État Plurinational De Bolivie"},
    { value: "BQ", label: "Bonaire, Saint-Eustache Et Saba"},
    { value: "BR", label: "Brésil"},
    { value: "BS", label: "Bahamas"},
    { value: "BT", label: "Bhoutan"},
    { value: "BV", label: "Île Bouvet"},
    { value: "BW", label: "Botswana"},
    { value: "BY", label: "Biélorussie"},
    { value: "BZ", label: "Belize"},
    { value: "CA", label: "Canada"},
    { value: "CC", label: "Îles Cocos"},
    { value: "CD", label: "République Démocratique Du Congo"},
    { value: "CF", label: "République Centrafricaine"},
    { value: "CG", label: "Congo"},
    { value: "CH", label: "Suisse"},
    { value: "CI", label: "Côte D'Ivoire"},
    { value: "CK", label: "Îles Cook"},
    { value: "CL", label: "Chili"},
    { value: "CM", label: "Cameroun"},
    { value: "CN", label: "Chine"},
    { value: "CO", label: "Colombie"},
    { value: "CR", label: "Costa Rica"},
    { value: "CU", label: "Cuba"},
    { value: "CV", label: "Cap-Vert"},
    { value: "CW", label: "Curaçao"},
    { value: "CX", label: "Île Christmas"},
    { value: "CY", label: "Chypre"},
    { value: "CZ", label: "République Tchèque"},
    { value: "DE", label: "Allemagne"},
    { value: "DJ", label: "Djibouti"},
    { value: "DK", label: "Denmark"},
    { value: "DM", label: "Dominique"},
    { value: "DO", label: "République Dominicaine"},
    { value: "DZ", label: "Algérie"},
    { value: "EC", label: "Équateur"},
    { value: "EE", label: "Estonie"},
    { value: "EG", label: "Égypte"},
    { value: "EH", label: "Sahara Occidental"},
    { value: "ER", label: "Érythrée"},
    { value: "ES", label: "Espagne"},
    { value: "ET", label: "Éthiopie"},
    { value: "EU", label: "Europe"},
    { value: "FI", label: "Finlande"},
    { value: "FJ", label: "Fidji"},
    { value: "FK", label: "Îles Malouines"},
    { value: "FM", label: "États Fédérés De Micronésie"},
    { value: "FO", label: "Îles Féroé"},
    { value: "FRA", label: "France"},
    { value: "GA", label: "Gabon"},
    { value: "GB", label: "Royaume-Uni"},
    { value: "GD", label: "Grenade"},
    { value: "GE", label: "Géorgie"},
    { value: "GF", label: "Guyane"},
    { value: "GG", label: "Guernesey"},
    { value: "GH", label: "Ghana"},
    { value: "GI", label: "Gibraltar"},
    { value: "GL", label: "Groenland"},
    { value: "GM", label: "Gambie"},
    { value: "GN", label: "Guinée"},
    { value: "GP", label: "Guadeloupe"},
    { value: "GQ", label: "Guinée Équatoriale"},
    { value: "GR", label: "Grèce"},
    { value: "GS", label: "Géorgie Du Sud-Et-Les Îles Sandwich Du Sud"},
    { value: "GT", label: "Guatemala"},
    { value: "GU", label: "Guam"},
    { value: "GW", label: "Guinée-Bissau"},
    { value: "GY", label: "Guyana"},
    { value: "HK", label: "Hong Kong"},
    { value: "HM", label: "Îles Heard-Et-MacDonald"},
    { value: "HN", label: "Honduras"},
    { value: "HR", label: "Croatie"},
    { value: "HT", label: "Haïti"},
    { value: "HU", label: "Hongrie"},
    { value: "ID", label: "Indonésie"},
    { value: "IE", label: "Irlande"},
    { value: "IL", label: "Israël"},
    { value: "IM", label: "Île De Man"},
    { value: "IN", label: "Inde"},
    { value: "IO", label: "Territoire Britannique De L'océan Indien"},
    { value: "IQ", label: "Irak"},
    { value: "IR", label: "République Islamique D'Iran"},
    { value: "IS", label: "Islande"},
    { value: "IT", label: "Italie"},
    { value: "JE", label: "Jersey"},
    { value: "JM", label: "Jamaïque"},
    { value: "JO", label: "Jordanie"},
    { value: "JP", label: "Japon"},
    { value: "KE", label: "Kenya"},
    { value: "KG", label: "Kirghizistan"},
    { value: "KH", label: "Cambodge"},
    { value: "KI", label: "Kiribati"},
    { value: "KM", label: "Comores"},
    { value: "KN", label: "Saint-Christophe-et-Niévès"},
    { value: "KP", label: "République Populaire Démocratique De Corée"},
    { value: "KR", label: "République De Corée"},
    { value: "KW", label: "Koweït"},
    { value: "KY", label: "Îles Caïmans"},
    { value: "KZ", label: "Kazakhstan"},
    { value: "LA", label: "République Démocratique Populaire Lao"},
    { value: "LB", label: "Liban"},
    { value: "LC", label: "Sainte-Lucie"},
    { value: "LI", label: "Liechtenstein"},
    { value: "LK", label: "Sri Lanka"},
    { value: "LR", label: "Liberia"},
    { value: "LS", label: "Lesotho"},
    { value: "LT", label: "Lituanie"},
    { value: "LU", label: "Luxembourg"},
    { value: "LV", label: "Lettonie"},
    { value: "LY", label: "Libye"},
    { value: "MA", label: "Maroc"},
    { value: "MC", label: "Monaco"},
    { value: "MD", label: "République De Moldavie"},
    { value: "ME", label: "Monténégro"},
    { value: "MF", label: "Saint-Martin (Partie Française)"},
    { value: "MG", label: "Madagascar"},
    { value: "MH", label: "Îles Marshall"},
    { value: "MK", label: "Macédoine"},
    { value: "ML", label: "Mali"},
    { value: "MM", label: "Birmanie"},
    { value: "MN", label: "Mongolie"},
    { value: "MO", label: "Macao"},
    { value: "MP", label: "Îles Mariannes Du Nord"},
    { value: "MQ", label: "Martinique"},
    { value: "MR", label: "Mauritanie"},
    { value: "MS", label: "Montserrat"},
    { value: "MT", label: "Malte"},
    { value: "MU", label: "Maurice"},
    { value: "MV", label: "Maldives"},
    { value: "MW", label: "Malawi"},
    { value: "MX", label: "Mexique"},
    { value: "MY", label: "Malaisie"},
    { value: "MZ", label: "Mozambique"},
    { value: "NA", label: "Namibie"},
    { value: "NC", label: "Nouvelle-Calédonie"},
    { value: "NE", label: "Niger"},
    { value: "NF", label: "Île Norfolk"},
    { value: "NG", label: "Nigéria"},
    { value: "NI", label: "Nicaragua"},
    { value: "NL", label: "Pays-Bas"},
    { value: "NO", label: "Norvège"},
    { value: "NP", label: "Népal"},
    { value: "NR", label: "Nauru"},
    { value: "NU", label: "Niue"},
    { value: "NZ", label: "Nouvelle-Zélande"},
    { value: "OM", label: "Oman"},
    { value: "PA", label: "Panama"},
    { value: "PE", label: "Pérou"},
    { value: "PF", label: "Polynésie Française"},
    { value: "PG", label: "Papouasie-Nouvelle-Guinée"},
    { value: "PH", label: "Philippines"},
    { value: "PK", label: "Pakistan"},
    { value: "PL", label: "Pologne"},
    { value: "PM", label: "Saint-Pierre-Et-Miquelon"},
    { value: "PN", label: "Pitcairn"},
    { value: "PR", label: "Porto Rico"},
    { value: "PS", label: "Territoires Palestiniens Occupés"},
    { value: "PT", label: "Portugal"},
    { value: "PW", label: "Palaos"},
    { value: "PY", label: "Paraguay"},
    { value: "QA", label: "Qatar"},
    { value: "RE", label: "Réunion"},
    { value: "RO", label: "Roumanie"},
    { value: "RS", label: "Serbie"},
    { value: "RU", label: "Fédération De Russie"},
    { value: "RW", label: "Rwanda"},
    { value: "SA", label: "Arabie Saoudite"},
    { value: "SB", label: "Îles Salomon"},
    { value: "SC", label: "Seychelles"},
    { value: "SD", label: "Soudan"},
    { value: "SE", label: "Suède"},
    { value: "SG", label: "Singapour"},
    { value: "SH", label: "Sainte-Hélène"},
    { value: "SI", label: "Slovénie"},
    { value: "SJ", label: "Svalbard Et Jan Mayen"},
    { value: "SK", label: "Slovaquie"},
    { value: "SL", label: "Sierra Leone"},
    { value: "SM", label: "Saint-Marin"},
    { value: "SN", label: "Sénégal"},
    { value: "SO", label: "Somalie"},
    { value: "SR", label: "Suriname"},
    { value: "SS", label: "Soudan Du Sud"},
    { value: "ST", label: "Sao Tomé-Et-Principe"},
    { value: "SV", label: "République Du Salvador"},
    { value: "SX", label: "Saint-Martin (Partie Néerlandaise)"},
    { value: "SY", label: "République Arabe Syrienne"},
    { value: "SZ", label: "Swaziland"},
    { value: "TC", label: "Îles Turks-Et-Caïcos"},
    { value: "TD", label: "Tchad"},
    { value: "TF", label: "Terres Australes Françaises"},
    { value: "TG", label: "Togo"},
    { value: "TH", label: "Thaïlande"},
    { value: "TJ", label: "Tadjikistan"},
    { value: "TK", label: "Tokelau"},
    { value: "TL", label: "Timor-Leste"},
    { value: "TM", label: "Turkménistan"},
    { value: "TN", label: "Tunisie"},
    { value: "TO", label: "Tonga"},
    { value: "TR", label: "Turquie"},
    { value: "TT", label: "Trinité-Et-Tobago"},
    { value: "TV", label: "Tuvalu"},
    { value: "TW", label: "Taïwan"},
    { value: "TZ", label: "République-Unie De Tanzanie"},
    { value: "UA", label: "Ukraine"},
    { value: "UG", label: "Ouganda"},
    { value: "UM", label: "Îles Mineures Éloignées Des États-Unis"},
    { value: "US", label: "États-Unis"},
    { value: "UY", label: "Uruguay"},
    { value: "UZ", label: "Ouzbékistan"},
    { value: "VA", label: "Saint-Siège (État De La Cité Du Vatican)"},
    { value: "VC", label: "Saint-Vincent-Et-Les Grenadines"},
    { value: "VE", label: "Venezuela"},
    { value: "VG", label: "Îles Vierges Britanniques"},
    { value: "VI", label: "Îles Vierges Des États-Unis"},
    { value: "VN", label: "Viet Nam"},
    { value: "VU", label: "Vanuatu"},
    { value: "WF", label: "Wallis Et Futuna"},
    { value: "WS", label: "Samoa"},
    { value: "YE", label: "Yémen"},
    { value: "YT", label: "Mayotte"},
    { value: "ZA", label: "Afrique Du Sud"},
    { value: "ZM", label: "Zambie"},
    { value: "ZW", label: "Zimbabwe"}
  ],
  
  formations: [
    { value: "BTS MCO" },
    { value: "BTS NDR" },
    { value: "RNCP MUM" },
    { value: "RNCP NTC" },
    { value: "RNCP MERCD" },
    { value: "RNCP CMD" },
    { value: "RNCP MCI" },
    { value: "RNCP MCI CI" },
    { value: "RNCP MCI IA" },
    { value: "BTS SIO" },
    { value: "BTS WEB" },
    { value: "RNCP Réseaux" },
    { value: "RNCP Développeur" },
    { value: "RNCP AIS" },
    { value: "MPI Big Data" },
    { value: "MPI CyberSecurité" },
    { value: "RNCP ARH" },
    { value: "BTS Assurance" },
    { value: "BTS Banque" },
    { value: "BTS CG" },
    { value: "RNCP GCF" },
    { value: "BTS PME" },
    { value: "BTS Notariat" },
    { value: "DCG" },
    { value: "DCGS" },
    { value: "RNCP MRH" },
    { value: "RNCP BIM" },
    { value: "BTS MEC" },
    { value: "Bachelor BIM" },
    { value: "BTS Hôtellerie-Restauration" },
    { value: "BTS SPSSS" },
    { value: "RNCP RET" },
  ],

  entreprisesList: [
    { value: "Elitelabs" },
    { value: "ESTYA" },
    { value: "ADG" },
    { value: "Autre" }
  ],

  programme: [
    { value: "Programme Français" },
    { value: "Programme Anglais" },
  ],

  niveau_academic: [
    { id: 1, value: 'Pré-bac', label: 'Pré-bac' },
    { id: 2, value: 'Bac+2', label: 'Bac+2' },
    { id: 3, value: 'Bac+3', label: 'Bac+3' },
    { id: 4, value: 'Bac+4', label: 'Bac+4' },
    { id: 5, value: 'Bac+5', label: 'Bac+5' },
  ],

  statut_actuel: [
    { id: 1, value: 'Etudiant', label: 'Etudiant' },
    { id: 2, value: 'Salarié', label: 'Salarié' },
    { id: 3, value: 'Au chômage', label: 'Au chômage' },
    { id: 4, value: 'Autre', label: 'Autre' },
  ],

  civilite: [
    { id: 1, value: 'Monsieur', label: 'Mr' },
    { id: 2, value: 'Madame', label: 'Mme' },
    { id: 3, value: 'Autre', label: 'Autre' },
  ],

  profil: [
    { value: 'Salarié', label: 'Salarié' },
    { value: 'Apprenti', label: 'Apprenti' },
    { value: 'Demandeur d\'emploi', label: 'Demandeur d\'emploi'},
    { value: 'Particulier', label: 'Particulier'},
    { value: 'Contrat de professionnalisation', label: 'Contrat de professionnalisation' },
    { value: 'Autre', label: 'Autre' },
  ],

  statut: [
    { value: 'En cours de traitement', label: 'En cours de traitement' },
    { value: 'En attente d\'une réponse', label: 'En attente d\'une réponse' },
    { value: 'Traité', label: 'Traité' },
  ],

  sujetTicketing: [
    { value: "Attestation d'emploi et Certificat de travail", label: "Attestation d'emploi et Certificat de travail" },
    { value: "Déclarer un arrêt de travail", label: 'Déclarer un arrêt de travail' },
    { value: "Renouvellement de contrat", label: "Renouvellement de contrat" },
    { value: "Demander ses BDS", label: "Demander ses BDS" },
    { value: "Démission", label: "Démission" },
    { value: "Domiciliation de salaire", label: "Domiciliation de salaire" },
    { value: "Attestation de salaire", label: "Attestation de salaire" },
    { value: "Avenant de contrat", label: "Avenant de contrat" },
    { value: "Ticket resto", label: "Ticket resto" },
    { value: "Avenant de contrat", label: "Avenant de contrat" },
    { value: "Prévoyance et mutuelle", label: "Prévoyance et mutuelle" },

  ],

  dicNationaliteCode: [
    { 'Aruba': 'ABW' }, // TODO
    { 'Afghane': 'AFG' },
    { 'Angolaise': 'AGO' },
    { 'Anguilla': 'AIA' }, // TODO
    { 'Åland Islands': 'ALA' }, // TODO
    { 'Albanaise': 'ALB' },
    { 'Andorra': 'AND' }, // TODO
    { 'United Arab Emirates': 'ARE' }, // TODO
    { 'Argentine': 'ARG' },
    { 'Armenia': 'ARM' }, // TODO
    { 'American Samoa': 'ASM' }, // TODO
    { 'Antarctica': 'ATA' }, // TODO
    { 'French Southern Territories': 'ATF' }, // TODO
    { 'Antiguaise et barbudienne': 'ATG' },
    { 'Australienne': 'AUS' },
    { 'Autrichienne': 'AUT' },
    { 'Azerbaïdjanaise': 'AZE' },
    { 'Burundaise': 'BDI' },
    { 'Belge': 'BEL' },
    { 'Beninoise': 'BEN' },
    { 'Bonaire, Sint Eustatius and Saba': 'BES' }, //TODO
    { 'Burkinabe': 'BFA' },
    { 'Bangladaise': 'BGD' },
    { 'Bulgare': 'BGR' },
    { 'Bahreinienne': 'BHR' },
    { 'Bahamienne': 'BHS' },
    { 'Bosnienne': 'BIH' },
    { 'Saint BarthÃ©lemy': 'BLM' }, //TODO
    { 'Bielorusse': 'BLR' },
    { 'Belizienne': 'BLZ' },
    { 'Bermuda': 'BMU' },//TODO
    { 'Bolivienne': 'BOL' },
    { 'Brazil': 'BRA' },//TODO
    { 'Barbadienne': 'BRB' },
    { 'Brunei Darussalam': 'BRN' },//TODO
    { 'Bhoutanaise': 'BTN' },
    { 'Bouvet Island': 'BVT' },//TODO
    { 'Botswanaise': 'BWA' },
    { 'Centrafricaine': 'CAF' },
    { 'Canadienne': 'CAN' },
    { 'Cocos (Keeling) Islands': 'CCK' },//TODO
    { 'Suisse': 'CHE' },
    { 'Chilienne': 'CHL' },
    { 'Chinoise': 'CHN' },
    { "Ivoirienne": 'CIV' },
    { 'Camerounaise': 'CMR' },
    { 'Congolaise': 'COD' },
    { 'Congolais': 'COG' },
    { 'Cook Islands': 'COK' },//TODO
    { 'Colombienne': 'COL' },
    { 'Comorienne': 'COM' },
    { 'Cap-verdienn': 'CPV' },
    { 'Costaricaine': 'CRI' },
    { 'Cubaine': 'CUB' },
    { 'Curaçao': 'CUW' },//TODO
    { 'Christmas Island': 'CXR' },//TODO
    { 'Cayman Islands': 'CYM' },//TODO
    { 'Cyprus': 'CYP' },//TODO Chypriote
    { 'Czech Republic': 'CZE' }, //TODO Croate
    { 'Allemande': 'DEU' },
    { 'Djiboutienne': 'DJI' },
    { 'Dominiquaise': 'DMA' },
    { 'Danoise': 'DNK' }, { 'Dominicaine': 'DOM' }, { 'Algerienne': 'DZA' },
    { 'Equatorienne': 'ECU' }, { 'Egyptienne': 'EGY' }, { 'Erythreenne': 'ERI' },
    { 'Western Sahara': 'ESH' },//TODO 
    { 'Espagnole': 'ESP' },
    { 'Estonienne': 'EST' }, { 'Ethiopienne': 'ETH' }, { 'Finlandaise': 'FIN' },
    { 'Fidjienne': 'FJI' },
    { 'Falkland Islands (Malvinas)': 'FLK' },//TODO
    { 'Française': 'FRA' },
    { 'Faroe Islands': 'FRO' }, //TODO
    { 'Micronesia, Federated States of': 'FSM' },//TODO
    { 'Gambienne': 'GAB' },
    { 'Britannique': 'GBR' },
    { 'Georgienne': 'GEO' },
    { 'Guernsey': 'GGY' }, //TODO
    { 'Ghaneenne': 'GHA' },
    { 'Gibraltar': 'GIB' },//TODO
    { 'Guineenne': 'GIN' },
    { 'Guadeloupe': 'GLP' },//TODO
    { 'Gambia': 'GMB' },//TODO
    { 'Guinea-Bissau': 'GNB' },//TODO
    { 'Equatorial Guinea': 'GNQ' },//TODO
    { 'Grecque': 'GRC' }, { 'Grenadienne': 'GRD' },
    { 'Greenland': 'GRL' },//TODO
    { 'Guatemalteque': 'GTM' },
    { 'French Guiana': 'GUF' },//TODO
    { 'Guam': 'GUM' },//TODO
    { 'Guyanienne': 'GUY' },
    { 'Hong Kong': 'HKG' },//TODO
    { 'Heard Island and McDonald Islands': 'HMD' },//TODO
    { 'Hondurienne': 'HND' },
    { 'Croate': 'HRV' },
    { 'Haïtienne': 'HTI' },
    { 'Hongroise': 'HUN' },
    { 'Indonesienne': 'IDN' },
    { 'Isle of Man': 'IMN' },//TODO
    { 'Indienne': 'IND' },
    { 'British Indian Ocean Territory': 'IOT' },//TODO
    { 'Irlandaise': 'IRL' },//TODO
    { 'Iran, Islamic Republic of': 'IRN' }, //TODO
    { 'Irakienne': 'IRQ' },
    { 'Islandaise': 'ISL' },
    { 'Israel': 'ISR' },
    { 'Italienne': 'ITA' },
    { 'Jamaïcaine': 'JAM' },
    { 'Jersey': 'JEY' },//TODO
    { 'Jordanienne': 'JOR' }, { 'Japonaise': 'JPN' },
    { 'Kazakhstanaise': 'KAZ' }, { 'Kenyane': 'KEN' }, { 'Kirghize': 'KGZ' },
    { 'Cambodgienne': 'KHM' },
    { 'Kiribatienne': 'KIR' }, { 'Kittitienne-et-nevicienne': 'KNA' },
    { 'Korea, Republic of': 'KOR' }, //TODO
    { 'Kuwait': 'KWT' },//TODO Koweitienne
    { "Lao People's Democratic Republic": 'LAO' }, //TODO Laotienne
    { 'Libanaise': 'LBN' },
    { 'Liberienne': 'LBR' },
    { 'Libyenne': 'LBY' },
    { 'Saint Lucia': 'LCA' }, //TODO
    { 'Liechtensteinoise': 'LIE' },
    { 'Sri Lanka': 'LKA' },//TODO
    { 'Lesothane': 'LSO' },
    { 'Lituanienne': 'LTU' }, { 'Luxembourgeoise': 'LUX' },
    { 'Latvia': 'LVA' },  //TODO
    { 'Macao': 'MAC' }, //TODO
    { 'Saint-Martinois': 'MAF' },
    { 'Morocco': 'MAR' }, //TODO
    { 'Monaco': 'MCO' }, //TODO
    { 'Moldave': 'MDA' },
    { 'Madagascar': 'MDG' },//TODO
    { 'Maldivienne': 'MDV' },
    { 'Mexicaine': 'MEX' },
    { 'Marshall Islands': 'MHL' },//TODO
    { 'Macedonia, the former Yugoslav Republic of': 'MKD' },//TODO
    { 'Malienne': 'MLI' },
    { 'Maltaise': 'MLT' },
    { 'Myanmar': 'MMR' },//TODO
    { 'Montenegrine': 'MNE' },
    { 'Mongole': 'MNG' },
    { 'Northern Mariana Islands': 'MNP' },//TODO
    { 'Mozambicaine': 'MOZ' }, { 'Mauritanienne': 'MRT' },
    { 'Montserrat': 'MSR' },//TODO
    { 'Martinique': 'MTQ' },//TODO
    { 'Mauritius': 'MUS' },//TODO
    { 'Malawienne': 'MWI' },//TODO
    { 'Malaisienne': 'MYS' },
    { 'Mayotte': 'MYT' },//TODO
    { 'Namibienne': 'NAM' },
    { 'New Caledonia': 'NCL' },//TODO
    { 'Nigerienne': 'NER' },
    { 'Norfolk Island': 'NFK' },//TODO
    { 'Nigeriane': 'NGA' },
    { 'Nicaraguayenne': 'NIC' },
    { 'Niue': 'NIU' },//TODO Niuéenne
    { 'Néerlandaise': 'NLD' },
    { 'Norvegienne': 'NOR' }, { 'Nepalaise': 'NPL' },
    { 'Nauruane': 'NRU' }, { 'Neo-zelandaise': 'NZL' },
    { 'Omanaise': 'OMN' }, { 'Pakistanaise': 'PAK' }, { 'Panameenne': 'PAN' },
    { 'Pitcairn': 'PCN' },//TODO Pitcairnaise
    { 'Peruvienne': 'PER' }, { 'Philippine': 'PHL' },
    { 'Palau': 'PLW' },
    { 'Papouane-neoguineenne': 'PNG' },
    { 'Polonaise': 'POL' }, { 'Portoricaine': 'PRI' },
    { "Korea, Democratic People's Republic of": 'PRK' },
    { 'Portugaise': 'PRT' }, { 'Paraguayenne': 'PRY' }, { 'Palestinienne': 'PSE' },
    { 'French Polynesia': 'PYF' },//TODO Polynésiens
    { 'Qatarienne': 'QAT' },
    { 'Réunion': 'REU' },//TODO Réunionnais
    { 'Roumaine': 'ROU' },
    { 'Russe': 'RUS' }, { 'Rwandaise': 'RWA' },
    { 'Saoudienne': 'SAU' },
    { 'Soudanaise': 'SDN' }, { 'Senegalaise': 'SEN' },
    { 'Singapourienne': 'SGP' },
    { 'South Georgia and the South Sandwich Islands': 'SGS' },//TODO
    { 'Hellenique': 'SHN' },
    { 'Svalbard and Jan Mayen': 'SJM' },//TODO
    { 'Salomonaise': 'SLB' },
    { 'Sierra-leonaise': 'SLE' },
    { 'El Salvador': 'SLV' },
    { 'San Marino': 'SMR' },
    { 'Somalienne': 'SOM' },
    { 'Miquelonais': 'SPM' },
    { 'Serbe': 'SRB' },
    { 'Saoudienne': 'SSD' },
    { 'Santomeenne': 'STP' },
    { 'Surinamaise': 'SUR' },
    { 'Slovaque': 'SVK' }, { 'Slovene': 'SVN' }, { 'Suedoise': 'SWE' },
    { 'Swazie': 'SWZ' },
    { 'Sint Maarten (Dutch part)': 'SXM' },//TODO
    { 'Seychelloise': 'SYC' },
    { 'Syrienne': 'SYR' },
    { 'Turks and Caicos Islands': 'TCA' }, //TODO
    { 'Tchadienne': 'TCD' },
    { 'Togolaise': 'TGO' },
    { 'Thaïlandaise': 'THA' },
    { 'Tadjike': 'TJK' },
    { 'Tokelau': 'TKL' },
    { 'Turkmene': 'TKM' },
    { 'Est-timoraise': 'TLS' },
    { 'Tonguienne': 'TON' }, { 'Trinidadienne': 'TTO' }, { 'Tunisienne': 'TUN' },
    { 'Turque': 'TUR' }, { 'Tuvaluane': 'TUV' }, { 'Taiwanaise': 'TWN' },
    { 'Tanzanienne': 'TZA' },
    { 'Ougandaise': 'UGA' },
    { 'Ukrainienne': 'UKR' },
    { 'United States Minor Outlying Islands': 'UMI' }, //TODO
    { 'Uruguayenne': 'URY' },
    { 'Americaine': 'USA' },
    { 'Ouzbeke': 'UZB' },
    { 'Holy See (Vatican City State)': 'VAT' },//TODO
    { 'Saint-vincentaise-et-grenadine': 'VCT' },
    { 'Venezuelienne': 'VEN' },
    { 'Virgin Islands, British': 'VGB' },//TODO
    { 'Virgin Islands, U.S.': 'VIR' }, //TODO
    { 'Vietnamienne': 'VNM' },
    { 'Vanuatu': 'VUT' },
    { 'Wallis and Futuna': 'WLF' },
    { 'Samoane': 'WSM' },
    { 'Yemenite': 'YEM' },
    { 'Sud-africaine': 'ZAF' },
    { 'Zambienne': 'ZMB' }, { 'Zimbabweenne': 'ZWE' }
  ]

  ,
  pays: [ //default [76]
    { value: 'Aruba', label: 'Aruba' },
    { value: 'Afghanistan', label: 'Afghanistan' },
    { value: 'Angola', label: 'Angola' },
    { value: 'Anguilla', label: 'Anguilla' },
    { value: 'Ahvenanmaa', label: 'Ahvenanmaa' },
    { value: 'Albanie', label: 'Albanie' },
    { value: 'Andorre', label: 'Andorre' },
    { value: 'Émirats arabes unis', label: 'Émirats arabes unis' },
    { value: 'Argentine', label: 'Argentine' },
    { value: 'Arménie', label: 'Arménie' },
    { value: 'Samoa américaines', label: 'Samoa américaines' },
    { value: 'Antarctique', label: 'Antarctique' },
    { value: 'Terres australes et antarctiques françaises', label: 'Terres australes et antarctiques françaises' },
    { value: 'Antigua-et-Barbuda', label: 'Antigua-et-Barbuda' },
    { value: 'Australie', label: 'Australie' },
    { value: 'Autriche', label: 'Autriche' },
    { value: 'Azerbaïdjan', label: 'Azerbaïdjan' },
    { value: 'Burundi', label: 'Burundi' },
    { value: 'Belgique', label: 'Belgique' },
    { value: 'Bénin', label: 'Bénin' },
    { value: 'Burkina Faso', label: 'Burkina Faso' },
    { value: 'Bangladesh', label: 'Bangladesh' },
    { value: 'Bulgarie', label: 'Bulgarie' },
    { value: 'Bahreïn', label: 'Bahreïn' },
    { value: 'Bahamas', label: 'Bahamas' },
    { value: 'Bosnie-Herzégovine', label: 'Bosnie-Herzégovine' },
    { value: 'Saint-Barthélemy', label: 'Saint-Barthélemy' },
    { value: 'Sainte-Hélène, Ascension et Tristan da Cunha', label: 'Sainte-Hélène, Ascension et Tristan da Cunha' },
    { value: 'Biélorussie', label: 'Biélorussie' },
    { value: 'Belize', label: 'Belize' },
    { value: 'Bermudes', label: 'Bermudes' },
    { value: 'Bolivie', label: 'Bolivie' },
    { value: 'Pays-Bas caribéens', label: 'Pays-Bas caribéens' },
    { value: 'Brésil', label: 'Brésil' },
    { value: 'Barbade', label: 'Barbade' },
    { value: 'Brunei', label: 'Brunei' },
    { value: 'Bhoutan', label: 'Bhoutan' },
    { value: 'Île Bouvet', label: 'Île Bouvet' },
    { value: 'Botswana', label: 'Botswana' },
    { value: 'République centrafricaine', label: 'République centrafricaine' },
    { value: 'Canada', label: 'Canada' },
    { value: 'Îles Cocos', label: 'Îles Cocos' },
    { value: 'Suisse', label: 'Suisse' },
    { value: 'Chili', label: 'Chili' },
    { value: 'Chine', label: 'Chine' },
    { value: 'Côte d\'Ivoire', label: 'Côte d\'Ivoire' },
    { value: 'Cameroun', label: 'Cameroun' },
    { value: 'Congo (Rép. dém.)', label: 'Congo (Rép. dém.)' },
    { value: 'Congo', label: 'Congo' },
    { value: 'Îles Cook', label: 'Îles Cook' },
    { value: 'Colombie', label: 'Colombie' },
    { value: 'Comores', label: 'Comores' },
    { value: 'Îles du Cap-Vert', label: 'Îles du Cap-Vert' },
    { value: 'Costa Rica', label: 'Costa Rica' },
    { value: 'Cuba', label: 'Cuba' },
    { value: 'Curaçao', label: 'Curaçao' },
    { value: 'Île Christmas', label: 'Île Christmas' },
    { value: 'Îles Caïmans', label: 'Îles Caïmans' },
    { value: 'Chypre', label: 'Chypre' },
    { value: 'Tchéquie', label: 'Tchéquie' },
    { value: 'Allemagne', label: 'Allemagne' },
    { value: 'Djibouti', label: 'Djibouti' },
    { value: 'Dominique', label: 'Dominique' },
    { value: 'Danemark', label: 'Danemark' },
    { value: 'République dominicaine', label: 'République dominicaine' },
    { value: 'Algérie', label: 'Algérie' },
    { value: 'Équateur', label: 'Équateur' },
    { value: 'Égypte', label: 'Égypte' },
    { value: 'Érythrée', label: 'Érythrée' },
    { value: 'Sahara Occidental', label: 'Sahara Occidental' },
    { value: 'Espagne', label: 'Espagne' },
    { value: 'Estonie', label: 'Estonie' },
    { value: 'Éthiopie', label: 'Éthiopie' },
    { value: 'Finlande', label: 'Finlande' },
    { value: 'Fidji', label: 'Fidji' },
    { value: 'Îles Malouines', label: 'Îles Malouines' },
    { value: 'France', label: 'France' },
    { value: 'Îles Féroé', label: 'Îles Féroé' },
    { value: 'Micronésie', label: 'Micronésie' },
    { value: 'Gabon', label: 'Gabon' },
    { value: 'Royaume-Uni', label: 'Royaume-Uni' },
    { value: 'Géorgie', label: 'Géorgie' },
    { value: 'Guernesey', label: 'Guernesey' },
    { value: 'Ghana', label: 'Ghana' },
    { value: 'Gibraltar', label: 'Gibraltar' },
    { value: 'Guinée', label: 'Guinée' },
    { value: 'Guadeloupe', label: 'Guadeloupe' },
    { value: 'Gambie', label: 'Gambie' },
    { value: 'Guinée-Bissau', label: 'Guinée-Bissau' },
    { value: 'Guinée équatoriale', label: 'Guinée équatoriale' },
    { value: 'Grèce', label: 'Grèce' },
    { value: 'Grenade', label: 'Grenade' },
    { value: 'Groenland', label: 'Groenland' },
    { value: 'Guatemala', label: 'Guatemala' },
    { value: 'Guyane', label: 'Guyane' },
    { value: 'Guam', label: 'Guam' },
    { value: 'Guyana', label: 'Guyana' },
    { value: 'Hong Kong', label: 'Hong Kong' },
    { value: 'Îles Heard-et-MacDonald', label: 'Îles Heard-et-MacDonald' },
    { value: 'Honduras', label: 'Honduras' },
    { value: 'Croatie', label: 'Croatie' },
    { value: 'Haïti', label: 'Haïti' },
    { value: 'Hongrie', label: 'Hongrie' },
    { value: 'Indonésie', label: 'Indonésie' },
    { value: 'Île de Man', label: 'Île de Man' },
    { value: 'Inde', label: 'Inde' },
    { value: 'Territoire britannique de l\'océan Indien', label: 'Territoire britannique de l\'océan Indien' },
    { value: 'Irlande', label: 'Irlande' },
    { value: 'Iran', label: 'Iran' },
    { value: 'Irak', label: 'Irak' },
    { value: 'Islande', label: 'Islande' },
    { value: 'Israël', label: 'Israël' },
    { value: 'Italie', label: 'Italie' },
    { value: 'Jamaïque', label: 'Jamaïque' },
    { value: 'Jersey', label: 'Jersey' },
    { value: 'Jordanie', label: 'Jordanie' },
    { value: 'Japon', label: 'Japon' },
    { value: 'Kazakhstan', label: 'Kazakhstan' },
    { value: 'Kenya', label: 'Kenya' },
    { value: 'Kirghizistan', label: 'Kirghizistan' },
    { value: 'Cambodge', label: 'Cambodge' },
    { value: 'Kiribati', label: 'Kiribati' },
    { value: 'Saint-Christophe-et-Niévès', label: 'Saint-Christophe-et-Niévès' },
    { value: 'Corée du Sud', label: 'Corée du Sud' },
    { value: 'Kosovo', label: 'Kosovo' },
    { value: 'Koweït', label: 'Koweït' },
    { value: 'Laos', label: 'Laos' },
    { value: 'Liban', label: 'Liban' },
    { value: 'Liberia', label: 'Liberia' },
    { value: 'Libye', label: 'Libye' },
    { value: 'Sainte-Lucie', label: 'Sainte-Lucie' },
    { value: 'Liechtenstein', label: 'Liechtenstein' },
    { value: 'Sri Lanka', label: 'Sri Lanka' },
    { value: 'Lesotho', label: 'Lesotho' },
    { value: 'Lituanie', label: 'Lituanie' },
    { value: 'Luxembourg', label: 'Luxembourg' },
    { value: 'Lettonie', label: 'Lettonie' },
    { value: 'Macao', label: 'Macao' },
    { value: 'Saint-Martin', label: 'Saint-Martin' },
    { value: 'Maroc', label: 'Maroc' },
    { value: 'Monaco', label: 'Monaco' },
    { value: 'Moldavie', label: 'Moldavie' },
    { value: 'Madagascar', label: 'Madagascar' },
    { value: 'Maldives', label: 'Maldives' },
    { value: 'Mexique', label: 'Mexique' },
    { value: 'Îles Marshall', label: 'Îles Marshall' },
    { value: 'Macédoine', label: 'Macédoine' },
    { value: 'Mali', label: 'Mali' },
    { value: 'Malte', label: 'Malte' },
    { value: 'Birmanie', label: 'Birmanie' },
    { value: 'Monténégro', label: 'Monténégro' },
    { value: 'Mongolie', label: 'Mongolie' },
    { value: 'Îles Mariannes du Nord', label: 'Îles Mariannes du Nord' },
    { value: 'Mozambique', label: 'Mozambique' },
    { value: 'Mauritanie', label: 'Mauritanie' },
    { value: 'Montserrat', label: 'Montserrat' },
    { value: 'Martinique', label: 'Martinique' },
    { value: 'Île Maurice', label: 'Île Maurice' },
    { value: 'Malawi', label: 'Malawi' },
    { value: 'Malaisie', label: 'Malaisie' },
    { value: 'Mayotte', label: 'Mayotte' },
    { value: 'Namibie', label: 'Namibie' },
    { value: 'Nouvelle-Calédonie', label: 'Nouvelle-Calédonie' },
    { value: 'Niger', label: 'Niger' },
    { value: 'Île Norfolk', label: 'Île Norfolk' },
    { value: 'Nigéria', label: 'Nigéria' },
    { value: 'Nicaragua', label: 'Nicaragua' },
    { value: 'Niue', label: 'Niue' },
    { value: 'Pays-Bas', label: 'Pays-Bas' },
    { value: 'Norvège', label: 'Norvège' },
    { value: 'Népal', label: 'Népal' },
    { value: 'Nauru', label: 'Nauru' },
    { value: 'Nouvelle-Zélande', label: 'Nouvelle-Zélande' },
    { value: 'Oman', label: 'Oman' },
    { value: 'Pakistan', label: 'Pakistan' },
    { value: 'Panama', label: 'Panama' },
    { value: 'Îles Pitcairn', label: 'Îles Pitcairn' },
    { value: 'Pérou', label: 'Pérou' },
    { value: 'Philippines', label: 'Philippines' },
    { value: 'Palaos (Palau)', label: 'Palaos (Palau)' },
    { value: 'Papouasie-Nouvelle-Guinée', label: 'Papouasie-Nouvelle-Guinée' },
    { value: 'Pologne', label: 'Pologne' },
    { value: 'Porto Rico', label: 'Porto Rico' },
    { value: 'Corée du Nord', label: 'Corée du Nord' },
    { value: 'Portugal', label: 'Portugal' },
    { value: 'Paraguay', label: 'Paraguay' },
    { value: 'Palestine', label: 'Palestine' },
    { value: 'Polynésie française', label: 'Polynésie française' },
    { value: 'Qatar', label: 'Qatar' },
    { value: 'Réunion', label: 'Réunion' },
    { value: 'Roumanie', label: 'Roumanie' },
    { value: 'Russie', label: 'Russie' },
    { value: 'Rwanda', label: 'Rwanda' },
    { value: 'Arabie Saoudite', label: 'Arabie Saoudite' },
    { value: 'Soudan', label: 'Soudan' },
    { value: 'Sénégal', label: 'Sénégal' },
    { value: 'Singapour', label: 'Singapour' },
    { value: 'Géorgie du Sud-et-les Îles Sandwich du Sud', label: 'Géorgie du Sud-et-les Îles Sandwich du Sud' },
    { value: 'Svalbard et Jan Mayen', label: 'Svalbard et Jan Mayen' },
    { value: 'Îles Salomon', label: 'Îles Salomon' },
    { value: 'Sierra Leone', label: 'Sierra Leone' },
    { value: 'Salvador', label: 'Salvador' },
    { value: 'Saint-Marin', label: 'Saint-Marin' },
    { value: 'Somalie', label: 'Somalie' },
    { value: 'Saint-Pierre-et-Miquelon', label: 'Saint-Pierre-et-Miquelon' },
    { value: 'Serbie', label: 'Serbie' },
    { value: 'Soudan du Sud', label: 'Soudan du Sud' },
    { value: 'São Tomé et Príncipe', label: 'São Tomé et Príncipe' },
    { value: 'Surinam', label: 'Surinam' },
    { value: 'Slovaquie', label: 'Slovaquie' },
    { value: 'Slovénie', label: 'Slovénie' },
    { value: 'Suède', label: 'Suède' },
    { value: 'Swaziland', label: 'Swaziland' },
    { value: 'Saint-Martin', label: 'Saint-Martin' },
    { value: 'Seychelles', label: 'Seychelles' },
    { value: 'Syrie', label: 'Syrie' },
    { value: 'Îles Turques-et-Caïques', label: 'Îles Turques-et-Caïques' },
    { value: 'Tchad', label: 'Tchad' },
    { value: 'Togo', label: 'Togo' },
    { value: 'Thaïlande', label: 'Thaïlande' },
    { value: 'Tadjikistan', label: 'Tadjikistan' },
    { value: 'Tokelau', label: 'Tokelau' },
    { value: 'Turkménistan', label: 'Turkménistan' },
    { value: 'Timor oriental', label: 'Timor oriental' },
    { value: 'Tonga', label: 'Tonga' },
    { value: 'Trinité-et-Tobago', label: 'Trinité-et-Tobago' },
    { value: 'Tunisie', label: 'Tunisie' },
    { value: 'Turquie', label: 'Turquie' },
    { value: 'Tuvalu', label: 'Tuvalu' },
    { value: 'Taïwan', label: 'Taïwan' },
    { value: 'Tanzanie', label: 'Tanzanie' },
    { value: 'Ouganda', label: 'Ouganda' },
    { value: 'Ukraine', label: 'Ukraine' },
    { value: 'Îles mineures éloignées des États-Unis', label: 'Îles mineures éloignées des États-Unis' },
    { value: 'Uruguay', label: 'Uruguay' },
    { value: 'États-Unis', label: 'États-Unis' },
    { value: 'Ouzbékistan', label: 'Ouzbékistan' },
    { value: 'Cité du Vatican', label: 'Cité du Vatican' },
    { value: 'Saint-Vincent-et-les-Grenadines', label: 'Saint-Vincent-et-les-Grenadines' },
    { value: 'Venezuela', label: 'Venezuela' },
    { value: 'Îles Vierges britanniques', label: 'Îles Vierges britanniques' },
    { value: 'Îles Vierges des États-Unis', label: 'Îles Vierges des États-Unis' },
    { value: 'Viêt Nam', label: 'Viêt Nam' },
    { value: 'Vanuatu', label: 'Vanuatu' },
    { value: 'Wallis-et-Futuna', label: 'Wallis-et-Futuna' },
    { value: 'Samoa', label: 'Samoa' },
    { value: 'Yémen', label: 'Yémen' },
    { value: 'Afrique du Sud', label: 'Afrique du Sud' },
    { value: 'Zambie', label: 'Zambie' },
    { value: 'Zimbabwe', label: 'Zimbabwe' }
  ],


  nationalites: [
    //{ value: "", label: "Choisissez une nationalité" },
    { value: "Afghane", label: 'Afghane' },
    { value: "Albanaise", label: 'Albanaise' },
    { value: "Algerienne", label: 'Algerienne' },
    { value: "Allemande", label: 'Allemande' },
    { value: "Americaine", label: 'Americaine' },
    { value: "Andorrane", label: 'Andorrane' },
    { value: "Angolaise", label: 'Angolaise' },
    { value: "Antiguaise et barbudienne", label: 'Antiguaise et barbudienne' },
    { value: "Argentine", label: 'Argentine' },
    { value: "Australienne", label: 'Australienne' },
    { value: "Autrichienne", label: 'Autrichienne' },
    { value: "Azerbaïdjanaise", label: 'Azerbaïdjanaise' },
    { value: "Bahamienne", label: 'Bahamienne' },
    { value: "Bahreinienne", label: 'Bahreinienne' },
    { value: "Bangladaise", label: 'Bangladaise' },
    { value: "Barbadienne", label: 'Barbadienne' },
    { value: "Belge", label: 'Belge' },
    { value: "Belizienne", label: 'Belizienne' },
    { value: "Beninoise", label: 'Beninoise' },
    { value: "Bhoutanaise", label: 'Bhoutanaise' },
    { value: "Bielorusse", label: 'Bielorusse' },
    { value: "Birmane", label: 'Birmane' },
    { value: "Bissau-Guinéenne", label: 'Bissau-Guinéenne' },
    { value: "Bolivienne", label: 'Bolivienne' },
    { value: "Bosnienne", label: 'Bosnienne' },
    { value: "Botswanaise", label: 'Botswanaise' },
    { value: "Britannique", label: 'Britannique' },
    { value: "Bruneienne", label: 'Bruneienne' },
    { value: "Bulgare", label: 'Bulgare' },
    { value: "Burkinabe", label: 'Burkinabe' },
    { value: "Burundaise", label: 'Burundaise' },
    { value: "Cambodgienne", label: 'Cambodgienne' },
    { value: "Camerounaise", label: 'Camerounaise' },
    { value: "Canadienne", label: 'Canadienne' },
    { value: "Cap-verdienne", label: 'Cap-verdienne' },
    { value: "Centrafricaine", label: 'Centrafricaine' },
    { value: "Chilienne", label: 'Chilienne' },
    { value: "Chinoise", label: 'Chinoise' },
    { value: "Chypriote", label: 'Chypriote' },
    { value: "Colombienne", label: 'Colombienne' },
    { value: "Comorienne", label: 'Comorienne' },
    { value: "Congolais", label: 'Congolais' },
    { value: "Congolaise", label: 'Congolaise' },
    { value: "Costaricaine", label: 'Costaricaine' },
    { value: "Croate", label: 'Croate' },
    { value: "Cubaine", label: 'Cubaine' },
    { value: "Danoise", label: 'Danoise' },
    { value: "Djiboutienne", label: 'Djiboutienne' },
    { value: "Dominicaine", label: 'Dominicaine' },
    { value: "Dominiquaise", label: 'Dominiquaise' },
    { value: "Egyptienne", label: 'Egyptienne' },
    { value: "Emirienne", label: 'Emirienne' },
    { value: "Equato-guineenne", label: 'Equato-guineenne' },
    { value: "Equatorienne", label: 'Equatorienne' },
    { value: "Erythreenne", label: 'Erythreenne' },
    { value: "Espagnole", label: 'Espagnole' },
    { value: "Est-timoraise", label: 'Est-timoraise' },
    { value: "Estonienne", label: 'Estonienne' },
    { value: "Ethiopienne", label: 'Ethiopienne' },
    { value: "Fidjienne", label: 'Fidjienne' },
    { value: "Finlandaise", label: 'Finlandaise' },
    { value: "Française", label: 'Française' },
    { value: "Gabonaise", label: 'Gabonaise' },
    { value: "Gambienne", label: 'Gambienne' },
    { value: "Georgienne", label: 'Georgienne' },
    { value: "Ghaneenne", label: 'Ghaneenne' },
    { value: "Grèce", label: 'Grèce' },
    { value: "Grenadienne", label: 'Grenadienne' },
    { value: "Guatemalteque", label: 'Guatemalteque' },
    { value: "Guineenne", label: 'Guineenne' },
    { value: "Guyanienne", label: 'Guyanienne' },
    { value: "Grecque", label: 'Grecque' },
    { value: "Haïtienne", label: 'Haïtienne' },
    { value: "Hellenique", label: 'Hellenique' },
    { value: "Hondurienne", label: 'Hondurienne' },
    { value: "Hongroise", label: 'Hongroise' },
    { value: "Hongrie", label: 'Hongrie' },
    { value: "Indienne", label: 'Indienne' },
    { value: "Indonesienne", label: 'Indonesienne' },
    { value: "Irakienne", label: 'Irakienne' },
    { value: "Irlandaise", label: 'Irlandaise' },
    { value: "Islandaise", label: 'Islandaise' },
    { value: "Italienne", label: 'Italienne' },
    { value: "Ivoirienne", label: 'Ivoirienne' },
    { value: "Jamaïcaine", label: 'Jamaïcaine' },
    { value: "Japonaise", label: 'Japonaise' },
    { value: "Jordanienne", label: 'Jordanienne' },
    { value: "Kazakhstanaise", label: 'Kazakhstanaise' },
    { value: "Kenyane", label: 'Kenyane' },
    { value: "Kirghize", label: 'Kirghize' },
    { value: "Kiribatienne", label: 'Kiribatienne' },
    { value: "Kittitienne-et-nevicienne", label: 'Kittitienne-et-nevicienne' },
    { value: "Kossovienne", label: 'Kossovienne' },
    { value: "Koweitienne", label: 'Koweitienne' },
    { value: "Laotienne", label: 'Laotienne' },
    { value: "Lesothane", label: 'Lesothane' },
    { value: "Lettone", label: 'Lettone' },
    { value: "Libanaise", label: 'Libanaise' },
    { value: "Liberienne", label: 'Liberienne' },
    { value: "Libyenne", label: 'Libyenne' },
    { value: "Liechtensteinoise", label: 'Liechtensteinoise' },
    { value: "Lituanienne", label: 'Lituanienne' },
    { value: "Luxembourgeoise", label: 'Luxembourgeoise' },
    { value: "Macedonienne", label: 'Macedonienne' },
    { value: "Malaisienne", label: 'Malaisienne' },
    { value: "Malawienne", label: 'Malawienne' },
    { value: "Maldivienne", label: 'Maldivienne' },
    { value: "Malgache", label: 'Malgache' },
    { value: "Malienne", label: 'Malienne' },
    { value: "Maltaise", label: 'Maltaise' },
    { value: "Maltaise", label: 'Maltaise' },
    { value: "Miquelonais", label: 'Miquelonais' },
    { value: "Marshallaise", label: 'Marshallaise' },
    { value: "Mauricienne", label: 'Mauricienne' },
    { value: "Mauritanienne", label: 'Mauritanienne' },
    { value: "Mexicaine", label: 'Mexicaine' },
    { value: "Micronesienne", label: 'Micronesienne' },
    { value: "Moldave", label: 'Moldave' },
    { value: "Monegasque", label: 'Monegasque' },
    { value: "Mongole", label: 'Mongole' },
    { value: "Montenegrine", label: 'Montenegrine' },
    { value: "Mozambicaine", label: 'Mozambicaine' },
    { value: "Namibienne", label: 'Namibienne' },
    { value: "Nauruane", label: 'Nauruane' },
    { value: "Néerlandaise", label: 'Neerlandaise' },
    { value: "Neo-zelandaise", label: 'Neo-zelandaise' },
    { value: "Nepalaise", label: 'Nepalaise' },
    { value: "Nicaraguayenne", label: 'Nicaraguayenne' },
    { value: "Nigeriane", label: 'Nigeriane' },
    { value: "Nigerienne", label: 'Nigerienne' },
    { value: "Nord-coréenne", label: 'Nord-coréenne' },
    { value: "Norvegienne", label: 'Norvegienne' },
    { value: "Omanaise", label: 'Omanaise' },
    { value: "Ougandaise", label: 'Ougandaise' },
    { value: "Ouzbeke", label: 'Ouzbeke' },
    { value: "Pakistanaise", label: 'Pakistanaise' },
    { value: "Palau", label: 'Palau' },
    { value: "Palestinienne", label: 'Palestinienne' },
    { value: "Panameenne", label: 'Panameenne' },
    { value: "Papouane-neoguineenne", label: 'Papouane-neoguineenne' },
    { value: "Paraguayenne", label: 'Paraguayenne' },
    { value: "Peruvienne", label: 'Peruvienne' },
    { value: "Philippine", label: 'Philippine' },
    { value: "Polonaise", label: 'Polonaise' },
    { value: "Portoricaine", label: 'Portoricaine' },
    { value: "Portugaise", label: 'Portugaise' },
    { value: "Qatarienne", label: 'Qatarienne' },
    { value: "Roumaine", label: 'Roumaine' },
    { value: "Russe", label: 'Russe' },
    { value: "Rwandaise", label: 'Rwandaise' },
    { value: "Saint-lucienne", label: 'Saint-lucienne' },
    { value: "Saint-marinaise", label: 'Saint-marinaise' },
    { value: "Saint-Martinois", label: 'Saint-Martinois' },
    { value: "Saint-vincentaise-et-grenadine", label: 'Saint-vincentaise-et-grenadine' },
    { value: "Salomonaise", label: 'Salomonaise' },
    { value: "Salvadorienne", label: 'Salvadorienne' },
    { value: "Samoane", label: 'Samoane' },
    { value: "Santomeenne", label: 'Santomeenne' },
    { value: "Saoudienne", label: 'Saoudienne' },
    { value: "Senegalaise", label: 'Senegalaise' },
    { value: "Serbe", label: 'Serbe' },
    { value: "Seychelloise", label: 'Seychelloise' },
    { value: "Sierra-leonaise", label: 'Sierra-leonaise' },
    { value: "Singapourienne", label: 'Singapourienne' },
    { value: "Slovaque", label: 'Slovaque' },
    { value: "Slovene", label: 'Slovene' },
    { value: "Somalienne", label: 'Somalienne' },
    { value: "Soudanaise", label: 'Soudanaise' },
    { value: "Sri-lankaise", label: 'Sri-lankaise' },
    { value: "Sud-africaine", label: 'Sud-africaine' },
    { value: "Sud-coréenne", label: 'Sud-coréenne' },
    { value: "Suedoise", label: 'Suedoise' },
    { value: "Suisse", label: 'Suisse' },
    { value: "Surinamaise", label: 'Surinamaise' },
    { value: "Swazie", label: 'Swazie' },
    { value: "Syrienne", label: 'Syrienne' },
    { value: "Tadjike", label: 'Tadjike' },
    { value: "Taiwanaise", label: 'Taiwanaise' },
    { value: "Tanzanienne", label: 'Tanzanienne' },
    { value: "Tchadienne", label: 'Tchadienne' },
    { value: "Tcheque", label: 'Tcheque' },
    { value: "Thaïlandaise", label: 'Thaïlandaise' },
    { value: "Togolaise", label: 'Togolaise' },
    { value: "Tonguienne", label: 'Tonguienne' },
    { value: "Trinidadienne", label: 'Trinidadienne' },
    { value: "Tunisienne", label: 'Tunisienne' },
    { value: "Turkmene", label: 'Turkmene' },
    { value: "Turque", label: 'Turque' },
    { value: "Tuvaluane", label: 'Tuvaluane' },
    { value: "Ukrainienne", label: 'Ukrainienne' },
    { value: "Uruguayenne", label: 'Uruguayenne' },
    { value: "Vanuatuane", label: 'Vanuatuane' },
    { value: "Venezuelienne", label: 'Venezuelienne' },
    { value: "Vietnamienne", label: 'Vietnamienne' },
    { value: "Yemenite", label: 'Yemenite' },
    { value: "Zambienne", label: 'Zambienne' },
    { value: "Zimbabweenne", label: 'Zimbabweenne' },

  ],

  nationalites_UE: [
    { value: "Allemande", label: 'Allemande' },
    { value: "Autrichienne", label: 'Autrichienne' },
    { value: "Belge", label: 'Belge' },
    { value: "Danoise", label: 'Danoise' },
    { value: "Espagnole", label: 'Espagnole' },
    { value: "Estonienne", label: 'Estonienne' },
    { value: "Finlandaise", label: 'Finlandaise' },
    { value: "Française", label: 'Française' },
    { value: "Grèce", label: 'Grèce' },
    { value: "Hongrie", label: 'Hongrie' },
    { value: "Islandaise", label: 'Islandaise' },
    { value: "Italienne", label: 'Italienne' },
    { value: "Liechtensteinoise", label: 'Liechtensteinoise' },
    { value: "Lituanienne", label: 'Lituanienne' },
    { value: "Lettone", label: 'Lettone' },
    { value: "Luxembourgeoise", label: 'Luxembourgeoise' },
    { value: "Maltaise", label: 'Maltaise' },
    { value: "Norvegienne", label: 'Norvegienne' },
    { value: "Néerlandaise", label: 'Néerlandaise' },
    { value: "Polonaise", label: 'Polonaise' },
    { value: "Portugaise", label: 'Portugaise' },
    { value: "Slovaque", label: 'Slovaque' },
    { value: "Slovene", label: 'Slovene' },
    { value: "Suedoise", label: 'Suedoise' },
    { value: "Suisse", label: 'Suisse' },
    { value: "Tcheque", label: 'Tcheque' },
  ],

  nationalitesEDU: [
    { value: "Afghane", label: 'Afghane' },
    { value: "Albanaise", label: 'Albanaise' },
    { value: "Algerienne", label: 'Algerienne' },
    { value: "Americaine", label: 'Americaine' },
    { value: "Andorrane", label: 'Andorrane' },
    { value: "Angolaise", label: 'Angolaise' },
    { value: "Antiguaise et barbudienne", label: 'Antiguaise et barbudienne' },
    { value: "Argentine", label: 'Argentine' },
    { value: "Australienne", label: 'Australienne' },
    { value: "Azerbaïdjanaise", label: 'Azerbaïdjanaise' },
    { value: "Bahamienne", label: 'Bahamienne' },
    { value: "Bahreinienne", label: 'Bahreinienne' },
    { value: "Bangladaise", label: 'Bangladaise' },
    { value: "Barbadienne", label: 'Barbadienne' },
    { value: "Belizienne", label: 'Belizienne' },
    { value: "Beninoise", label: 'Beninoise' },
    { value: "Bhoutanaise", label: 'Bhoutanaise' },
    { value: "Bielorusse", label: 'Bielorusse' },
    { value: "Birmane", label: 'Birmane' },
    { value: "Bissau-Guinéenne", label: 'Bissau-Guinéenne' },
    { value: "Bolivienne", label: 'Bolivienne' },
    { value: "Bosnienne", label: 'Bosnienne' },
    { value: "Botswanaise", label: 'Botswanaise' },
    { value: "Britannique", label: 'Britannique' },
    { value: "Bruneienne", label: 'Bruneienne' },
    { value: "Bulgare", label: 'Bulgare' },
    { value: "Burkinabe", label: 'Burkinabe' },
    { value: "Burundaise", label: 'Burundaise' },
    { value: "Cambodgienne", label: 'Cambodgienne' },
    { value: "Camerounaise", label: 'Camerounaise' },
    { value: "Canadienne", label: 'Canadienne' },
    { value: "Cap-verdienne", label: 'Cap-verdienne' },
    { value: "Centrafricaine", label: 'Centrafricaine' },
    { value: "Chilienne", label: 'Chilienne' },
    { value: "Chinoise", label: 'Chinoise' },
    { value: "Chypriote", label: 'Chypriote' },
    { value: "Colombienne", label: 'Colombienne' },
    { value: "Comorienne", label: 'Comorienne' },
    { value: "Congolaise", label: 'Congolaise' },
    { value: "Costaricaine", label: 'Costaricaine' },
    { value: "Croate", label: 'Croate' },
    { value: "Cubaine", label: 'Cubaine' },
    { value: "Djiboutienne", label: 'Djiboutienne' },
    { value: "Dominicaine", label: 'Dominicaine' },
    { value: "Dominiquaise", label: 'Dominiquaise' },
    { value: "Egyptienne", label: 'Egyptienne' },
    { value: "Emirienne", label: 'Emirienne' },
    { value: "Equato-guineenne", label: 'Equato-guineenne' },
    { value: "Equatorienne", label: 'Equatorienne' },
    { value: "Erythreenne", label: 'Erythreenne' },
    { value: "Est-timoraise", label: 'Est-timoraise' },
    { value: "Ethiopienne", label: 'Ethiopienne' },
    { value: "Fidjienne", label: 'Fidjienne' },
    { value: "Gabonaise", label: 'Gabonaise' },
    { value: "Gambienne", label: 'Gambienne' },
    { value: "Georgienne", label: 'Georgienne' },
    { value: "Ghaneenne", label: 'Ghaneenne' },
    { value: "Grenadienne", label: 'Grenadienne' },
    { value: "Guatemalteque", label: 'Guatemalteque' },
    { value: "Guineenne", label: 'Guineenne' },
    { value: "Guyanienne", label: 'Guyanienne' },
    { value: "Grecque", label: 'Grecque' },
    { value: "Haïtienne", label: 'Haïtienne' },
    { value: "Hellenique", label: 'Hellenique' },
    { value: "Hondurienne", label: 'Hondurienne' },
    { value: "Hongroise", label: 'Hongroise' },
    { value: "Indienne", label: 'Indienne' },
    { value: "Indonesienne", label: 'Indonesienne' },
    { value: "Irakienne", label: 'Irakienne' },
    { value: "Irlandaise", label: 'Irlandaise' },
    { value: "Ivoirienne", label: 'Ivoirienne' },
    { value: "Jamaïcaine", label: 'Jamaïcaine' },
    { value: "Japonaise", label: 'Japonaise' },
    { value: "Jordanienne", label: 'Jordanienne' },
    { value: "Kazakhstanaise", label: 'Kazakhstanaise' },
    { value: "Kenyane", label: 'Kenyane' },
    { value: "Kirghize", label: 'Kirghize' },
    { value: "Kiribatienne", label: 'Kiribatienne' },
    { value: "Kittitienne-et-nevicienne", label: 'Kittitienne-et-nevicienne' },
    { value: "Kossovienne", label: 'Kossovienne' },
    { value: "Koweitienne", label: 'Koweitienne' },
    { value: "Laotienne", label: 'Laotienne' },
    { value: "Lesothane", label: 'Lesothane' },
    { value: "Libanaise", label: 'Libanaise' },
    { value: "Liberienne", label: 'Liberienne' },
    { value: "Libyenne", label: 'Libyenne' },
    { value: "Macedonienne", label: 'Macedonienne' },
    { value: "Malaisienne", label: 'Malaisienne' },
    { value: "Malawienne", label: 'Malawienne' },
    { value: "Maldivienne", label: 'Maldivienne' },
    { value: "Malgache", label: 'Malgache' },
    { value: "Malienne", label: 'Malienne' },
    { value: "Marocaine", label: 'Marocaine' },
    { value: "Marshallaise", label: 'Marshallaise' },
    { value: "Mauricienne", label: 'Mauricienne' },
    { value: "Mauritanienne", label: 'Mauritanienne' },
    { value: "Mexicaine", label: 'Mexicaine' },
    { value: "Micronesienne", label: 'Micronesienne' },
    { value: "Moldave", label: 'Moldave' },
    { value: "Monegasque", label: 'Monegasque' },
    { value: "Mongole", label: 'Mongole' },
    { value: "Montenegrine", label: 'Montenegrine' },
    { value: "Mozambicaine", label: 'Mozambicaine' },
    { value: "Namibienne", label: 'Namibienne' },
    { value: "Nauruane", label: 'Nauruane' },
    { value: "Neo-zelandaise", label: 'Neo-zelandaise' },
    { value: "Nepalaise", label: 'Nepalaise' },
    { value: "Nicaraguayenne", label: 'Nicaraguayenne' },
    { value: "Nigeriane", label: 'Nigeriane' },
    { value: "Nigerienne", label: 'Nigerienne' },
    { value: "Nord-coréenne", label: 'Nord-coréenne' },
    { value: "Omanaise", label: 'Omanaise' },
    { value: "Ougandaise", label: 'Ougandaise' },
    { value: "Ouzbeke", label: 'Ouzbeke' },
    { value: "Pakistanaise", label: 'Pakistanaise' },
    { value: "Palau", label: 'Palau' },
    { value: "Palestinienne", label: 'Palestinienne' },
    { value: "Panameenne", label: 'Panameenne' },
    { value: "Papouane-neoguineenne", label: 'Papouane-neoguineenne' },
    { value: "Paraguayenne", label: 'Paraguayenne' },
    { value: "Peruvienne", label: 'Peruvienne' },
    { value: "Philippine", label: 'Philippine' },
    { value: "Portoricaine", label: 'Portoricaine' },
    { value: "Qatarienne", label: 'Qatarienne' },
    { value: "Roumaine", label: 'Roumaine' },
    { value: "Russe", label: 'Russe' },
    { value: "Rwandaise", label: 'Rwandaise' },
    { value: "Saint-lucienne", label: 'Saint-lucienne' },
    { value: "Saint-marinaise", label: 'Saint-marinaise' },
    { value: "Saint-vincentaise-et-grenadine", label: 'Saint-vincentaise-et-grenadine' },
    { value: "Salomonaise", label: 'Salomonaise' },
    { value: "Salvadorienne", label: 'Salvadorienne' },
    { value: "Samoane", label: 'Samoane' },
    { value: "Santomeenne", label: 'Santomeenne' },
    { value: "Saoudienne", label: 'Saoudienne' },
    { value: "Senegalaise", label: 'Senegalaise' },
    { value: "Serbe", label: 'Serbe' },
    { value: "Seychelloise", label: 'Seychelloise' },
    { value: "Sierra-leonaise", label: 'Sierra-leonaise' },
    { value: "Singapourienne", label: 'Singapourienne' },
    { value: "Somalienne", label: 'Somalienne' },
    { value: "Soudanaise", label: 'Soudanaise' },
    { value: "Sri-lankaise", label: 'Sri-lankaise' },
    { value: "Sud-africaine", label: 'Sud-africaine' },
    { value: "Sud-coréenne", label: 'Sud-coréenne' },
    { value: "Surinamaise", label: 'Surinamaise' },
    { value: "Swazie", label: 'Swazie' },
    { value: "Syrienne", label: 'Syrienne' },
    { value: "Tadjike", label: 'Tadjike' },
    { value: "Taiwanaise", label: 'Taiwanaise' },
    { value: "Tanzanienne", label: 'Tanzanienne' },
    { value: "Tchadienne", label: 'Tchadienne' },
    { value: "Thaïlandaise", label: 'Thaïlandaise' },
    { value: "Togolaise", label: 'Togolaise' },
    { value: "Tonguienne", label: 'Tonguienne' },
    { value: "Trinidadienne", label: 'Trinidadienne' },
    { value: "Tunisienne", label: 'Tunisienne' },
    { value: "Turkmene", label: 'Turkmene' },
    { value: "Turque", label: 'Turque' },
    { value: "Tuvaluane", label: 'Tuvaluane' },
    { value: "Ukrainienne", label: 'Ukrainienne' },
    { value: "Uruguayenne", label: 'Uruguayenne' },
    { value: "Vanuatuane", label: 'Vanuatuane' },
    { value: "Venezuelienne", label: 'Venezuelienne' },
    { value: "Vietnamienne", label: 'Vietnamienne' },
    { value: "Yemenite", label: 'Yemenite' },
    { value: "Zambienne", label: 'Zambienne' },
    { value: "Zimbabweenne", label: 'Zimbabweenne' },

  ],
  entreprises: [
    { value: "ESTYA Education", label: 'ESTYA Education' },
    { value: "ESTYA Training", label: 'ESTYA Training' },
    { value: "Académie des gouvernantes", label: 'Académie des gouvernantes' },

  ],
  status: [
    { label: "À traiter", value: 'À traiter' },
    { label: "En cours de traitement", value: 'En cours de traitement' },
    { label: "En attente de retour", value: 'En attente de retour' },
    { label: "Clôturé", value: 'Clôturé' }
  ],

  etat_annee: [
    { label: "Nouvelle", value: 'Nouvelle' },
    { label: "Active", value: 'Active' },
    { label: "Archivée", value: 'Archivée' },
  ],

  programeFrDropdown:
    [
      { value: "BTS MCO - Management Commercial Opérationnel" },
      { value: "BTS NDRC - Négociation et Digitalisation de la Relation Client" },
      { value: "BTS CG - Comptabilité et Gestion" },
      { value: "RNCP CI - Commerce International" },
      { value: "RNCP NTC - Négociateur Technico-Commercial" },
      { value: "RNCP - Chargé de Développement Marketing et Commercial" },
      { value: "RNCP - IA - Ingénieur d'Affaires" },
      { value: "RNCP Management et Commerce International" },
      { value: "BTS Services Informatique aux Organisations - SISR" },
      { value: "BTS Services Informatique aux Organisations - SLAM" },
      { value: "RNCP TSSR - Technicien Supérieur Systèmes et Réseaux" },
      { value: "RNCP DWWM - Développeur Web & Web Mobile" },
      { value: "RNCP AIS - Administrateur d'Infrastructures Sécurisées" },
      { value: "RNCP CDA - Concepteur Développeur d'Applications" },
      { value: "RNCP MPI Big Data - Expert IT – Applications Intelligentes & Big Data" },
      { value: "RNCP MPI CyberSecurité - Expert IT – Cybersécurité et Haute Disponibilité" },
      { value: "BTS Collaborateur Juriste Notarial" },
      { value: "RNCP - Assistant Ressources Humaines" },
      { value: "RNCP- Management des Ressources Humaines" },
      { value: "BTS SPSSS - Services et Prestations des Secteurs Sanitaire et Social" },
      { value: "RNCP - BIM modeleur du Bâtiement" },
      { value: "RNCP - BIM modeleur du Coordinateur BIM du Bâtiment" },
    ],

  programEnDropdown:
    [
      { value: "Level 3 - Foundation Diploma for Higher Education Studies" },
      { value: "Level 4 - Business Management " },
      { value: "Level 4 - Information Technology " },
      { value: "Level 4 - Tourism and Hospitality Management" },
      { value: "Level 4 - Health and Social care Management" },
      { value: "Level 5 - Business Management" },
      { value: "Level 5 - Information Technology" },
      { value: "Level 7 - Project Management" },
      { value: "Level 7 - Tourism and Hospitality Management" },
      { value: "Level 7 - Health and Social care Management", }

    ],
  ADGprogrameFrDropdown:
    [
      { value: "GH - Gouvernant(e) en hôtellerie - Titre RNCP - Niveau 4" },
      { value: "CAP AEPE – CAP Accompagnant Educatif Petite Enfance" },
      { value: "GM - Gouvernant(e) de maison - Diplôme maison" },
      { value: "BTS MCO - Management Commercial Operationnel" },
      { value: "BTS NDRC - Négociation et Digitalisation de la Relation Client" },
      { value: "BTS GPME" },
      { value: "BTS CI - Commerce International" },
      { value: "NTC - Négociateur Technico-Commercial (Titre Professionnel)" },
      { value: "Chargé de gestion commerciale - Spécialité service commercial" },
      { value: "IA - Ingénieur d'Affaires" },
      { value: "Management et Stratégie d’Entreprise " },
      { value: "BTS SIO - Services Informatiques aux Organisations" },
      { value: "TSSR - Technicien Supérieur Systèmes et Réseaux (Titre professionnel)" },
      { value: "DWWM - Développeur Web et Web Mobile (Titre professionnel)" },
      { value: "AIS - Administrateur d’Infrastructures Sécurisées" },
      { value: "CDA - Concepteur Développeur d’Applications" },
      { value: "EXPERT IT - CYBERSÉCURITÉ ET HAUTE DISPONIBILITÉ " },
      { value: "EXPERT IT - APPLICATIONS INTELLIGENTES & BIG DATA " },
      { value: "BTS CJN  - Collaborateur Juriste Notarial" },
      { value: "BTS CG - Comptabilité et Gestion" },
      { value: "ARH : Assistant Ressources Humaines (Titre Professionnel)" },
      { value: "BIM Modeleur du Bâtiment (Titre Professionnel)" },
      { value: "Coordinateur BIM du Bâtiment" },
      { value: "BTS SPSSS - Services et Prestations dans les Secteurs Sanitaire et Social" },
      { value: "Formations continues IPERIA" }

    ],
    formationReinscrit:
    [
      { value: "BTS MCO 1ère année - Management Commercial Opérationnel" },
      { value: "BTS NDRC 1ère année - Négociation et Digitalisation de la Relation Client" },
      { value: "BTS CG 1ère année - Comptabilité et Gestion" },
      { value: "BTS MCO 2ème année - Management Commercial Opérationnel" },
      { value: "BTS NDRC 2ème année - Négociation et Digitalisation de la Relation Client" },
      { value: "BTS CG 2ème année	 - Comptabilité et Gestion" },
      { value: "BTS CI 1ère année - Commerce International" },
      { value: "BTS CI 2ème année - Commerce International" },
      { value: "RNCP NTC 1ère année - Négociateur Technico-Commercial" },
      { value: "RNCP NTC 2ème année - Négociateur Technico-Commercial" },
      { value: "RNCP - Chargé de Développement Marketing et Commercial" },
      { value: "RNCP - IA 1ère année - Ingénieur d'Affaires" },
      { value: "RNCP - IA 2ème année - Ingénieur d'Affaires" },
      { value: "RNCP Management et Commerce International" },
      { value: "BTS Services Informatique aux Organisations 1ère année - SISR" },
      { value: "BTS Services Informatique aux Organisations 2ème année - SISR" },
      { value: "BTS Services Informatique aux Organisations 1ère année - SLAM" },
      { value: "BTS Services Informatique aux Organisations 2ème année - SLAM" },
      { value: "RNCP TSSR - Technicien Supérieur Systèmes et Réseaux" },
      { value: "RNCP DWWM - Développeur Web & Web Mobile" },
      { value: "RNCP AIS - Administrateur d'Infrastructures Sécurisées" },
      { value: "RNCP CDA - Concepteur Développeur d'Applications" },
      { value: "RNCP MPI Big Data 1ère année - Expert IT – Applications Intelligentes & Big Data" },
      { value: "RNCP MPI Big Data 2ème année - Expert IT – Applications Intelligentes & Big Data" },
      { value: "RNCP MPI CyberSecurité 1ère année - Expert IT – Cybersécurité et Haute Disponibilité" },
      { value: "RNCP MPI CyberSecurité 2ème année - Expert IT – Cybersécurité et Haute Disponibilité" },
      { value: "BTS Collaborateur Juriste Notarial" },
      { value: "RNCP - Assistant Ressources Humaines" },
      { value: "RNCP - Management des Ressources Humaines - 1ère année" },
      { value: "RNCP - Management des Ressources Humaines - 2ème année" },
      { value: "BTS SPSSS - Services et Prestations des Secteurs Sanitaire et Social" },
      { value: "RNCP - BIM modeleur du Bâtiement" },
      { value: "RNCP - BIM modeleur du Coordinateur BIM du Bâtiment" },

      { value: "Level 3 - Foundation Diploma for Higher Education Studies" },
      { value: "Level 4 - Business Management " },
      { value: "Level 4 - Information Technology " },
      { value: "Level 4 - Tourism and Hospitality Management" },
      { value: "Level 4 - Health and Social care Management" },
      { value: "Level 5 - Business Management" },
      { value: "Level 5 - Information Technology" },
      { value: "Level 7 - Project Management" },
      { value: "Level 7 - Tourism and Hospitality Management" },
      { value: "Level 7 - Health and Social care Management" },
    ],
    ADGReinscrit: [
      { value: "GH - Gouvernant(e) en hôtellerie - Titre RNCP - Niveau 4" },
      { value: "CAP AEPE – CAP Accompagnant Educatif Petite Enfance" },
      { value: "GM - Gouvernant(e) de maison - Diplôme maison" },
      { value: "BTS MCO 1ère année - Management Commercial Operationnel" },
      { value: "BTS MCO 2ème année - Management Commercial Operationnel" },
      { value: "BTS NDRC 1ère année - Négociation et Digitalisation de la Relation Client" },
      { value: "BTS NDRC 2ème année - Négociation et Digitalisation de la Relation Client" },
      { value: "BTS GPME" },
      { value: "BTS CI 1ère année - Commerce International" },
      { value: "BTS CI 2ème année - Commerce International" },
      { value: "BTS NTC 1ère année - Négociateur Technico-Commercial (Titre Professionnel)" },
      { value: "BTS NTC 2ème année - Négociateur Technico-Commercial (Titre Professionnel)" },
      { value: "Chargé de gestion commerciale - Spécialité service commercial" },
      { value: "RNCP IA 1ère année - Ingénieur d'Affaires" },
      { value: "RNCP IA 2ème année - Ingénieur d'Affaires" },
      { value: "Management et Stratégie d’Entreprise " },
      { value: "BTS Services Informatique aux Organisations 1ère année - SISR" },
      { value: "BTS Services Informatique aux Organisations 2ème année - SISR" },
      { value: "BTS Services Informatique aux Organisations 1ère année - SLAM" },
      { value: "BTS Services Informatique aux Organisations 2ème année - SLAM" },
      { value: "TSSR - Technicien Supérieur Systèmes et Réseaux (Titre professionnel)" },
      { value: "DWWM - Développeur Web et Web Mobile (Titre professionnel)" },
      { value: "AIS - Administrateur d’Infrastructures Sécurisées" },
      { value: "CDA - Concepteur Développeur d’Applications" },
      { value: "EXPERT IT - CYBERSÉCURITÉ ET HAUTE DISPONIBILITÉ " },
      { value: "EXPERT IT - APPLICATIONS INTELLIGENTES & BIG DATA " },
      { value: "BTS CJN  - Collaborateur Juriste Notarial" },
      { value: "BTS CG - Comptabilité et Gestion" },
      { value: "ARH : Assistant Ressources Humaines (Titre Professionnel)" },
      { value: "BIM Modeleur du Bâtiment (Titre Professionnel)" },
      { value: "Coordinateur BIM du Bâtiment" },
      { value: "BTS SPSSS - Services et Prestations dans les Secteurs Sanitaire et Social" },
      { value: "Formations continues IPERIA" }
    ]
};
/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
