// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  origin: "https://ticket.estya.com/soc/",
  key: "6abdfb04243e096a4a51b46c8f3d4b32",
  User: null,
  clientId:"c2fdb74f-1c56-4ebb-872b-0e0279e91612",

  fr: {
    firstDayOfWeek: 0,
    dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
    dayNamesShort: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
    monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
    monthNamesShort: ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Jun', 'Jul', 'Aoû', 'Sep', 'Oct', 'Nov', 'Déc'],
    today: 'Aujourdhui',
    clear: 'Clear',
    dateFormat: 'dd-mm-yy',
    weekHeader: 'sem'
  },
  colorPaletteGreen: [
    "#b7de6a",
    "#486b03",
    "#79a324",
    "#cafa6b",
    "#c1db8c",
    "#6e9422",
    "#abb39b",
    "#b6e657",
    "#B2C787",
    "#8c9678",
  ],
  role: [
    { value: 'Agent'},
    { value: 'Responsable' }
  ],

  typeUser: [{
    value: "Etudiant",
  }, {
    value: "Salarié"
  }, {
    value: "Alternant/Stagiaire"
  }],

  campus:[
    {value:"Paris"},
    {value:"Montpellier"},
    {value:"Dubai"},
    {value:"Montréal"},
    {value:"Londres"},
    {value:"Tunis"},
    {value:"En Ligne(365)"}
  ],

  formations:[
    {value:"BTS MCO"},
    {value:"BTS NDR"},
    {value:"RNCP MUM"},
    {value:"RNCP NTC"},
    {value:"RNCP MERCD"},
    {value:"RNCP CMD"},
    {value:"RNCP MCI"},
    {value:"RNCP MCI CI"},
    {value:"RNCP MCI IA"},
    {value:"BTS SIO"},
    {value:"BTS WEB"},
    {value:"RNCP Réseaux"},
    {value:"RNCP Développeur"},
    {value:"RNCP AIS"},
    {value:"MPI Big Data"},
    {value:"MPI CyberSecurité"},
    {value:"RNCP ARH"},
    {value:"BTS Assurance"},
    {value:"BTS Banque"},
    {value:"BTS CG"},
    {value:"RNCP GCF"},
    {value:"BTS PME"},
    {value:"BTS Notariat"},
    {value:"DCG"},
    {value:"DCGS"},
    {value:"RNCP MRH"},
    {value:"RNCP BIM"},
    {value:"BTS MEC"},
    {value:"Bachelor BIM"},
    {value:"BTS Hôtellerie-Restauration"},
    {value:"BTS SPSSS"},
    {value:"RNCP RET"},
  ],

  entreprisesList:[
    {value:"Elitelabs"},
    {value:"ESTYA"},
    {value:"ADG"},
    {value:"Autre"}
  ],

  programme : [
    { value: "Programme Français"},
    { value: "Programme Anglais"},
  ],
  
  niveau_academic: [
    { id: 1, value:'Pré-bac', viewValue: 'Pré-bac'},
    { id: 2, value: 'Bac+2', viewValue: 'Bac+2'},
    { id: 3, value: 'Bac+3', viewValue: 'Bac+3'},
    { id: 4, value: 'Bac+4', viewValue: 'Bac+4'},
    { id: 5, value: 'Bac+5', viewValue: 'Bac+5'},
  ],

  statut_actuel : [
    { id: 1, value: 'Etudiant', viewValue: 'Etudiant'},
    { id: 2, value: 'Salarié', viewValue: 'Salarié'},
    { id: 3, value: 'Au chômage', viewValue: 'Au chômage'},
    { id: 4, value: 'Autre', viewValue: 'Autre'},
  ],

  civilite: [
    { id: 1, value: 'Monsieur', viewValue: 'Mr' },
    { id: 2, value: 'Madame', viewValue: 'Mme' },
    { id: 3, value: 'Autre', viewValue: 'Autre' },
  ],

  profil: [
    { id: 1, value: 'Salarié', viewValue: 'Salarié' },
    { id: 2, value: 'Apprenti', viewValue: 'Apprenti' },
    { id: 3, value: 'Demandeur d\'emploi', viewValue: 'Demandeur d\'emploi' },
    { id: 4, value: 'Paticulier', viewValue: 'Paticulier' },
    { id: 5, value: 'Autre', viewValue: 'Autre' },
    { id: 6, value: 'Contrat de professionnalisation', viewValue: 'Contrat de professionnalisation' },
    { id: 7, value: 'Contrat d\'apprentissage', viewValue: 'Contrat d\'apprentissage' },
  ],

  statut: [
    { value: 'En cours de traitement', viewValue: 'En cours de traitement' },
    { value: 'En attente d\'une réponse', viewValue: 'En attente d\'une réponse' },
    { value: 'Traité', viewValue: 'Traité' },
  ],

  sujetTicketing: [
    { value: "Attestation d'emploi et Certificat de travail", viewValue: "Attestation d'emploi et Certificat de travail" },
    { value: "Déclarer un arrêt de travail", viewValue: 'Déclarer un arrêt de travail' },
    { value: "Renouvellement de contrat", viewValue: "Renouvellement de contrat" },
    { value: "Demander ses BDS", viewValue: "Demander ses BDS" },
    { value: "Démission", viewValue: "Démission" },
    { value: "Domiciliation de salaire", viewValue: "Domiciliation de salaire" },
    { value: "Attestation de salaire", viewValue: "Attestation de salaire" },
    { value: "Avenant de contrat", viewValue: "Avenant de contrat" },
    { value: "Ticket resto", viewValue: "Ticket resto" },
    { value: "Avenant de contrat", viewValue: "Avenant de contrat" },
    { value: "Prévoyance et mutuelle", viewValue: "Prévoyance et mutuelle" },

  ],

  dicNationaliteCode: [
    { 'Aruba': 'ABW' }, // TODO
    { 'Afghane': 'AFG' },
    { 'Angolaise': 'AGO' },
    { 'Anguilla': 'AIA' }, // TODO
    { 'Åland Islands': 'ALA' }, // TODO
    { 'Albanaise': 'ALB' },
    { 'Andorra': 'AND' }, // TODO
    { 'United Arab Emirates': 'ARE' }, // TODO
    { 'Argentine': 'ARG' },
    { 'Armenia': 'ARM' }, // TODO
    { 'American Samoa': 'ASM' }, // TODO
    { 'Antarctica': 'ATA' }, // TODO
    { 'French Southern Territories': 'ATF' }, // TODO
    { 'Antiguaise et barbudienne': 'ATG' },
    { 'Australienne': 'AUS' },
    { 'Autrichienne': 'AUT' },
    { 'Azerbaïdjanaise': 'AZE' },
    { 'Burundaise': 'BDI' },
    { 'Belge': 'BEL' },
    { 'Beninoise': 'BEN' },
    { 'Bonaire, Sint Eustatius and Saba': 'BES' }, //TODO
    { 'Burkinabe': 'BFA' },
    { 'Bangladaise': 'BGD' },
    { 'Bulgare': 'BGR' },
    { 'Bahreinienne': 'BHR' },
    { 'Bahamienne': 'BHS' },
    { 'Bosnienne': 'BIH' },
    { 'Saint BarthÃ©lemy': 'BLM' }, //TODO
    { 'Bielorusse': 'BLR' },
    { 'Belizienne': 'BLZ' },
    { 'Bermuda': 'BMU' },//TODO
    { 'Bolivienne': 'BOL' },
    { 'Brazil': 'BRA' },//TODO
    { 'Barbadienne': 'BRB' },
    { 'Brunei Darussalam': 'BRN' },//TODO
    { 'Bhoutanaise': 'BTN' },
    { 'Bouvet Island': 'BVT' },//TODO
    { 'Botswanaise': 'BWA' },
    { 'Centrafricaine': 'CAF' },
    { 'Canadienne': 'CAN' },
    { 'Cocos (Keeling) Islands': 'CCK' },//TODO
    { 'Suisse': 'CHE' },
    { 'Chilienne': 'CHL' },
    { 'Chinoise': 'CHN' },
    { "Ivoirienne": 'CIV' },
    { 'Camerounaise': 'CMR' },
    { 'Congolaise': 'COD' },
    { 'Congolais': 'COG' },
    { 'Cook Islands': 'COK' },//TODO
    { 'Colombienne': 'COL' },
    { 'Comorienne': 'COM' },
    { 'Cap-verdienn': 'CPV' },
    { 'Costaricaine': 'CRI' },
    { 'Cubaine': 'CUB' },
    { 'Curaçao': 'CUW' },//TODO
    { 'Christmas Island': 'CXR' },//TODO
    { 'Cayman Islands': 'CYM' },//TODO
    { 'Cyprus': 'CYP' },//TODO Chypriote
    { 'Czech Republic': 'CZE' }, //TODO Croate
    { 'Allemande': 'DEU' },
    { 'Djiboutienne': 'DJI' },
    { 'Dominiquaise': 'DMA' },
    { 'Danoise': 'DNK' }, { 'Dominicaine': 'DOM' }, { 'Algerienne': 'DZA' },
    { 'Equatorienne': 'ECU' }, { 'Egyptienne': 'EGY' }, { 'Erythreenne': 'ERI' },
    { 'Western Sahara': 'ESH' },//TODO 
    { 'Espagnole': 'ESP' },
    { 'Estonienne': 'EST' }, { 'Ethiopienne': 'ETH' }, { 'Finlandaise': 'FIN' },
    { 'Fidjienne': 'FJI' },
    { 'Falkland Islands (Malvinas)': 'FLK' },//TODO
    { 'Française': 'FRA' },
    { 'Faroe Islands': 'FRO' }, //TODO
    { 'Micronesia, Federated States of': 'FSM' },//TODO
    { 'Gambienne': 'GAB' },
    { 'Britannique': 'GBR' },
    { 'Georgienne': 'GEO' },
    { 'Guernsey': 'GGY' }, //TODO
    { 'Ghaneenne': 'GHA' },
    { 'Gibraltar': 'GIB' },//TODO
    { 'Guineenne': 'GIN' },
    { 'Guadeloupe': 'GLP' },//TODO
    { 'Gambia': 'GMB' },//TODO
    { 'Guinea-Bissau': 'GNB' },//TODO
    { 'Equatorial Guinea': 'GNQ' },//TODO
    { 'Grecque': 'GRC' }, { 'Grenadienne': 'GRD' },
    { 'Greenland': 'GRL' },//TODO
    { 'Guatemalteque': 'GTM' },
    { 'French Guiana': 'GUF' },//TODO
    { 'Guam': 'GUM' },//TODO
    { 'Guyanienne': 'GUY' },
    { 'Hong Kong': 'HKG' },//TODO
    { 'Heard Island and McDonald Islands': 'HMD' },//TODO
    { 'Hondurienne': 'HND' },
    { 'Croate': 'HRV' },
    { 'Haïtienne': 'HTI' },
    { 'Hongroise': 'HUN' },
    { 'Indonesienne': 'IDN' },
    { 'Isle of Man': 'IMN' },//TODO
    { 'Indienne': 'IND' },
    { 'British Indian Ocean Territory': 'IOT' },//TODO
    { 'Irlandaise': 'IRL' },//TODO
    { 'Iran, Islamic Republic of': 'IRN' }, //TODO
    { 'Irakienne': 'IRQ' },
    { 'Islandaise': 'ISL' },
    { 'Israel': 'ISR' },
    { 'Italienne': 'ITA' },
    { 'Jamaïcaine': 'JAM' },
    { 'Jersey': 'JEY' },//TODO
    { 'Jordanienne': 'JOR' }, { 'Japonaise': 'JPN' },
    { 'Kazakhstanaise': 'KAZ' }, { 'Kenyane': 'KEN' }, { 'Kirghize': 'KGZ' },
    { 'Cambodgienne': 'KHM' },
    { 'Kiribatienne': 'KIR' }, { 'Kittitienne-et-nevicienne': 'KNA' },
    { 'Korea, Republic of': 'KOR' }, //TODO
    { 'Kuwait': 'KWT' },//TODO Koweitienne
    { "Lao People's Democratic Republic": 'LAO' }, //TODO Laotienne
    { 'Libanaise': 'LBN' },
    { 'Liberienne': 'LBR' },
    { 'Libyenne': 'LBY' },
    { 'Saint Lucia': 'LCA' }, //TODO
    { 'Liechtensteinoise': 'LIE' },
    { 'Sri Lanka': 'LKA' },//TODO
    { 'Lesothane': 'LSO' },
    { 'Lituanienne': 'LTU' }, { 'Luxembourgeoise': 'LUX' },
    { 'Latvia': 'LVA' },  //TODO
    { 'Macao': 'MAC' }, //TODO
    { 'Saint-Martinois': 'MAF' },
    { 'Morocco': 'MAR' }, //TODO
    { 'Monaco': 'MCO' }, //TODO
    { 'Moldave': 'MDA' },
    { 'Madagascar': 'MDG' },//TODO
    { 'Maldivienne': 'MDV' },
    { 'Mexicaine': 'MEX' },
    { 'Marshall Islands': 'MHL' },//TODO
    { 'Macedonia, the former Yugoslav Republic of': 'MKD' },//TODO
    { 'Malienne': 'MLI' },
    { 'Maltaise': 'MLT' },
    { 'Myanmar': 'MMR' },//TODO
    { 'Montenegrine': 'MNE' },
    { 'Mongole': 'MNG' },
    { 'Northern Mariana Islands': 'MNP' },//TODO
    { 'Mozambicaine': 'MOZ' }, { 'Mauritanienne': 'MRT' },
    { 'Montserrat': 'MSR' },//TODO
    { 'Martinique': 'MTQ' },//TODO
    { 'Mauritius': 'MUS' },//TODO
    { 'Malawienne': 'MWI' },//TODO
    { 'Malaisienne': 'MYS' },
    { 'Mayotte': 'MYT' },//TODO
    { 'Namibienne': 'NAM' },
    { 'New Caledonia': 'NCL' },//TODO
    { 'Nigerienne': 'NER' },
    { 'Norfolk Island': 'NFK' },//TODO
    { 'Nigeriane': 'NGA' },
    { 'Nicaraguayenne': 'NIC' },
    { 'Niue': 'NIU' },//TODO Niuéenne
    { 'Néerlandaise': 'NLD' },
    { 'Norvegienne': 'NOR' }, { 'Nepalaise': 'NPL' },
    { 'Nauruane': 'NRU' }, { 'Neo-zelandaise': 'NZL' },
    { 'Omanaise': 'OMN' }, { 'Pakistanaise': 'PAK' }, { 'Panameenne': 'PAN' },
    { 'Pitcairn': 'PCN' },//TODO Pitcairnaise
    { 'Peruvienne': 'PER' }, { 'Philippine': 'PHL' },
    { 'Palau': 'PLW' },
    { 'Papouane-neoguineenne': 'PNG' },
    { 'Polonaise': 'POL' }, { 'Portoricaine': 'PRI' },
    { "Korea, Democratic People's Republic of": 'PRK' },
    { 'Portugaise': 'PRT' }, { 'Paraguayenne': 'PRY' }, { 'Palestinienne': 'PSE' },
    { 'French Polynesia': 'PYF' },//TODO Polynésiens
    { 'Qatarienne': 'QAT' },
    { 'Réunion': 'REU' },//TODO Réunionnais
    { 'Roumaine': 'ROU' },
    { 'Russe': 'RUS' }, { 'Rwandaise': 'RWA' },
    { 'Saoudienne': 'SAU' },
    { 'Soudanaise': 'SDN' }, { 'Senegalaise': 'SEN' },
    { 'Singapourienne': 'SGP' },
    { 'South Georgia and the South Sandwich Islands': 'SGS' },//TODO
    { 'Hellenique': 'SHN' },
    { 'Svalbard and Jan Mayen': 'SJM' },//TODO
    { 'Salomonaise': 'SLB' },
    { 'Sierra-leonaise': 'SLE' },
    { 'El Salvador': 'SLV' },
    { 'San Marino': 'SMR' },
    { 'Somalienne': 'SOM' },
    { 'Miquelonais': 'SPM' },
    { 'Serbe': 'SRB' },
    { 'Saoudienne': 'SSD' },
    { 'Santomeenne': 'STP' },
    { 'Surinamaise': 'SUR' },
    { 'Slovaque': 'SVK' }, { 'Slovene': 'SVN' }, { 'Suedoise': 'SWE' },
    { 'Swazie': 'SWZ' },
    { 'Sint Maarten (Dutch part)': 'SXM' },//TODO
    { 'Seychelloise': 'SYC' },
    { 'Syrienne': 'SYR' },
    { 'Turks and Caicos Islands': 'TCA' }, //TODO
    { 'Tchadienne': 'TCD' },
    { 'Togolaise': 'TGO' },
    { 'Thaïlandaise': 'THA' },
    { 'Tadjike': 'TJK' },
    { 'Tokelau': 'TKL' },
    { 'Turkmene': 'TKM' },
    { 'Est-timoraise': 'TLS' },
    { 'Tonguienne': 'TON' }, { 'Trinidadienne': 'TTO' }, { 'Tunisienne': 'TUN' },
    { 'Turque': 'TUR' }, { 'Tuvaluane': 'TUV' }, { 'Taiwanaise': 'TWN' },
    { 'Tanzanienne': 'TZA' },
    { 'Ougandaise': 'UGA' }, 
    { 'Ukrainienne': 'UKR' },
    { 'United States Minor Outlying Islands': 'UMI' }, //TODO
    { 'Uruguayenne': 'URY' },
    { 'Americaine': 'USA' },
    { 'Ouzbeke': 'UZB' },
    { 'Holy See (Vatican City State)': 'VAT' },//TODO
    { 'Saint-vincentaise-et-grenadine': 'VCT' },
    { 'Venezuelienne': 'VEN' },
    { 'Virgin Islands, British': 'VGB' },//TODO
    { 'Virgin Islands, U.S.': 'VIR' }, //TODO
    { 'Vietnamienne': 'VNM' },
    { 'Vanuatu': 'VUT' },
    { 'Wallis and Futuna': 'WLF' },
    { 'Samoane': 'WSM' },
    { 'Yemenite': 'YEM' },
    { 'Sud-africaine': 'ZAF' },
    { 'Zambienne': 'ZMB' }, { 'Zimbabweenne': 'ZWE' }
  ],


  nationalites: [
    {value:"",viewValue:"Choissisez une nationalité"},
    { value: "Afghane", viewValue: 'Afghane' },
    { value: "Albanaise", viewValue: 'Albanaise' },
    { value: "Algerienne", viewValue: 'Algerienne' },
    { value: "Allemande", viewValue: 'Allemande' },
    { value: "Americaine", viewValue: 'Americaine' },
    { value: "Andorrane", viewValue: 'Andorrane' },
    { value: "Angolaise", viewValue: 'Angolaise' },
    { value: "Antiguaise et barbudienne", viewValue: 'Antiguaise et barbudienne' },
    { value: "Argentine", viewValue: 'Argentine' },
    { value: "Australienne", viewValue: 'Australienne' },
    { value: "Autrichienne", viewValue: 'Autrichienne' },
    { value: "Azerbaïdjanaise", viewValue: 'Azerbaïdjanaise' },
    { value: "Bahamienne", viewValue: 'Bahamienne' },
    { value: "Bahreinienne", viewValue: 'Bahreinienne' },
    { value: "Bangladaise", viewValue: 'Bangladaise' },
    { value: "Barbadienne", viewValue: 'Barbadienne' },
    { value: "Belge", viewValue: 'Belge' },
    { value: "Belizienne", viewValue: 'Belizienne' },
    { value: "Beninoise", viewValue: 'Beninoise' },
    { value: "Bhoutanaise", viewValue: 'Bhoutanaise' },
    { value: "Bielorusse", viewValue: 'Bielorusse' },
    { value: "Birmane", viewValue: 'Birmane' },
    { value: "Bissau-Guinéenne", viewValue: 'Bissau-Guinéenne' },
    { value: "Bolivienne", viewValue: 'Bolivienne' },
    { value: "Bosnienne", viewValue: 'Bosnienne' },
    { value: "Botswanaise", viewValue: 'Botswanaise' },
    { value: "Britannique", viewValue: 'Britannique' },
    { value: "Bruneienne", viewValue: 'Bruneienne' },
    { value: "Bulgare", viewValue: 'Bulgare' },
    { value: "Burkinabe", viewValue: 'Burkinabe' },
    { value: "Burundaise", viewValue: 'Burundaise' },
    { value: "Cambodgienne", viewValue: 'Cambodgienne' },
    { value: "Camerounaise", viewValue: 'Camerounaise' },
    { value: "Canadienne", viewValue: 'Canadienne' },
    { value: "Cap-verdienne", viewValue: 'Cap-verdienne' },
    { value: "Centrafricaine", viewValue: 'Centrafricaine' },
    { value: "Chilienne", viewValue: 'Chilienne' },
    { value: "Chinoise", viewValue: 'Chinoise' },
    { value: "Chypriote", viewValue: 'Chypriote' },
    { value: "Colombienne", viewValue: 'Colombienne' },
    { value: "Comorienne", viewValue: 'Comorienne' },
    { value: "Congolaise", viewValue: 'Congolaise' },
    { value: "Costaricaine", viewValue: 'Costaricaine' },
    { value: "Croate", viewValue: 'Croate' },
    { value: "Cubaine", viewValue: 'Cubaine' },
    { value: "Danoise", viewValue: 'Danoise' },
    { value: "Djiboutienne", viewValue: 'Djiboutienne' },
    { value: "Dominicaine", viewValue: 'Dominicaine' },
    { value: "Dominiquaise", viewValue: 'Dominiquaise' },
    { value: "Egyptienne", viewValue: 'Egyptienne' },
    { value: "Emirienne", viewValue: 'Emirienne' },
    { value: "Equato-guineenne", viewValue: 'Equato-guineenne' },
    { value: "Equatorienne", viewValue: 'Equatorienne' },
    { value: "Erythreenne", viewValue: 'Erythreenne' },
    { value: "Espagnole", viewValue: 'Espagnole' },
    { value: "Est-timoraise", viewValue: 'Est-timoraise' },
    { value: "Estonienne", viewValue: 'Estonienne' },
    { value: "Ethiopienne", viewValue: 'Ethiopienne' },
    { value: "Fidjienne", viewValue: 'Fidjienne' },
    { value: "Finlandaise", viewValue: 'Finlandaise' },
    { value: "Française", viewValue: 'Française' },
    { value: "Gabonaise", viewValue: 'Gabonaise' },
    { value: "Gambienne", viewValue: 'Gambienne' },
    { value: "Georgienne", viewValue: 'Georgienne' },
    { value: "Ghaneenne", viewValue: 'Ghaneenne' },
    { value: "Grèce", viewValue: 'Grèce' },
    { value: "Grenadienne", viewValue: 'Grenadienne' },
    { value: "Guatemalteque", viewValue: 'Guatemalteque' },
    { value: "Guineenne", viewValue: 'Guineenne' },
    { value: "Guyanienne", viewValue: 'Guyanienne' },
    { value: "Grecque", viewValue: 'Grecque' },
    { value: "Haïtienne", viewValue: 'Haïtienne' },
    { value: "Hellenique", viewValue: 'Hellenique' },
    { value: "Hondurienne", viewValue: 'Hondurienne' },
    { value: "Hongroise", viewValue: 'Hongroise' },
    { value: "Hongrie", viewValue: 'Hongrie' },
    { value: "Indienne", viewValue: 'Indienne' },
    { value: "Indonesienne", viewValue: 'Indonesienne' },
    { value: "Irakienne", viewValue: 'Irakienne' },
    { value: "Irlandaise", viewValue: 'Irlandaise' },
    { value: "Islandaise", viewValue: 'Islandaise' },
    { value: "Italienne", viewValue: 'Italienne' },
    { value: "Ivoirienne", viewValue: 'Ivoirienne' },
    { value: "Jamaïcaine", viewValue: 'Jamaïcaine' },
    { value: "Japonaise", viewValue: 'Japonaise' },
    { value: "Jordanienne", viewValue: 'Jordanienne' },
    { value: "Kazakhstanaise", viewValue: 'Kazakhstanaise' },
    { value: "Kenyane", viewValue: 'Kenyane' },
    { value: "Kirghize", viewValue: 'Kirghize' },
    { value: "Kiribatienne", viewValue: 'Kiribatienne' },
    { value: "Kittitienne-et-nevicienne", viewValue: 'Kittitienne-et-nevicienne' },
    { value: "Kossovienne", viewValue: 'Kossovienne' },
    { value: "Koweitienne", viewValue: 'Koweitienne' },
    { value: "Laotienne", viewValue: 'Laotienne' },
    { value: "Lesothane", viewValue: 'Lesothane' },
    { value: "Lettone", viewValue: 'Lettone' },
    { value: "Libanaise", viewValue: 'Libanaise' },
    { value: "Liberienne", viewValue: 'Liberienne' },
    { value: "Libyenne", viewValue: 'Libyenne' },
    { value: "Liechtensteinoise", viewValue: 'Liechtensteinoise' },
    { value: "Lituanienne", viewValue: 'Lituanienne' },
    { value: "Luxembourgeoise", viewValue: 'Luxembourgeoise' },
    { value: "Macedonienne", viewValue: 'Macedonienne' },
    { value: "Malaisienne", viewValue: 'Malaisienne' },
    { value: "Malawienne", viewValue: 'Malawienne' },
    { value: "Maldivienne", viewValue: 'Maldivienne' },
    { value: "Malgache", viewValue: 'Malgache' },
    { value: "Malienne", viewValue: 'Malienne' },
    { value: "Maltaise", viewValue: 'Maltaise' },
    { value: "Marocaine", viewValue: 'Marocaine' },
    { value: "Marshallaise", viewValue: 'Marshallaise' },
    { value: "Mauricienne", viewValue: 'Mauricienne' },
    { value: "Mauritanienne", viewValue: 'Mauritanienne' },
    { value: "Mexicaine", viewValue: 'Mexicaine' },
    { value: "Micronesienne", viewValue: 'Micronesienne' },
    { value: "Moldave", viewValue: 'Moldave' },
    { value: "Monegasque", viewValue: 'Monegasque' },
    { value: "Mongole", viewValue: 'Mongole' },
    { value: "Montenegrine", viewValue: 'Montenegrine' },
    { value: "Mozambicaine", viewValue: 'Mozambicaine' },
    { value: "Namibienne", viewValue: 'Namibienne' },
    { value: "Nauruane", viewValue: 'Nauruane' },
    { value: "Néerlandaise", viewValue: 'Neerlandaise' },
    { value: "Neo-zelandaise", viewValue: 'Neo-zelandaise' },
    { value: "Nepalaise", viewValue: 'Nepalaise' },
    { value: "Nicaraguayenne", viewValue: 'Nicaraguayenne' },
    { value: "Nigeriane", viewValue: 'Nigeriane' },
    { value: "Nigerienne", viewValue: 'Nigerienne' },
    { value: "Nord-coréenne", viewValue: 'Nord-coréenne' },
    { value: "Norvegienne", viewValue: 'Norvegienne' },
    { value: "Omanaise", viewValue: 'Omanaise' },
    { value: "Ougandaise", viewValue: 'Ougandaise' },
    { value: "Ouzbeke", viewValue: 'Ouzbeke' },
    { value: "Pakistanaise", viewValue: 'Pakistanaise' },
    { value: "Palau", viewValue: 'Palau' },
    { value: "Palestinienne", viewValue: 'Palestinienne' },
    { value: "Panameenne", viewValue: 'Panameenne' },
    { value: "Papouane-neoguineenne", viewValue: 'Papouane-neoguineenne' },
    { value: "Paraguayenne", viewValue: 'Paraguayenne' },
    { value: "Peruvienne", viewValue: 'Peruvienne' },
    { value: "Philippine", viewValue: 'Philippine' },
    { value: "Polonaise", viewValue: 'Polonaise' },
    { value: "Portoricaine", viewValue: 'Portoricaine' },
    { value: "Portugaise", viewValue: 'Portugaise' },
    { value: "Qatarienne", viewValue: 'Qatarienne' },
    { value: "Roumaine", viewValue: 'Roumaine' },
    { value: "Russe", viewValue: 'Russe' },
    { value: "Rwandaise", viewValue: 'Rwandaise' },
    { value: "Saint-lucienne", viewValue: 'Saint-lucienne' },
    { value: "Saint-marinaise", viewValue: 'Saint-marinaise' },
    { value: "Saint-vincentaise-et-grenadine", viewValue: 'Saint-vincentaise-et-grenadine' },
    { value: "Salomonaise", viewValue: 'Salomonaise' },
    { value: "Salvadorienne", viewValue: 'Salvadorienne' },
    { value: "Samoane", viewValue: 'Samoane' },
    { value: "Santomeenne", viewValue: 'Santomeenne' },
    { value: "Saoudienne", viewValue: 'Saoudienne' },
    { value: "Senegalaise", viewValue: 'Senegalaise' },
    { value: "Serbe", viewValue: 'Serbe' },
    { value: "Seychelloise", viewValue: 'Seychelloise' },
    { value: "Sierra-leonaise", viewValue: 'Sierra-leonaise' },
    { value: "Singapourienne", viewValue: 'Singapourienne' },
    { value: "Slovaque", viewValue: 'Slovaque' },
    { value: "Slovene", viewValue: 'Slovene' },
    { value: "Somalienne", viewValue: 'Somalienne' },
    { value: "Soudanaise", viewValue: 'Soudanaise' },
    { value: "Sri-lankaise", viewValue: 'Sri-lankaise' },
    { value: "Sud-africaine", viewValue: 'Sud-africaine' },
    { value: "Sud-coréenne", viewValue: 'Sud-coréenne' },
    { value: "Suedoise", viewValue: 'Suedoise' },
    { value: "Suisse", viewValue: 'Suisse' },
    { value: "Surinamaise", viewValue: 'Surinamaise' },
    { value: "Swazie", viewValue: 'Swazie' },
    { value: "Syrienne", viewValue: 'Syrienne' },
    { value: "Tadjike", viewValue: 'Tadjike' },
    { value: "Taiwanaise", viewValue: 'Taiwanaise' },
    { value: "Tanzanienne", viewValue: 'Tanzanienne' },
    { value: "Tchadienne", viewValue: 'Tchadienne' },
    { value: "Tcheque", viewValue: 'Tcheque' },
    { value: "Thaïlandaise", viewValue: 'Thaïlandaise' },
    { value: "Togolaise", viewValue: 'Togolaise' },
    { value: "Tonguienne", viewValue: 'Tonguienne' },
    { value: "Trinidadienne", viewValue: 'Trinidadienne' },
    { value: "Tunisienne", viewValue: 'Tunisienne' },
    { value: "Turkmene", viewValue: 'Turkmene' },
    { value: "Turque", viewValue: 'Turque' },
    { value: "Tuvaluane", viewValue: 'Tuvaluane' },
    { value: "Ukrainienne", viewValue: 'Ukrainienne' },
    { value: "Uruguayenne", viewValue: 'Uruguayenne' },
    { value: "Vanuatuane", viewValue: 'Vanuatuane' },
    { value: "Venezuelienne", viewValue: 'Venezuelienne' },
    { value: "Vietnamienne", viewValue: 'Vietnamienne' },
    { value: "Yemenite", viewValue: 'Yemenite' },
    { value: "Zambienne", viewValue: 'Zambienne' },
    { value: "Zimbabweenne", viewValue: 'Zimbabweenne' },

  ],

  nationalites_UE: [
    { value: "Allemande", viewValue: 'Allemande' },
    { value: "Autrichienne", viewValue: 'Autrichienne' },
    { value: "Belge", viewValue: 'Belge' },
    { value: "Danoise", viewValue: 'Danoise' },
    { value: "Espagnole", viewValue: 'Espagnole' },
    { value: "Estonienne", viewValue: 'Estonienne' },
    { value: "Finlandaise", viewValue: 'Finlandaise' },
    { value: "Française", viewValue: 'Française' },
    { value: "Grèce", viewValue: 'Grèce' },
    { value: "Hongrie", viewValue: 'Hongrie' },
    { value: "Islandaise", viewValue: 'Islandaise' },
    { value: "Italienne", viewValue: 'Italienne' },
    { value: "Liechtensteinoise", viewValue: 'Liechtensteinoise' },
    { value: "Lituanienne", viewValue: 'Lituanienne' },
    { value: "Lettone", viewValue: 'Lettone' },
    { value: "Luxembourgeoise", viewValue: 'Luxembourgeoise' },
    { value: "Maltaise", viewValue: 'Maltaise' },
    { value: "Norvegienne", viewValue: 'Norvegienne' },
    { value: "Néerlandaise", viewValue: 'Néerlandaise' },
    { value: "Polonaise", viewValue: 'Polonaise' },
    { value: "Portugaise", viewValue: 'Portugaise' },
    { value: "Slovaque", viewValue: 'Slovaque' },
    { value: "Slovene", viewValue: 'Slovene' },
    { value: "Suedoise", viewValue: 'Suedoise' },
    { value: "Suisse", viewValue: 'Suisse' },
    { value: "Tcheque", viewValue: 'Tcheque' },
  ],

  nationalitesEDU: [
    { value: "Afghane", viewValue: 'Afghane' },
    { value: "Albanaise", viewValue: 'Albanaise' },
    { value: "Algerienne", viewValue: 'Algerienne' },
    { value: "Americaine", viewValue: 'Americaine' },
    { value: "Andorrane", viewValue: 'Andorrane' },
    { value: "Angolaise", viewValue: 'Angolaise' },
    { value: "Antiguaise et barbudienne", viewValue: 'Antiguaise et barbudienne' },
    { value: "Argentine", viewValue: 'Argentine' },
    { value: "Australienne", viewValue: 'Australienne' },
    { value: "Azerbaïdjanaise", viewValue: 'Azerbaïdjanaise' },
    { value: "Bahamienne", viewValue: 'Bahamienne' },
    { value: "Bahreinienne", viewValue: 'Bahreinienne' },
    { value: "Bangladaise", viewValue: 'Bangladaise' },
    { value: "Barbadienne", viewValue: 'Barbadienne' },
    { value: "Belizienne", viewValue: 'Belizienne' },
    { value: "Beninoise", viewValue: 'Beninoise' },
    { value: "Bhoutanaise", viewValue: 'Bhoutanaise' },
    { value: "Bielorusse", viewValue: 'Bielorusse' },
    { value: "Birmane", viewValue: 'Birmane' },
    { value: "Bissau-Guinéenne", viewValue: 'Bissau-Guinéenne' },
    { value: "Bolivienne", viewValue: 'Bolivienne' },
    { value: "Bosnienne", viewValue: 'Bosnienne' },
    { value: "Botswanaise", viewValue: 'Botswanaise' },
    { value: "Britannique", viewValue: 'Britannique' },
    { value: "Bruneienne", viewValue: 'Bruneienne' },
    { value: "Bulgare", viewValue: 'Bulgare' },
    { value: "Burkinabe", viewValue: 'Burkinabe' },
    { value: "Burundaise", viewValue: 'Burundaise' },
    { value: "Cambodgienne", viewValue: 'Cambodgienne' },
    { value: "Camerounaise", viewValue: 'Camerounaise' },
    { value: "Canadienne", viewValue: 'Canadienne' },
    { value: "Cap-verdienne", viewValue: 'Cap-verdienne' },
    { value: "Centrafricaine", viewValue: 'Centrafricaine' },
    { value: "Chilienne", viewValue: 'Chilienne' },
    { value: "Chinoise", viewValue: 'Chinoise' },
    { value: "Chypriote", viewValue: 'Chypriote' },
    { value: "Colombienne", viewValue: 'Colombienne' },
    { value: "Comorienne", viewValue: 'Comorienne' },
    { value: "Congolaise", viewValue: 'Congolaise' },
    { value: "Costaricaine", viewValue: 'Costaricaine' },
    { value: "Croate", viewValue: 'Croate' },
    { value: "Cubaine", viewValue: 'Cubaine' },
    { value: "Djiboutienne", viewValue: 'Djiboutienne' },
    { value: "Dominicaine", viewValue: 'Dominicaine' },
    { value: "Dominiquaise", viewValue: 'Dominiquaise' },
    { value: "Egyptienne", viewValue: 'Egyptienne' },
    { value: "Emirienne", viewValue: 'Emirienne' },
    { value: "Equato-guineenne", viewValue: 'Equato-guineenne' },
    { value: "Equatorienne", viewValue: 'Equatorienne' },
    { value: "Erythreenne", viewValue: 'Erythreenne' },
    { value: "Est-timoraise", viewValue: 'Est-timoraise' },
    { value: "Ethiopienne", viewValue: 'Ethiopienne' },
    { value: "Fidjienne", viewValue: 'Fidjienne' },
    { value: "Gabonaise", viewValue: 'Gabonaise' },
    { value: "Gambienne", viewValue: 'Gambienne' },
    { value: "Georgienne", viewValue: 'Georgienne' },
    { value: "Ghaneenne", viewValue: 'Ghaneenne' },
    { value: "Grenadienne", viewValue: 'Grenadienne' },
    { value: "Guatemalteque", viewValue: 'Guatemalteque' },
    { value: "Guineenne", viewValue: 'Guineenne' },
    { value: "Guyanienne", viewValue: 'Guyanienne' },
    { value: "Grecque", viewValue: 'Grecque' },
    { value: "Haïtienne", viewValue: 'Haïtienne' },
    { value: "Hellenique", viewValue: 'Hellenique' },
    { value: "Hondurienne", viewValue: 'Hondurienne' },
    { value: "Hongroise", viewValue: 'Hongroise' },
    { value: "Indienne", viewValue: 'Indienne' },
    { value: "Indonesienne", viewValue: 'Indonesienne' },
    { value: "Irakienne", viewValue: 'Irakienne' },
    { value: "Irlandaise", viewValue: 'Irlandaise' },
    { value: "Ivoirienne", viewValue: 'Ivoirienne' },
    { value: "Jamaïcaine", viewValue: 'Jamaïcaine' },
    { value: "Japonaise", viewValue: 'Japonaise' },
    { value: "Jordanienne", viewValue: 'Jordanienne' },
    { value: "Kazakhstanaise", viewValue: 'Kazakhstanaise' },
    { value: "Kenyane", viewValue: 'Kenyane' },
    { value: "Kirghize", viewValue: 'Kirghize' },
    { value: "Kiribatienne", viewValue: 'Kiribatienne' },
    { value: "Kittitienne-et-nevicienne", viewValue: 'Kittitienne-et-nevicienne' },
    { value: "Kossovienne", viewValue: 'Kossovienne' },
    { value: "Koweitienne", viewValue: 'Koweitienne' },
    { value: "Laotienne", viewValue: 'Laotienne' },
    { value: "Lesothane", viewValue: 'Lesothane' },
    { value: "Libanaise", viewValue: 'Libanaise' },
    { value: "Liberienne", viewValue: 'Liberienne' },
    { value: "Libyenne", viewValue: 'Libyenne' },
    { value: "Macedonienne", viewValue: 'Macedonienne' },
    { value: "Malaisienne", viewValue: 'Malaisienne' },
    { value: "Malawienne", viewValue: 'Malawienne' },
    { value: "Maldivienne", viewValue: 'Maldivienne' },
    { value: "Malgache", viewValue: 'Malgache' },
    { value: "Malienne", viewValue: 'Malienne' },
    { value: "Marocaine", viewValue: 'Marocaine' },
    { value: "Marshallaise", viewValue: 'Marshallaise' },
    { value: "Mauricienne", viewValue: 'Mauricienne' },
    { value: "Mauritanienne", viewValue: 'Mauritanienne' },
    { value: "Mexicaine", viewValue: 'Mexicaine' },
    { value: "Micronesienne", viewValue: 'Micronesienne' },
    { value: "Moldave", viewValue: 'Moldave' },
    { value: "Monegasque", viewValue: 'Monegasque' },
    { value: "Mongole", viewValue: 'Mongole' },
    { value: "Montenegrine", viewValue: 'Montenegrine' },
    { value: "Mozambicaine", viewValue: 'Mozambicaine' },
    { value: "Namibienne", viewValue: 'Namibienne' },
    { value: "Nauruane", viewValue: 'Nauruane' },
    { value: "Neo-zelandaise", viewValue: 'Neo-zelandaise' },
    { value: "Nepalaise", viewValue: 'Nepalaise' },
    { value: "Nicaraguayenne", viewValue: 'Nicaraguayenne' },
    { value: "Nigeriane", viewValue: 'Nigeriane' },
    { value: "Nigerienne", viewValue: 'Nigerienne' },
    { value: "Nord-coréenne", viewValue: 'Nord-coréenne' },
    { value: "Omanaise", viewValue: 'Omanaise' },
    { value: "Ougandaise", viewValue: 'Ougandaise' },
    { value: "Ouzbeke", viewValue: 'Ouzbeke' },
    { value: "Pakistanaise", viewValue: 'Pakistanaise' },
    { value: "Palau", viewValue: 'Palau' },
    { value: "Palestinienne", viewValue: 'Palestinienne' },
    { value: "Panameenne", viewValue: 'Panameenne' },
    { value: "Papouane-neoguineenne", viewValue: 'Papouane-neoguineenne' },
    { value: "Paraguayenne", viewValue: 'Paraguayenne' },
    { value: "Peruvienne", viewValue: 'Peruvienne' },
    { value: "Philippine", viewValue: 'Philippine' },
    { value: "Portoricaine", viewValue: 'Portoricaine' },
    { value: "Qatarienne", viewValue: 'Qatarienne' },
    { value: "Roumaine", viewValue: 'Roumaine' },
    { value: "Russe", viewValue: 'Russe' },
    { value: "Rwandaise", viewValue: 'Rwandaise' },
    { value: "Saint-lucienne", viewValue: 'Saint-lucienne' },
    { value: "Saint-marinaise", viewValue: 'Saint-marinaise' },
    { value: "Saint-vincentaise-et-grenadine", viewValue: 'Saint-vincentaise-et-grenadine' },
    { value: "Salomonaise", viewValue: 'Salomonaise' },
    { value: "Salvadorienne", viewValue: 'Salvadorienne' },
    { value: "Samoane", viewValue: 'Samoane' },
    { value: "Santomeenne", viewValue: 'Santomeenne' },
    { value: "Saoudienne", viewValue: 'Saoudienne' },
    { value: "Senegalaise", viewValue: 'Senegalaise' },
    { value: "Serbe", viewValue: 'Serbe' },
    { value: "Seychelloise", viewValue: 'Seychelloise' },
    { value: "Sierra-leonaise", viewValue: 'Sierra-leonaise' },
    { value: "Singapourienne", viewValue: 'Singapourienne' },
    { value: "Somalienne", viewValue: 'Somalienne' },
    { value: "Soudanaise", viewValue: 'Soudanaise' },
    { value: "Sri-lankaise", viewValue: 'Sri-lankaise' },
    { value: "Sud-africaine", viewValue: 'Sud-africaine' },
    { value: "Sud-coréenne", viewValue: 'Sud-coréenne' },
    { value: "Surinamaise", viewValue: 'Surinamaise' },
    { value: "Swazie", viewValue: 'Swazie' },
    { value: "Syrienne", viewValue: 'Syrienne' },
    { value: "Tadjike", viewValue: 'Tadjike' },
    { value: "Taiwanaise", viewValue: 'Taiwanaise' },
    { value: "Tanzanienne", viewValue: 'Tanzanienne' },
    { value: "Tchadienne", viewValue: 'Tchadienne' },
    { value: "Thaïlandaise", viewValue: 'Thaïlandaise' },
    { value: "Togolaise", viewValue: 'Togolaise' },
    { value: "Tonguienne", viewValue: 'Tonguienne' },
    { value: "Trinidadienne", viewValue: 'Trinidadienne' },
    { value: "Tunisienne", viewValue: 'Tunisienne' },
    { value: "Turkmene", viewValue: 'Turkmene' },
    { value: "Turque", viewValue: 'Turque' },
    { value: "Tuvaluane", viewValue: 'Tuvaluane' },
    { value: "Ukrainienne", viewValue: 'Ukrainienne' },
    { value: "Uruguayenne", viewValue: 'Uruguayenne' },
    { value: "Vanuatuane", viewValue: 'Vanuatuane' },
    { value: "Venezuelienne", viewValue: 'Venezuelienne' },
    { value: "Vietnamienne", viewValue: 'Vietnamienne' },
    { value: "Yemenite", viewValue: 'Yemenite' },
    { value: "Zambienne", viewValue: 'Zambienne' },
    { value: "Zimbabweenne", viewValue: 'Zimbabweenne' },

  ],
  entreprises: [
    { value: "ESTYA Education", viewValue: 'ESTYA Education' },
    { value: "ESTYA Training", viewValue: 'ESTYA Training' },
    { value: "Académie des gouvernantes", viewValue: 'Académie des gouvernantes' },

  ],
  status: [
    { label: "À traiter", value: 'À traiter' },
    { label: "En cours de traitement", value: 'En cours de traitement' },
    { label: "En attente de retour", value: 'En attente de retour' },
    { label: "Clôturé", value: 'Clôturé' }
  ],

  etat_annee: [
    { label: "Nouvelle", value: 'Nouvelle' },
    { label: "Active", value: 'Active' },
    { label: "Archivée", value: 'Archivée' },
  ],

  programeFrDropdown:
  [
    { value: "BTS MCO - Management Commercial Opérationnel" },
    { value: "BTS NDRC - Négociation et Digitalisation de la Relation Client" },
    { value: "BTS CG - Comptabilité et Gestion" },
    { value: "RNCP CI - Commerce International" },
    { value: "RNCP NTC - Négociateur Technico-Commercial" },
    { value: "RNCP - Chargé de Développement Marketing et Commercial" },
    { value: "RNCP - IA - Ingénieur d'Affaires" },
    { value: "RNCP Management et Commerce International" },
    { value: "BTS Services Informatique aux Organisations - SISR" },
    { value: "BTS Services Informatique aux Organisations - SLAM" },
    { value: "RNCP TSSR - Technicien Supérieur Systèmes et Réseaux" },
    { value: "RNCP DWWM - Développeur Web & Web Mobile" },
    { value: "RNCP AIS - Administrateur d'Infrastructures Sécurisées" },
    { value: "RNCP CDA - Concepteur Développeur d'Applications" },
    { value: "RNCP MPI Big Data - Expert IT – Applications Intelligentes & Big Data" },
    { value: "RNCP MPI CyberSecurité - Expert IT – Cybersécurité et Haute Disponibilité" },
    { value: "BTS Collaborateur Juriste Notarial" },
    { value: "RNCP - Assistant Ressources Humaines" },
    { value: "RNCP- Management des Ressources Humaines" },
    { value: "BTS SPSSS - Services et Prestations des Secteurs Sanitaire et Social" },
    { value: "RNCP - BIM modeleur du Bâtiement" },
    { value: "RNCP - BIM modeleur du Coordinateur BIM du Bâtiment" },
  ],

programEnDropdown:
  [
    { value: "Level 3 - Foundation Diploma for Higher Education Studies" },
    { value: "Level 4 - Business Management " },
    { value: "Level 4 - Information Technology " },
    { value: "Level 4 - Tourism and Hospitality Management" },
    { value: "Level 4 - Health and Social care Management" },
    { value: "Level 5 - Business Management" },
    { value: "Level 5 - Information Technology" },
    { value: "Level 7 - Project Management" },
    { value: "Level 7 - Tourism and Hospitality Management" },
    { value: "Level 7 - Health and Social care Management", }

  ],
  ADGprogrameFrDropdown:
  [
        { value: "GH - Gouvernant(e) en hôtellerie - Titre RNCP - Niveau 4" },
        { value: "CAP AEPE – CAP Accompagnant Educatif Petite Enfance" },
        { value: "GM - Gouvernant(e) de maison - Diplôme maison" },
        { value: "BTS MCO - Management Commercial Operationnel" },
        { value: "BTS NDRC - Négociation et Digitalisation de la Relation Client" },
        { value: "BTS GPME" },
        { value: "BTS CI - Commerce International" },
        { value: "NTC - Négociateur Technico-Commercial (Titre Professionnel)" },
        { value: "Chargé de gestion commerciale - Spécialité service commercial" },
        { value: "IA - Ingénieur d'Affaires" },
        { value: "Management et Stratégie d’Entreprise " },
        { value: "BTS SIO - Services Informatiques aux Organisations" },
        { value: "TSSR - Technicien Supérieur Systèmes et Réseaux (Titre professionnel)" },
        { value: "DWWM - Développeur Web et Web Mobile (Titre professionnel)" },
        { value: "AIS - Administrateur d’Infrastructures Sécurisées" },
        { value: "CDA - Concepteur Développeur d’Applications" },
        { value: "EXPERT IT - CYBERSÉCURITÉ ET HAUTE DISPONIBILITÉ " },
        { value: "EXPERT IT - APPLICATIONS INTELLIGENTES & BIG DATA " },
        { value: "BTS CJN  - Collaborateur Juriste Notarial" },
        { value: "BTS CG - Comptabilité et Gestion" },
        { value: "ARH : Assistant Ressources Humaines (Titre Professionnel)" },
        { value: "BIM Modeleur du Bâtiment (Titre Professionnel)" },
        { value: "Coordinateur BIM du Bâtiment" },
        { value: "BTS SPSSS - Services et Prestations dans les Secteurs Sanitaire et Social" },
        { value: "Formations continues IPERIA" }

  ],
};
/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
