// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  origin: "http://localhost:3000/soc/",
  key: "6abdfb04243e096a4a51b46c8f3d4b32",
  User: null,
  clientId: "25314c92-c369-4273-b8b0-5b3d2096ed05",

  fr: {
    firstDayOfWeek: 0,
    dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
    dayNamesShort: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
    monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
    monthNamesShort: ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Jun', 'Jul', 'Aoû', 'Sep', 'Oct', 'Nov', 'Déc'],
    today: 'Aujourdhui',
    clear: 'Clear',
    dateFormat: 'dd-mm-yy',
    weekHeader: 'sem'
  },
  colorPaletteGreen: [
    "#b7de6a",
    "#486b03",
    "#79a324",
    "#cafa6b",
    "#c1db8c",
    "#6e9422",
    "#abb39b",
    "#B2C787",
    "#8c9678",
    "#b6e657"
  ],
  role: [
    { value: 'Agent' },
    { value: 'Responsable' }
  ],

  typeUser: [
    { value: "Etudiant",},
    { value: "Salarié"}, 
    { value: "Alternant/Stagiaire"}
  ],

  schoolList: [
    { value: 'ESTYA'},
    { value: 'ADG Education'},
    { value: 'ESPIC'},
    { value: 'J\'ai besoin d\'orientation'},
  ],

  formations:[

    {value:"BTS MCO"},
    {value:"BTS NDR"},
    {value:"RNCP MUM"},
    {value:"RNCP NTC"},
    {value:"RNCP MERCD"},
    {value:"RNCP CMD"},
    {value:"RNCP MCI"},
    {value:"RNCP MCI CI"},
    {value:"RNCP MCI IA"},
    {value:"BTS SIO"},
    {value:"BTS WEB"},
    {value:"RNCP Réseaux"},
    {value:"RNCP Développeur"},
    {value:"RNCP AIS"},
    {value:"MPI Big Data"},
    {value:"MPI CyberSecurité"},
    {value:"RNCP ARH"},
    {value:"BTS Assurance"},
    {value:"BTS Banque"},
    {value:"BTS CG"},
    {value:"RNCP GCF"},
    {value:"BTS PME"},
    {value:"BTS Notariat"},
    {value:"DCG"},
    {value:"DCGS"},
    {value:"RNCP MRH"},
    {value:"RNCP BIM"},
    {value:"BTS MEC"},
    {value:"Bachelor BIM"},
    {value:"BTS Hôtellerie-Restauration"},
    {value:"BTS SPSSS"},
    {value:"RNCP RET"},

  ],
  campus: [
    { value: "France - Paris" },
    { value: "France - Montpellier" },
    { value: "UAE - Dubai" },
    { value: "Canada - Montréal" },
    { value: "Angleterre - Londres" },
    { value: "Tunisie - Tunis" },
    { value: "Espagne - Valencia"},
    { value: "Malte"},
    { value: "Grèce"},
    { value: "Maroc - Rabat"},
    { value: "En Ligne (365)" },
  ],

  programme : [
    { value: "Programme Français"},
    { value: "Programme Anglais"},
  ],

  entreprisesList: [
    { value: "Elitelabs" },
    { value: "ESTYA" },
    { value: "ADG" },
    { value: "Autre" }
  ],

  civilite: [
    { id: 1, value: 'Monsieur', viewValue: 'Mr' },
    { id: 2, value: 'Madame', viewValue: 'Mme' },
    { id: 3, value: 'Autre', viewValue: 'Autre' },
  ],

  niveau_academic: [
    { id: 1, value:'Pré-bac', viewValue: 'Pré-bac'},
    { id: 2, value: 'Bac+2', viewValue: 'Bac+2'},
    { id: 3, value: 'Bac+3', viewValue: 'Bac+3'},
    { id: 4, value: 'Bac+4', viewValue: 'Bac+4'},
    { id: 5, value: 'Bac+5', viewValue: 'Bac+5'},
  ],

  statut_actuel : [
    { id: 1, value: 'Etudiant', viewValue: 'Etudiant'},
    { id: 2, value: 'Salarié', viewValue: 'Salarié'},
    { id: 3, value: 'Au chômage', viewValue: 'Au chômage'},
    { id: 4, value: 'Autre', viewValue: 'Autre'},
  ],

  profil: [
    { id: 1, value: 'Salarié', viewValue: 'Salarié' },
    { id: 2, value: 'Apprenti', viewValue: 'Apprenti' },
    { id: 3, value: 'Demandeur d\'emploi', viewValue: 'Demandeur d\'emploi' },
    { id: 4, value: 'Paticulier', viewValue: 'Paticulier' },
    { id: 5, value: 'Autre', viewValue: 'Autre' },
    { id: 6, value: 'Contrat de professionnalisation', viewValue: 'Contrat de professionnalisation' },
    { id: 7, value: 'Contrat d\'apprentissage', viewValue: 'Contrat d\'apprentissage' },
  ],

  statut: [
    { value: 'En cours de traitement', viewValue: 'En cours de traitement' },
    { value: 'En attente d\'une réponse', viewValue: 'En attente d\'une réponse' },
    { value: 'Traité', viewValue: 'Traité' },
  ],

  sujetTicketing: [
    { value: "Attestation d'emploi et Certificat de travail", viewValue: "Attestation d'emploi et Certificat de travail" },
    { value: "Déclarer un arrêt de travail", viewValue: 'Déclarer un arrêt de travail' },
    { value: "Renouvellement de contrat", viewValue: "Renouvellement de contrat" },
    { value: "Demander ses BDS", viewValue: "Demander ses BDS" },
    { value: "Démission", viewValue: "Démission" },
    { value: "Domiciliation de salaire", viewValue: "Domiciliation de salaire" },
    { value: "Attestation de salaire", viewValue: "Attestation de salaire" },
    { value: "Avenant de contrat", viewValue: "Avenant de contrat" },
    { value: "Ticket resto", viewValue: "Ticket resto" },
    { value: "Avenant de contrat", viewValue: "Avenant de contrat" },
    { value: "Prévoyance et mutuelle", viewValue: "Prévoyance et mutuelle" },

  ],

  pays: [ //default [76]
  { value: 'Aruba', viewValue: 'Aruba' },
  { value: 'Afghanistan', viewValue: 'Afghanistan' },
  { value: 'Angola', viewValue: 'Angola'},
  { value: 'Anguilla', viewValue: 'Anguilla'},
  { value: 'Ahvenanmaa', viewValue: 'Ahvenanmaa'},
  { value: 'Albanie', viewValue: 'Albanie'},
  { value: 'Andorre', viewValue: 'Andorre'},
  { value: 'Émirats arabes unis', viewValue: 'Émirats arabes unis'},
  { value: 'Argentine', viewValue: 'Argentine'},
  { value: 'Arménie', viewValue: 'Arménie'},
  { value: 'Samoa américaines', viewValue:'Samoa américaines' },
  { value: 'Antarctique', viewValue: 'Antarctique'},
  { value: 'Terres australes et antarctiques françaises', viewValue: 'Terres australes et antarctiques françaises'},
  { value: 'Antigua-et-Barbuda', viewValue: 'Antigua-et-Barbuda'},
  { value: 'Australie', viewValue:'Australie' },
  { value: 'Autriche', viewValue: 'Autriche'},
  { value: 'Azerbaïdjan', viewValue: 'Azerbaïdjan'},
  { value: 'Burundi', viewValue: 'Burundi'},
  { value: 'Belgique', viewValue: 'Belgique'},
  { value: 'Bénin', viewValue: 'Bénin'},
  { value: 'Burkina Faso', viewValue: 'Burkina Faso'},
  { value: 'Bangladesh', viewValue: 'Bangladesh'},
  { value: 'Bulgarie', viewValue: 'Bulgarie'},
  { value: 'Bahreïn', viewValue: 'Bahreïn'},
  { value: 'Bahamas', viewValue: 'Bahamas'},
  { value: 'Bosnie-Herzégovine', viewValue: 'Bosnie-Herzégovine'},
  { value: 'Saint-Barthélemy', viewValue: 'Saint-Barthélemy'},
  { value: 'Sainte-Hélène, Ascension et Tristan da Cunha', viewValue: 'Sainte-Hélène, Ascension et Tristan da Cunha'},
  { value: 'Biélorussie', viewValue: 'Biélorussie'},
  { value: 'Belize', viewValue: 'Belize'},
  { value: 'Bermudes', viewValue: 'Bermudes'},
  { value: 'Bolivie', viewValue: 'Bolivie'},
  { value: 'Pays-Bas caribéens', viewValue: 'Pays-Bas caribéens'},
  { value: 'Brésil', viewValue: 'Brésil'},
  { value: 'Barbade', viewValue: 'Barbade'},
  { value: 'Brunei', viewValue: 'Brunei'},
  { value: 'Bhoutan', viewValue: 'Bhoutan'},
  { value: 'Île Bouvet', viewValue: 'Île Bouvet'},
  { value: 'Botswana', viewValue: 'Botswana'},
  { value: 'République centrafricaine', viewValue: 'République centrafricaine' },
  { value: 'Canada', viewValue:'Canada' },
  { value: 'Îles Cocos', viewValue:'Îles Cocos' },
  { value: 'Suisse', viewValue:'Suisse' },
  { value: 'Chili', viewValue: 'Chili'},
  { value: 'Chine', viewValue: 'Chine'},
  { value: 'Côte d\'Ivoire', viewValue:'Côte d\'Ivoire' },
  { value: 'Cameroun', viewValue:'Cameroun' },
  { value: 'Congo (Rép. dém.)', viewValue: 'Congo (Rép. dém.)' },
  { value: 'Congo', viewValue: 'Congo'},
  { value: 'Îles Cook', viewValue: 'Îles Cook'},
  { value: 'Colombie', viewValue: 'Colombie'},
  { value: 'Comores', viewValue: 'Comores'},
  { value: 'Îles du Cap-Vert', viewValue:'Îles du Cap-Vert' },
  { value: 'Costa Rica', viewValue: 'Costa Rica'},
  { value: 'Cuba', viewValue: 'Cuba'},
  { value: 'Curaçao', viewValue: 'Curaçao'},
  { value: 'Île Christmas', viewValue: 'Île Christmas'},
  { value: 'Îles Caïmans', viewValue: 'Îles Caïmans'},
  { value: 'Chypre', viewValue: 'Chypre'},
  { value: 'Tchéquie', viewValue: 'Tchéquie'},
  { value: 'Allemagne', viewValue: 'Allemagne'},
  { value: 'Djibouti', viewValue: 'Djibouti'},
  { value: 'Dominique', viewValue: 'Dominique'},
  { value: 'Danemark', viewValue: 'Danemark'},
  { value: 'République dominicaine', viewValue: 'République dominicaine'},
  { value: 'Algérie', viewValue: 'Algérie'},
  { value: 'Équateur', viewValue: 'Équateur'},
  { value: 'Égypte', viewValue: 'Égypte'},
  { value: 'Érythrée', viewValue: 'Érythrée'},
  { value: 'Sahara Occidental', viewValue: 'Sahara Occidental'},
  { value: 'Espagne', viewValue:'Espagne' },
  { value: 'Estonie', viewValue: 'Estonie'},
  { value: 'Éthiopie', viewValue: 'Éthiopie'},
  { value: 'Finlande', viewValue: 'Finlande'},
  { value: 'Fidji', viewValue:'Fidji' },
  { value: 'Îles Malouines', viewValue:'Îles Malouines' },
  { value: 'France', viewValue: 'France'},
  { value: 'Îles Féroé', viewValue: 'Îles Féroé'},
  { value: 'Micronésie', viewValue:'Micronésie' },
  { value: 'Gabon', viewValue: 'Gabon'},
  { value: 'Royaume-Uni', viewValue:'Royaume-Uni' },
  { value: 'Géorgie', viewValue:'Géorgie' },
  { value: 'Guernesey', viewValue: 'Guernesey'},
  { value: 'Ghana', viewValue: 'Ghana'},
  { value: 'Gibraltar', viewValue: 'Gibraltar'},
  { value: 'Guinée', viewValue: 'Guinée'},
  { value: 'Guadeloupe', viewValue: 'Guadeloupe'},
  { value: 'Gambie', viewValue: 'Gambie'},
  { value: 'Guinée-Bissau', viewValue: 'Guinée-Bissau'},
  { value: 'Guinée équatoriale', viewValue: 'Guinée équatoriale'},
  { value: 'Grèce', viewValue: 'Grèce'},
  { value: 'Grenade', viewValue: 'Grenade'},
  { value: 'Groenland', viewValue: 'Groenland'},
  { value: 'Guatemala', viewValue: 'Guatemala'},
  { value: 'Guyane', viewValue: 'Guyane'},
  { value: 'Guam', viewValue: 'Guam'},
  { value: 'Guyana', viewValue: 'Guyana'},
  { value: 'Hong Kong', viewValue: 'Hong Kong'},
  { value: 'Îles Heard-et-MacDonald', viewValue: 'Îles Heard-et-MacDonald'},
  { value: 'Honduras', viewValue:'Honduras' },
  { value: 'Croatie', viewValue: 'Croatie'},
  { value: 'Haïti', viewValue: 'Haïti'},
  { value: 'Hongrie', viewValue: 'Hongrie'},
  { value: 'Indonésie', viewValue: 'Indonésie'},
  { value: 'Île de Man' , viewValue:'Île de Man'},
  { value: 'Inde', viewValue: 'Inde'},
  { value: 'Territoire britannique de l\'océan Indien', viewValue:'Territoire britannique de l\'océan Indien' },
  { value: 'Irlande', viewValue: 'Irlande'},
  { value: 'Iran', viewValue: 'Iran'},
  { value: 'Irak', viewValue: 'Irak'},
  { value: 'Islande', viewValue:'Islande' },
  { value: 'Israël', viewValue: 'Israël'},
  { value: 'Italie', viewValue: 'Italie'},
  { value: 'Jamaïque' , viewValue:'Jamaïque'},
  { value: 'Jersey', viewValue: 'Jersey'},
  { value: 'Jordanie', viewValue: 'Jordanie'},
  { value: 'Japon', viewValue: 'Japon'},
  { value: 'Kazakhstan', viewValue: 'Kazakhstan'},
  { value: 'Kenya', viewValue: 'Kenya'},
  { value: 'Kirghizistan', viewValue: 'Kirghizistan'},
  { value: 'Cambodge', viewValue:'Cambodge' },
  { value: 'Kiribati', viewValue: 'Kiribati'},
  { value: 'Saint-Christophe-et-Niévès', viewValue: 'Saint-Christophe-et-Niévès'},
  { value: 'Corée du Sud', viewValue: 'Corée du Sud'},
  { value: 'Kosovo', viewValue: 'Kosovo'},
  { value: 'Koweït', viewValue: 'Koweït'},
  { value: 'Laos', viewValue: 'Laos'},
  { value: 'Liban', viewValue: 'Liban'},
  { value: 'Liberia' , viewValue:'Liberia'},
  { value: 'Libye', viewValue:'Libye' },
  { value: 'Sainte-Lucie', viewValue:'Sainte-Lucie' },
  { value: 'Liechtenstein', viewValue: 'Liechtenstein'},
  { value: 'Sri Lanka', viewValue: 'Sri Lanka'},
  { value: 'Lesotho', viewValue: 'Lesotho'},
  { value: 'Lituanie' , viewValue:'Lituanie'},
  { value: 'Luxembourg', viewValue: 'Luxembourg'},
  { value: 'Lettonie', viewValue: 'Lettonie'},
  { value: 'Macao', viewValue: 'Macao'},
  { value: 'Saint-Martin', viewValue: 'Saint-Martin'},
  { value: 'Maroc', viewValue:'Maroc' },
  { value: 'Monaco', viewValue: 'Monaco'},
  { value: 'Moldavie', viewValue: 'Moldavie'},
  { value: 'Madagascar', viewValue: 'Madagascar'},
  { value: 'Maldives', viewValue: 'Maldives'},
  { value: 'Mexique', viewValue: 'Mexique'},
  { value: 'Îles Marshall', viewValue: 'Îles Marshall'},
  { value: 'Macédoine', viewValue: 'Macédoine'},
  { value: 'Mali', viewValue: 'Mali'},
  { value: 'Malte', viewValue: 'Malte'},
  { value: 'Birmanie', viewValue: 'Birmanie'},
  { value: 'Monténégro', viewValue: 'Monténégro'},
  { value: 'Mongolie', viewValue: 'Mongolie'},
  { value: 'Îles Mariannes du Nord', viewValue: 'Îles Mariannes du Nord'},
  { value: 'Mozambique', viewValue: 'Mozambique'},
  { value: 'Mauritanie', viewValue: 'Mauritanie'},
  { value: 'Montserrat', viewValue: 'Montserrat'},
  { value: 'Martinique', viewValue: 'Martinique'},
  { value: 'Île Maurice', viewValue:'Île Maurice' },
  { value: 'Malawi', viewValue: 'Malawi'},
  { value: 'Malaisie', viewValue: 'Malaisie' },
  { value: 'Mayotte', viewValue:'Mayotte' },
  { value: 'Namibie', viewValue: 'Namibie'},
  { value: 'Nouvelle-Calédonie', viewValue: 'Nouvelle-Calédonie' },
  { value: 'Niger', viewValue: 'Niger'},
  { value: 'Île Norfolk', viewValue: 'Île Norfolk'},
  { value: 'Nigéria', viewValue: 'Nigéria'},
  { value: 'Nicaragua', viewValue: 'Nicaragua'},
  { value: 'Niue', viewValue:'Niue' },
  { value: 'Pays-Bas', viewValue: 'Pays-Bas'},
  { value: 'Norvège', viewValue:'Norvège' },
  { value: 'Népal', viewValue: 'Népal'},
  { value: 'Nauru' , viewValue:'Nauru'},
  { value: 'Nouvelle-Zélande', viewValue:'Nouvelle-Zélande' },
  { value: 'Oman', viewValue: 'Oman' },
  { value: 'Pakistan' , viewValue:'Pakistan'},
  { value: 'Panama' , viewValue:'Panama'},
  { value: 'Îles Pitcairn', viewValue: 'Îles Pitcairn'},
  { value: 'Pérou', viewValue: 'Pérou'},
  { value: 'Philippines', viewValue: 'Philippines'},
  { value: 'Palaos (Palau)', viewValue:'Palaos (Palau)' },
  { value: 'Papouasie-Nouvelle-Guinée', viewValue: 'Papouasie-Nouvelle-Guinée'},
  { value: 'Pologne' , viewValue:'Pologne'},
  { value: 'Porto Rico', viewValue: 'Porto Rico'},
  { value: 'Corée du Nord', viewValue: 'Corée du Nord'},
  { value: 'Portugal', viewValue:'Portugal' },
  { value: 'Paraguay', viewValue: 'Paraguay'},
  { value: 'Palestine', viewValue: 'Palestine'},
  { value: 'Polynésie française', viewValue:'Polynésie française' },
  { value: 'Qatar', viewValue: 'Qatar'},
  { value: 'Réunion', viewValue: 'Réunion'},
  { value: 'Roumanie', viewValue: 'Roumanie'},
  { value: 'Russie', viewValue: 'Russie'},
  { value: 'Rwanda', viewValue: 'Rwanda'},
  { value: 'Arabie Saoudite', viewValue: 'Arabie Saoudite'},
  { value: 'Soudan', viewValue: 'Soudan'},
  { value: 'Sénégal', viewValue: 'Sénégal'},
  { value: 'Singapour', viewValue: 'Singapour'},
  { value: 'Géorgie du Sud-et-les Îles Sandwich du Sud', viewValue:'Géorgie du Sud-et-les Îles Sandwich du Sud' },
  { value: 'Svalbard et Jan Mayen' , viewValue:'Svalbard et Jan Mayen'},
  { value: 'Îles Salomon', viewValue:'Îles Salomon' },
  { value: 'Sierra Leone', viewValue: 'Sierra Leone'},
  { value: 'Salvador', viewValue: 'Salvador'},
  { value: 'Saint-Marin', viewValue:'Saint-Marin' },
  { value: 'Somalie', viewValue:'Somalie' },
  { value: 'Saint-Pierre-et-Miquelon', viewValue:'Saint-Pierre-et-Miquelon' },
  { value: 'Serbie', viewValue:'Serbie' },
  { value: 'Soudan du Sud', viewValue: 'Soudan du Sud'},
  { value: 'São Tomé et Príncipe', viewValue:'São Tomé et Príncipe' },
  { value: 'Surinam', viewValue: 'Surinam'},
  { value: 'Slovaquie', viewValue: 'Slovaquie'},
  { value: 'Slovénie', viewValue: 'Slovénie'},
  { value: 'Suède', viewValue: 'Suède'},
  { value: 'Swaziland', viewValue:'Swaziland' },
  { value: 'Saint-Martin', viewValue: 'Saint-Martin'},
  { value: 'Seychelles', viewValue: 'Seychelles'},
  { value: 'Syrie', viewValue: 'Syrie'},
  { value: 'Îles Turques-et-Caïques', viewValue:'Îles Turques-et-Caïques' },
  { value: 'Tchad', viewValue: 'Tchad'},
  { value: 'Togo', viewValue: 'Togo'},
  { value: 'Thaïlande', viewValue: 'Thaïlande'},
  { value: 'Tadjikistan', viewValue: 'Tadjikistan'},
  { value: 'Tokelau', viewValue: 'Tokelau'},
  { value: 'Turkménistan', viewValue: 'Turkménistan'},
  { value: 'Timor oriental', viewValue: 'Timor oriental'},
  { value: 'Tonga', viewValue:'Tonga' },
  { value: 'Trinité-et-Tobago', viewValue:'Trinité-et-Tobago' },
  { value: 'Tunisie', viewValue: 'Tunisie'},
  { value: 'Turquie', viewValue: 'Turquie'},
  { value: 'Tuvalu', viewValue: 'Tuvalu'},
  { value: 'Taïwan', viewValue: 'Taïwan'},
  { value: 'Tanzanie', viewValue: 'Tanzanie'},
  { value: 'Ouganda', viewValue: 'Ouganda'},
  { value: 'Ukraine' , viewValue:'Ukraine'},
  { value: 'Îles mineures éloignées des États-Unis', viewValue:'Îles mineures éloignées des États-Unis' },
  { value: 'Uruguay', viewValue: 'Uruguay'},
  { value: 'États-Unis', viewValue: 'États-Unis'},
  { value: 'Ouzbékistan', viewValue: 'Ouzbékistan'},
  { value: 'Cité du Vatican', viewValue: 'Cité du Vatican'},
  { value: 'Saint-Vincent-et-les-Grenadines', viewValue:'Saint-Vincent-et-les-Grenadines' },
  { value: 'Venezuela', viewValue:'Venezuela' },
  { value: 'Îles Vierges britanniques', viewValue: 'Îles Vierges britanniques'},
  { value: 'Îles Vierges des États-Unis', viewValue:'Îles Vierges des États-Unis' },
  { value: 'Viêt Nam', viewValue: 'Viêt Nam'},
  { value: 'Vanuatu', viewValue:'Vanuatu' },
  { value: 'Wallis-et-Futuna', viewValue: 'Wallis-et-Futuna'},
  { value: 'Samoa', viewValue: 'Samoa'},
  { value: 'Yémen', viewValue: 'Yémen'},
  { value: 'Afrique du Sud', viewValue: 'Afrique du Sud'},
  { value: 'Zambie', viewValue: 'Zambie'},
  { value: 'Zimbabwe', viewValue: 'Zimbabwe'}
],


  nationalites: [
    { value: null, viewValue: 'Choissisez une nationalité' },
    { value: "Afghane", viewValue: 'Afghane' },
    { value: "Albanaise", viewValue: 'Albanaise' },
    { value: "Algerienne", viewValue: 'Algerienne' },
    { value: "Allemande", viewValue: 'Allemande' },
    { value: "Americaine", viewValue: 'Americaine' },
    { value: "Andorrane", viewValue: 'Andorrane' },
    { value: "Angolaise", viewValue: 'Angolaise' },
    { value: "Antiguaise et barbudienne", viewValue: 'Antiguaise et barbudienne' },
    { value: "Argentine", viewValue: 'Argentine' },
    { value: "Australienne", viewValue: 'Australienne' },
    { value: "Autrichienne", viewValue: 'Autrichienne' },
    { value: "Azerbaïdjanaise", viewValue: 'Azerbaïdjanaise' },
    { value: "Bahamienne", viewValue: 'Bahamienne' },
    { value: "Bahreinienne", viewValue: 'Bahreinienne' },
    { value: "Bangladaise", viewValue: 'Bangladaise' },
    { value: "Barbadienne", viewValue: 'Barbadienne' },
    { value: "Belge", viewValue: 'Belge' },
    { value: "Belizienne", viewValue: 'Belizienne' },
    { value: "Beninoise", viewValue: 'Beninoise' },
    { value: "Bhoutanaise", viewValue: 'Bhoutanaise' },
    { value: "Bielorusse", viewValue: 'Bielorusse' },
    { value: "Birmane", viewValue: 'Birmane' },
    { value: "Bissau-Guinéenne", viewValue: 'Bissau-Guinéenne' },
    { value: "Bolivienne", viewValue: 'Bolivienne' },
    { value: "Bosnienne", viewValue: 'Bosnienne' },
    { value: "Botswanaise", viewValue: 'Botswanaise' },
    { value: "Britannique", viewValue: 'Britannique' },
    { value: "Bruneienne", viewValue: 'Bruneienne' },
    { value: "Bulgare", viewValue: 'Bulgare' },
    { value: "Burkinabe", viewValue: 'Burkinabe' },
    { value: "Burundaise", viewValue: 'Burundaise' },
    { value: "Cambodgienne", viewValue: 'Cambodgienne' },
    { value: "Camerounaise", viewValue: 'Camerounaise' },
    { value: "Canadienne", viewValue: 'Canadienne' },
    { value: "Cap-verdienne", viewValue: 'Cap-verdienne' },
    { value: "Centrafricaine", viewValue: 'Centrafricaine' },
    { value: "Chilienne", viewValue: 'Chilienne' },
    { value: "Chinoise", viewValue: 'Chinoise' },
    { value: "Chypriote", viewValue: 'Chypriote' },
    { value: "Colombienne", viewValue: 'Colombienne' },
    { value: "Comorienne", viewValue: 'Comorienne' },
    { value: "Congolaise", viewValue: 'Congolaise' },
    { value: "Costaricaine", viewValue: 'Costaricaine' },
    { value: "Croate", viewValue: 'Croate' },
    { value: "Cubaine", viewValue: 'Cubaine' },
    { value: "Danoise", viewValue: 'Danoise' },
    { value: "Djiboutienne", viewValue: 'Djiboutienne' },
    { value: "Dominicaine", viewValue: 'Dominicaine' },
    { value: "Dominiquaise", viewValue: 'Dominiquaise' },
    { value: "Egyptienne", viewValue: 'Egyptienne' },
    { value: "Emirienne", viewValue: 'Emirienne' },
    { value: "Equato-guineenne", viewValue: 'Equato-guineenne' },
    { value: "Equatorienne", viewValue: 'Equatorienne' },
    { value: "Erythreenne", viewValue: 'Erythreenne' },
    { value: "Espagnole", viewValue: 'Espagnole' },
    { value: "Est-timoraise", viewValue: 'Est-timoraise' },
    { value: "Estonienne", viewValue: 'Estonienne' },
    { value: "Ethiopienne", viewValue: 'Ethiopienne' },
    { value: "Fidjienne", viewValue: 'Fidjienne' },
    { value: "Finlandaise", viewValue: 'Finlandaise' },
    { value: "Française", viewValue: 'Française' },
    { value: "Gabonaise", viewValue: 'Gabonaise' },
    { value: "Gambienne", viewValue: 'Gambienne' },
    { value: "Georgienne", viewValue: 'Georgienne' },
    { value: "Ghaneenne", viewValue: 'Ghaneenne' },
    { value: "Grèce", viewValue: 'Grèce' },
    { value: "Grenadienne", viewValue: 'Grenadienne' },
    { value: "Guatemalteque", viewValue: 'Guatemalteque' },
    { value: "Guineenne", viewValue: 'Guineenne' },
    { value: "Guyanienne", viewValue: 'Guyanienne' },
    { value: "Grecque", viewValue: 'Grecque' },
    { value: "Haïtienne", viewValue: 'Haïtienne' },
    { value: "Hellenique", viewValue: 'Hellenique' },
    { value: "Hondurienne", viewValue: 'Hondurienne' },
    { value: "Hongroise", viewValue: 'Hongroise' },
    { value: "Hongrie", viewValue: 'Hongrie' },
    { value: "Indienne", viewValue: 'Indienne' },
    { value: "Indonesienne", viewValue: 'Indonesienne' },
    { value: "Irakienne", viewValue: 'Irakienne' },
    { value: "Irlandaise", viewValue: 'Irlandaise' },
    { value: "Islandaise", viewValue: 'Islandaise' },
    { value: "Italienne", viewValue: 'Italienne' },
    { value: "Ivoirienne", viewValue: 'Ivoirienne' },
    { value: "Jamaïcaine", viewValue: 'Jamaïcaine' },
    { value: "Japonaise", viewValue: 'Japonaise' },
    { value: "Jordanienne", viewValue: 'Jordanienne' },
    { value: "Kazakhstanaise", viewValue: 'Kazakhstanaise' },
    { value: "Kenyane", viewValue: 'Kenyane' },
    { value: "Kirghize", viewValue: 'Kirghize' },
    { value: "Kiribatienne", viewValue: 'Kiribatienne' },
    { value: "Kittitienne-et-nevicienne", viewValue: 'Kittitienne-et-nevicienne' },
    { value: "Kossovienne", viewValue: 'Kossovienne' },
    { value: "Koweitienne", viewValue: 'Koweitienne' },
    { value: "Laotienne", viewValue: 'Laotienne' },
    { value: "Lesothane", viewValue: 'Lesothane' },
    { value: "Lettone", viewValue: 'Lettone' },
    { value: "Libanaise", viewValue: 'Libanaise' },
    { value: "Liberienne", viewValue: 'Liberienne' },
    { value: "Libyenne", viewValue: 'Libyenne' },
    { value: "Liechtensteinoise", viewValue: 'Liechtensteinoise' },
    { value: "Lituanienne", viewValue: 'Lituanienne' },
    { value: "Luxembourgeoise", viewValue: 'Luxembourgeoise' },
    { value: "Macedonienne", viewValue: 'Macedonienne' },
    { value: "Malaisienne", viewValue: 'Malaisienne' },
    { value: "Malawienne", viewValue: 'Malawienne' },
    { value: "Maldivienne", viewValue: 'Maldivienne' },
    { value: "Malgache", viewValue: 'Malgache' },
    { value: "Malienne", viewValue: 'Malienne' },
    { value: "Maltaise", viewValue: 'Maltaise' },
    { value: "Marocaine", viewValue: 'Marocaine' },
    { value: "Marshallaise", viewValue: 'Marshallaise' },
    { value: "Mauricienne", viewValue: 'Mauricienne' },
    { value: "Mauritanienne", viewValue: 'Mauritanienne' },
    { value: "Mexicaine", viewValue: 'Mexicaine' },
    { value: "Micronesienne", viewValue: 'Micronesienne' },
    { value: "Moldave", viewValue: 'Moldave' },
    { value: "Monegasque", viewValue: 'Monegasque' },
    { value: "Mongole", viewValue: 'Mongole' },
    { value: "Montenegrine", viewValue: 'Montenegrine' },
    { value: "Mozambicaine", viewValue: 'Mozambicaine' },
    { value: "Namibienne", viewValue: 'Namibienne' },
    { value: "Nauruane", viewValue: 'Nauruane' },
    { value: "Néerlandaise", viewValue: 'Neerlandaise' },
    { value: "Neo-zelandaise", viewValue: 'Neo-zelandaise' },
    { value: "Nepalaise", viewValue: 'Nepalaise' },
    { value: "Nicaraguayenne", viewValue: 'Nicaraguayenne' },
    { value: "Nigeriane", viewValue: 'Nigeriane' },
    { value: "Nigerienne", viewValue: 'Nigerienne' },
    { value: "Nord-coréenne", viewValue: 'Nord-coréenne' },
    { value: "Norvegienne", viewValue: 'Norvegienne' },
    { value: "Omanaise", viewValue: 'Omanaise' },
    { value: "Ougandaise", viewValue: 'Ougandaise' },
    { value: "Ouzbeke", viewValue: 'Ouzbeke' },
    { value: "Pakistanaise", viewValue: 'Pakistanaise' },
    { value: "Palau", viewValue: 'Palau' },
    { value: "Palestinienne", viewValue: 'Palestinienne' },
    { value: "Panameenne", viewValue: 'Panameenne' },
    { value: "Papouane-neoguineenne", viewValue: 'Papouane-neoguineenne' },
    { value: "Paraguayenne", viewValue: 'Paraguayenne' },
    { value: "Peruvienne", viewValue: 'Peruvienne' },
    { value: "Philippine", viewValue: 'Philippine' },
    { value: "Polonaise", viewValue: 'Polonaise' },
    { value: "Portoricaine", viewValue: 'Portoricaine' },
    { value: "Portugaise", viewValue: 'Portugaise' },
    { value: "Qatarienne", viewValue: 'Qatarienne' },
    { value: "Roumaine", viewValue: 'Roumaine' },
    { value: "Russe", viewValue: 'Russe' },
    { value: "Rwandaise", viewValue: 'Rwandaise' },
    { value: "Saint-lucienne", viewValue: 'Saint-lucienne' },
    { value: "Saint-marinaise", viewValue: 'Saint-marinaise' },
    { value: "Saint-vincentaise-et-grenadine", viewValue: 'Saint-vincentaise-et-grenadine' },
    { value: "Salomonaise", viewValue: 'Salomonaise' },
    { value: "Salvadorienne", viewValue: 'Salvadorienne' },
    { value: "Samoane", viewValue: 'Samoane' },
    { value: "Santomeenne", viewValue: 'Santomeenne' },
    { value: "Saoudienne", viewValue: 'Saoudienne' },
    { value: "Senegalaise", viewValue: 'Senegalaise' },
    { value: "Serbe", viewValue: 'Serbe' },
    { value: "Seychelloise", viewValue: 'Seychelloise' },
    { value: "Sierra-leonaise", viewValue: 'Sierra-leonaise' },
    { value: "Singapourienne", viewValue: 'Singapourienne' },
    { value: "Slovaque", viewValue: 'Slovaque' },
    { value: "Slovene", viewValue: 'Slovene' },
    { value: "Somalienne", viewValue: 'Somalienne' },
    { value: "Soudanaise", viewValue: 'Soudanaise' },
    { value: "Sri-lankaise", viewValue: 'Sri-lankaise' },
    { value: "Sud-africaine", viewValue: 'Sud-africaine' },
    { value: "Sud-coréenne", viewValue: 'Sud-coréenne' },
    { value: "Suedoise", viewValue: 'Suedoise' },
    { value: "Suisse", viewValue: 'Suisse' },
    { value: "Surinamaise", viewValue: 'Surinamaise' },
    { value: "Swazie", viewValue: 'Swazie' },
    { value: "Syrienne", viewValue: 'Syrienne' },
    { value: "Tadjike", viewValue: 'Tadjike' },
    { value: "Taiwanaise", viewValue: 'Taiwanaise' },
    { value: "Tanzanienne", viewValue: 'Tanzanienne' },
    { value: "Tchadienne", viewValue: 'Tchadienne' },
    { value: "Tcheque", viewValue: 'Tcheque' },
    { value: "Thaïlandaise", viewValue: 'Thaïlandaise' },
    { value: "Togolaise", viewValue: 'Togolaise' },
    { value: "Tonguienne", viewValue: 'Tonguienne' },
    { value: "Trinidadienne", viewValue: 'Trinidadienne' },
    { value: "Tunisienne", viewValue: 'Tunisienne' },
    { value: "Turkmene", viewValue: 'Turkmene' },
    { value: "Turque", viewValue: 'Turque' },
    { value: "Tuvaluane", viewValue: 'Tuvaluane' },
    { value: "Ukrainienne", viewValue: 'Ukrainienne' },
    { value: "Uruguayenne", viewValue: 'Uruguayenne' },
    { value: "Vanuatuane", viewValue: 'Vanuatuane' },
    { value: "Venezuelienne", viewValue: 'Venezuelienne' },
    { value: "Vietnamienne", viewValue: 'Vietnamienne' },
    { value: "Yemenite", viewValue: 'Yemenite' },
    { value: "Zambienne", viewValue: 'Zambienne' },
    { value: "Zimbabweenne", viewValue: 'Zimbabweenne' },

  ],

  nationalites_UE: [
    { value: "Allemande", viewValue: 'Allemande' },
    { value: "Autrichienne", viewValue: 'Autrichienne' },
    { value: "Belge", viewValue: 'Belge' },
    { value: "Danoise", viewValue: 'Danoise' },
    { value: "Espagnole", viewValue: 'Espagnole' },
    { value: "Estonienne", viewValue: 'Estonienne' },
    { value: "Finlandaise", viewValue: 'Finlandaise' },
    { value: "Française", viewValue: 'Française' },
    { value: "Grèce", viewValue: 'Grèce' },
    { value: "Hongrie", viewValue: 'Hongrie' },
    { value: "Islandaise", viewValue: 'Islandaise' },
    { value: "Italienne", viewValue: 'Italienne' },
    { value: "Liechtensteinoise", viewValue: 'Liechtensteinoise' },
    { value: "Lituanienne", viewValue: 'Lituanienne' },
    { value: "Lettone", viewValue: 'Lettone' },
    { value: "Luxembourgeoise", viewValue: 'Luxembourgeoise' },
    { value: "Maltaise", viewValue: 'Maltaise' },
    { value: "Norvegienne", viewValue: 'Norvegienne' },
    { value: "Néerlandaise", viewValue: 'Néerlandaise' },
    { value: "Polonaise", viewValue: 'Polonaise' },
    { value: "Portugaise", viewValue: 'Portugaise' },
    { value: "Slovaque", viewValue: 'Slovaque' },
    { value: "Slovene", viewValue: 'Slovene' },
    { value: "Suedoise", viewValue: 'Suedoise' },
    { value: "Suisse", viewValue: 'Suisse' },
    { value: "Tcheque", viewValue: 'Tcheque' },
  ],

  nationalitesEDU: [
    { value: "Afghane", viewValue: 'Afghane' },
    { value: "Albanaise", viewValue: 'Albanaise' },
    { value: "Algerienne", viewValue: 'Algerienne' },
    { value: "Americaine", viewValue: 'Americaine' },
    { value: "Andorrane", viewValue: 'Andorrane' },
    { value: "Angolaise", viewValue: 'Angolaise' },
    { value: "Antiguaise et barbudienne", viewValue: 'Antiguaise et barbudienne' },
    { value: "Argentine", viewValue: 'Argentine' },
    { value: "Australienne", viewValue: 'Australienne' },
    { value: "Azerbaïdjanaise", viewValue: 'Azerbaïdjanaise' },
    { value: "Bahamienne", viewValue: 'Bahamienne' },
    { value: "Bahreinienne", viewValue: 'Bahreinienne' },
    { value: "Bangladaise", viewValue: 'Bangladaise' },
    { value: "Barbadienne", viewValue: 'Barbadienne' },
    { value: "Belizienne", viewValue: 'Belizienne' },
    { value: "Beninoise", viewValue: 'Beninoise' },
    { value: "Bhoutanaise", viewValue: 'Bhoutanaise' },
    { value: "Bielorusse", viewValue: 'Bielorusse' },
    { value: "Birmane", viewValue: 'Birmane' },
    { value: "Bissau-Guinéenne", viewValue: 'Bissau-Guinéenne' },
    { value: "Bolivienne", viewValue: 'Bolivienne' },
    { value: "Bosnienne", viewValue: 'Bosnienne' },
    { value: "Botswanaise", viewValue: 'Botswanaise' },
    { value: "Britannique", viewValue: 'Britannique' },
    { value: "Bruneienne", viewValue: 'Bruneienne' },
    { value: "Bulgare", viewValue: 'Bulgare' },
    { value: "Burkinabe", viewValue: 'Burkinabe' },
    { value: "Burundaise", viewValue: 'Burundaise' },
    { value: "Cambodgienne", viewValue: 'Cambodgienne' },
    { value: "Camerounaise", viewValue: 'Camerounaise' },
    { value: "Canadienne", viewValue: 'Canadienne' },
    { value: "Cap-verdienne", viewValue: 'Cap-verdienne' },
    { value: "Centrafricaine", viewValue: 'Centrafricaine' },
    { value: "Chilienne", viewValue: 'Chilienne' },
    { value: "Chinoise", viewValue: 'Chinoise' },
    { value: "Chypriote", viewValue: 'Chypriote' },
    { value: "Colombienne", viewValue: 'Colombienne' },
    { value: "Comorienne", viewValue: 'Comorienne' },
    { value: "Congolaise", viewValue: 'Congolaise' },
    { value: "Costaricaine", viewValue: 'Costaricaine' },
    { value: "Croate", viewValue: 'Croate' },
    { value: "Cubaine", viewValue: 'Cubaine' },
    { value: "Djiboutienne", viewValue: 'Djiboutienne' },
    { value: "Dominicaine", viewValue: 'Dominicaine' },
    { value: "Dominiquaise", viewValue: 'Dominiquaise' },
    { value: "Egyptienne", viewValue: 'Egyptienne' },
    { value: "Emirienne", viewValue: 'Emirienne' },
    { value: "Equato-guineenne", viewValue: 'Equato-guineenne' },
    { value: "Equatorienne", viewValue: 'Equatorienne' },
    { value: "Erythreenne", viewValue: 'Erythreenne' },
    { value: "Est-timoraise", viewValue: 'Est-timoraise' },
    { value: "Ethiopienne", viewValue: 'Ethiopienne' },
    { value: "Fidjienne", viewValue: 'Fidjienne' },
    { value: "Gabonaise", viewValue: 'Gabonaise' },
    { value: "Gambienne", viewValue: 'Gambienne' },
    { value: "Georgienne", viewValue: 'Georgienne' },
    { value: "Ghaneenne", viewValue: 'Ghaneenne' },
    { value: "Grenadienne", viewValue: 'Grenadienne' },
    { value: "Guatemalteque", viewValue: 'Guatemalteque' },
    { value: "Guineenne", viewValue: 'Guineenne' },
    { value: "Guyanienne", viewValue: 'Guyanienne' },
    { value: "Grecque", viewValue: 'Grecque' },
    { value: "Haïtienne", viewValue: 'Haïtienne' },
    { value: "Hellenique", viewValue: 'Hellenique' },
    { value: "Hondurienne", viewValue: 'Hondurienne' },
    { value: "Hongroise", viewValue: 'Hongroise' },
    { value: "Indienne", viewValue: 'Indienne' },
    { value: "Indonesienne", viewValue: 'Indonesienne' },
    { value: "Irakienne", viewValue: 'Irakienne' },
    { value: "Irlandaise", viewValue: 'Irlandaise' },
    { value: "Ivoirienne", viewValue: 'Ivoirienne' },
    { value: "Jamaïcaine", viewValue: 'Jamaïcaine' },
    { value: "Japonaise", viewValue: 'Japonaise' },
    { value: "Jordanienne", viewValue: 'Jordanienne' },
    { value: "Kazakhstanaise", viewValue: 'Kazakhstanaise' },
    { value: "Kenyane", viewValue: 'Kenyane' },
    { value: "Kirghize", viewValue: 'Kirghize' },
    { value: "Kiribatienne", viewValue: 'Kiribatienne' },
    { value: "Kittitienne-et-nevicienne", viewValue: 'Kittitienne-et-nevicienne' },
    { value: "Kossovienne", viewValue: 'Kossovienne' },
    { value: "Koweitienne", viewValue: 'Koweitienne' },
    { value: "Laotienne", viewValue: 'Laotienne' },
    { value: "Lesothane", viewValue: 'Lesothane' },
    { value: "Libanaise", viewValue: 'Libanaise' },
    { value: "Liberienne", viewValue: 'Liberienne' },
    { value: "Libyenne", viewValue: 'Libyenne' },
    { value: "Macedonienne", viewValue: 'Macedonienne' },
    { value: "Malaisienne", viewValue: 'Malaisienne' },
    { value: "Malawienne", viewValue: 'Malawienne' },
    { value: "Maldivienne", viewValue: 'Maldivienne' },
    { value: "Malgache", viewValue: 'Malgache' },
    { value: "Malienne", viewValue: 'Malienne' },
    { value: "Marocaine", viewValue: 'Marocaine' },
    { value: "Marshallaise", viewValue: 'Marshallaise' },
    { value: "Mauricienne", viewValue: 'Mauricienne' },
    { value: "Mauritanienne", viewValue: 'Mauritanienne' },
    { value: "Mexicaine", viewValue: 'Mexicaine' },
    { value: "Micronesienne", viewValue: 'Micronesienne' },
    { value: "Moldave", viewValue: 'Moldave' },
    { value: "Monegasque", viewValue: 'Monegasque' },
    { value: "Mongole", viewValue: 'Mongole' },
    { value: "Montenegrine", viewValue: 'Montenegrine' },
    { value: "Mozambicaine", viewValue: 'Mozambicaine' },
    { value: "Namibienne", viewValue: 'Namibienne' },
    { value: "Nauruane", viewValue: 'Nauruane' },
    { value: "Neo-zelandaise", viewValue: 'Neo-zelandaise' },
    { value: "Nepalaise", viewValue: 'Nepalaise' },
    { value: "Nicaraguayenne", viewValue: 'Nicaraguayenne' },
    { value: "Nigeriane", viewValue: 'Nigeriane' },
    { value: "Nigerienne", viewValue: 'Nigerienne' },
    { value: "Nord-coréenne", viewValue: 'Nord-coréenne' },
    { value: "Omanaise", viewValue: 'Omanaise' },
    { value: "Ougandaise", viewValue: 'Ougandaise' },
    { value: "Ouzbeke", viewValue: 'Ouzbeke' },
    { value: "Pakistanaise", viewValue: 'Pakistanaise' },
    { value: "Palau", viewValue: 'Palau' },
    { value: "Palestinienne", viewValue: 'Palestinienne' },
    { value: "Panameenne", viewValue: 'Panameenne' },
    { value: "Papouane-neoguineenne", viewValue: 'Papouane-neoguineenne' },
    { value: "Paraguayenne", viewValue: 'Paraguayenne' },
    { value: "Peruvienne", viewValue: 'Peruvienne' },
    { value: "Philippine", viewValue: 'Philippine' },
    { value: "Portoricaine", viewValue: 'Portoricaine' },
    { value: "Qatarienne", viewValue: 'Qatarienne' },
    { value: "Roumaine", viewValue: 'Roumaine' },
    { value: "Russe", viewValue: 'Russe' },
    { value: "Rwandaise", viewValue: 'Rwandaise' },
    { value: "Saint-lucienne", viewValue: 'Saint-lucienne' },
    { value: "Saint-marinaise", viewValue: 'Saint-marinaise' },
    { value: "Saint-vincentaise-et-grenadine", viewValue: 'Saint-vincentaise-et-grenadine' },
    { value: "Salomonaise", viewValue: 'Salomonaise' },
    { value: "Salvadorienne", viewValue: 'Salvadorienne' },
    { value: "Samoane", viewValue: 'Samoane' },
    { value: "Santomeenne", viewValue: 'Santomeenne' },
    { value: "Saoudienne", viewValue: 'Saoudienne' },
    { value: "Senegalaise", viewValue: 'Senegalaise' },
    { value: "Serbe", viewValue: 'Serbe' },
    { value: "Seychelloise", viewValue: 'Seychelloise' },
    { value: "Sierra-leonaise", viewValue: 'Sierra-leonaise' },
    { value: "Singapourienne", viewValue: 'Singapourienne' },
    { value: "Somalienne", viewValue: 'Somalienne' },
    { value: "Soudanaise", viewValue: 'Soudanaise' },
    { value: "Sri-lankaise", viewValue: 'Sri-lankaise' },
    { value: "Sud-africaine", viewValue: 'Sud-africaine' },
    { value: "Sud-coréenne", viewValue: 'Sud-coréenne' },
    { value: "Surinamaise", viewValue: 'Surinamaise' },
    { value: "Swazie", viewValue: 'Swazie' },
    { value: "Syrienne", viewValue: 'Syrienne' },
    { value: "Tadjike", viewValue: 'Tadjike' },
    { value: "Taiwanaise", viewValue: 'Taiwanaise' },
    { value: "Tanzanienne", viewValue: 'Tanzanienne' },
    { value: "Tchadienne", viewValue: 'Tchadienne' },
    { value: "Thaïlandaise", viewValue: 'Thaïlandaise' },
    { value: "Togolaise", viewValue: 'Togolaise' },
    { value: "Tonguienne", viewValue: 'Tonguienne' },
    { value: "Trinidadienne", viewValue: 'Trinidadienne' },
    { value: "Tunisienne", viewValue: 'Tunisienne' },
    { value: "Turkmene", viewValue: 'Turkmene' },
    { value: "Turque", viewValue: 'Turque' },
    { value: "Tuvaluane", viewValue: 'Tuvaluane' },
    { value: "Ukrainienne", viewValue: 'Ukrainienne' },
    { value: "Uruguayenne", viewValue: 'Uruguayenne' },
    { value: "Vanuatuane", viewValue: 'Vanuatuane' },
    { value: "Venezuelienne", viewValue: 'Venezuelienne' },
    { value: "Vietnamienne", viewValue: 'Vietnamienne' },
    { value: "Yemenite", viewValue: 'Yemenite' },
    { value: "Zambienne", viewValue: 'Zambienne' },
    { value: "Zimbabweenne", viewValue: 'Zimbabweenne' },

  ],
  entreprises: [
    { value: "ESTYA Education", viewValue: 'ESTYA Education' },
    { value: "ESTYA Training", viewValue: 'ESTYA Training' },
    { value: "Académie des gouvernantes", viewValue: 'Académie des gouvernantes' },

  ],
  status: [
    { label: "À traiter", value: 'À traiter' },
    { label: "En cours de traitement", value: 'En cours de traitement' },
    { label: "En attente de retour", value: 'En attente de retour' },
    { label: "Clôturé", value: 'Clôturé' }
  ],
  etat_annee: [
    { label: "Nouvelle", value: 'Nouvelle' },
    { label: "Active", value: 'Active' },
    { label: "Archivée", value: 'Archivée' },

  ],
};
/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
